### ISSUE TITLE
Cant use folders inside events

### ISSUE THREAD

**Issue by xitude** [laravel/echo#100]
I'm unable to listen to events that have a folder in namespaces, it's getting a bit cluttered inside my events folder.

**Comment by RusinovAnton** [comment]
Hi, could you please give an example of what are you trying to say?

**Comment by xitude** [comment]
For instance, if I put an event in a folder such `/foo/bar.php` when it reaches pusher it will include the folder inside the namespace like `/foo/BarEvent` this will not work when called in my js. If I drop the file up a directory so it's just `/BarEvent` it now works. I have around 67 events now all in a single folder and naming them is becoming ugly as I can not separate them into folders.

**Comment by philbenoit** [comment]
@xitude I think you need to add the broadcastAs method to your event classes. This is not really an issue with Echo but rather with the laravel broadcast setup. 

You should be able to solve your issue with this doc https://laravel.com/docs/5.4/broadcasting#broadcast-name

**Comment by xitude** [comment]
@philbenoit. Thanks for the tip. I'll give it a go.

**Comment by blessingk** [comment]
Worked for me thanks
