### ISSUE TITLE
channel().whisper is not implemented

### ISSUE THREAD

**Issue by halper** [laravel/echo#103]
When I try to use Echo.channel('...').whisper I got an error that it is not a function. Probably I'm doing something wrong, but is it possible that whisper is not implemented?

**Comment by Luppakorva** [comment]
@halper having the same problem. Where you able to solve it?

**Comment by halper** [comment]
@Luppakorva unfortunately I am not that advanced, so handle it through server without using whisper. But I'm waiting on the solution.

**Comment by torrancemiller** [comment]
I see it in @taylorotwell's docs, but not in the code for laravel-echo.  Different version on npm maybe?

**Comment by torrancemiller** [comment]
Nevermind, found a fix. Try this guys:
Echo.private('chat').whisper('chat',{name: 'Tor Miller is typing...'});

**Comment by Luppakorva** [comment]
@torrancemiller thanks, seems to work in private indeed, I check if it can be added to public channels as well

**Comment by halper** [comment]
Thanks @torrancemiller, related documents should be updated accordingly.

**Comment by philbenoit** [comment]
@taylorotwell I think you can close this now as the docs are updated.

**Comment by shadoWalker89** [comment]
Why should the whisper() feature be related to private channels ?
It would be very helpful to have it on public channels as well

**Comment by vesper8** [comment]
So is it possible or not to whisper on public (not authorized) channels ?

**Comment by merijndk** [comment]
I would like to whisper on public channels aswell?

**Comment by vesper8** [comment]
I could not figure out a way to do this so I came up with a workaround which creates users for and logs in visitors to my site automatically, this happens transparently and once they are logged in then I am able to do whatever I want with Echo.. bit cumbersome but it works
