### ISSUE TITLE
Connection failed to to suspension?

### ISSUE THREAD

**Issue by CowboyDiplomacy** [laravel/echo#111]
Was working perfectly, then I get the following message in the console:

"WebSocket connection to 'ws://localhost' failed: WebSocket is closed due to suspension.

No ideas as to what's causing this.

**Comment by tomtom87** [comment]
+1 Got it too

**Comment by timgavin** [comment]
Got it as well.

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
