### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by Skintillion** [laravel/echo#112]
Having this error when trying to create a connection in NativeScript.

It errors on the first 'window' saying it is not defined.

```
if (window && window['Laravel'] && window['Laravel'].csrfToken) {
            return window['Laravel'].csrfToken;
        } else if (this.options.csrfToken) {
            return this.options.csrfToken;
        } else if (typeof document !== 'undefined' && (selector = document.querySelector('meta[name="csrf-token"]'))) {
            return selector.getAttribute('content');
        }
```

**Comment by Skintillion** [comment]
If I remove the references to window since I have the CSRF token specified in options, it gives another error on the io function.

**Comment by okaufmann** [comment]
When the next version will be released you can pass the io-module as option parameter and it does check if window if its available. See details: https://github.com/laravel/echo/pull/160

**Comment by driesvints** [comment]
Released now.
