### ISSUE TITLE
why orderId is not defined in echo private ?

### ISSUE THREAD

**Issue by thandonguocmo2020** [laravel/echo#115]
channel.php

Broadcast::channel('order.{orderId}', function ($user, $orderId) {
    return $user->id === Order::findOrNew($orderId)->user_id;
});

event broads : 

public function broadcastOn()
{
    return new PrivateChannel('order.'.$this->update->order_id);
}

echo javascript : 

Echo.private(`order.${orderId}`)
    .listen('ShippingStatusUpdated', (e) => {
        console.log(e.update);
    });

orderId is not defined  in console. Help !

orderId  where  from?

**Comment by xparthx** [comment]
Finally, there is someone who gets same error like me.

Have you got any solution yet?

Thanks

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.

**Comment by reigningkingforever** [comment]
I've been experiencing this since morning today. Please how did you all solve it
