### ISSUE TITLE
Its not supporting angularjs

### ISSUE THREAD

**Issue by kalidasweb** [laravel/echo#117]

**Comment by jastend** [comment]
Hi @kalidasweb,

You can just add the normal Laravel Echo Code in order to listen to channels. Here's an example with a custom function that you can call via `echoListen();`:
```
var echoListen = function() {
	window.Echo.channel('channel-messages')
	.listen('NewMessage', (e) => {
		console.log(e.message);

		$scope.$apply(function() {
			$scope.data.messages.push(e.message);
		});
	});
};
```

Of course, you could also put this into a directive etc.

**Comment by kalidasweb** [comment]
thanks @jastend already i done that :+1:

**Comment by RichardFans** [comment]
@kalidasweb  how can i do when i use es5 that  do not support "import Echo from "laravel-echo""??
