### ISSUE TITLE
binding  “pusher:subscribe” event to channel not working

### ISSUE THREAD

**Issue by sureshamk** [laravel/echo#120]
In my laravel application i am using laravel ECHO. In this I'm trying to listen a event "pusher:subscribe" through on method. But I its not happening. I can able to subscribe, add_memeber, remove_memeber as per laravel echo documentation. But i cannot able to listen specifically "pusher:subscribe" event. Actually I am trying to get data from this event and i will manipulate further

```
window.Echo = new Echo({
  broadcaster: 'pusher',
  key: 'myKeyHere',
  authEndpoint: 'pusher/auth',
  auth: {
    headers: {},
    params: {
      username: this.username
    }
  }
});
window.Echo.join('openChat').here((users) => {
  console.log(users);

}).listen('MessagePublished', (e) => {
  console.log('Message Received');

}).on('pusher:subscribe', (users) => {
  console.log('NOT WORKING');

}).joining((user) => {
  console.log('User Joined');
}).leaving((user) => {
  console.log('User gone');
});
```

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
