### ISSUE TITLE
How to leave all channels in Laravel Echo at once

### ISSUE THREAD

**Issue by shorlbeck** [laravel/echo#124]
I didn't see anything in the documentation about how to leave all channels at once. After poking around, I discovered it can be accomplished by looping over `Echo.connector.channels` and calling `Echo.leave(channelName)` where `channelName` is each key in that object. I'd love for there to be an official, built-in method such as `Echo.leaveAll()` but even if there will never be one, I am posting this here so that other developers who are searching for this can get a quick answer.

**Comment by maxpaynestory** [comment]
There is a disconnect function now available inside Echo, If you wish to stop receiving messages from all channels you could disconnect and open a new Echo instance later.

**Comment by clod986** [comment]
@maxpaynestory I'm new to npm, but how do I download the latest version?

Running `npm outdated` doesn't include laravel-echo, but I've checked the source and I didn't get your commits on this regard.

**Comment by ilyaDegtyarenko** [comment]
`Echo.disconnect();`
