### ISSUE TITLE
notification data structure

### ISSUE THREAD

**Issue by xralphack** [laravel/echo#127]
```
// client side 

Echo.private(`App.User.${userId}`)
    .notification((notification) => {
        console.log(notification);
    });

```
notification object here is

id: "184112d4-6451-468e-a652-4376bbc6457f"
link:"xxxx"
message:"xxxx"
socket:null
type:"App\Notifications\UserHasNewInvitation"

```
// server side

auth()->user()->unreadNotifications;

```
notification object here is

created_at:"2017-07-01 16:26:39"
data:Object
id:"022a3216-507c-47d3-8ae8-e4415a21043a"
notifiable_id:18
notifiable_type:"App\\User"
read_at:null
type:"App\\Notifications\\UserHasNewInvitation"
updated_at:"2017-07-01 16:26:39"

is there any chance to make the notification object structure identical 
on server side and client side

**Comment by driesvints** [comment]
I'm not really sure what you're trying to do. You can use the `broadcastWith` to manipulate the data structure.

https://laravel.com/docs/5.7/broadcasting#broadcast-data
