### ISSUE TITLE
Event frames being received but not picked up by .listen

### ISSUE THREAD

**Issue by thorlucas** [laravel/echo#130]
I'm trying to broadcast a simple event using Redis, Laravel Echo, Laravel Echo Server, and socket.io.
I've got everything in place on the client side. The message is indeed being broadcasted and laravel echo server is picking up on it.

On chat.dev/ I have the client joining. On chat.dev/new I have the event being broadcast.

```
[5:14:31 PM] - HvEq_a12YnQFJGFiAAAE joined channel: chat
Channel: chat
Event: message.created
CHANNEL chat
```

So it seems like everything is working. On the client side, I'm including socket.io and it is finding it.

`<script src="//{{ Request::getHost() }}:6001/socket.io/socket.io.js"></script>`

Then I'm running

```
import Echo from 'laravel-echo'

window.Echo = new Echo({
    broadcaster: 'socket.io',
    host: window.location.hostname + ':6001'
});


window.Echo.channel('chat')
    .listen('.message.created', (e) => {
        console.log("Got message");
    });
```

In the dev tools, I can see that the frame is indeed being received, with the proper channel and event name.

```
42["message.created", "chat", {,…}]
0
:
"message.created"
1
:
"chat"
2
:
{,…}
message
:
{id: 23, body: "Modified", created_at: "2017-07-19 01:11:18", updated_at: "2017-07-19 01:11:18"}
socket
:
null
```

But nothing is being logged to the console. Why?

**Comment by a1tem** [comment]
Same here.

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
