### ISSUE TITLE
Fanout.io-based connector

### ISSUE THREAD

**Issue by jkarneges** [laravel/echo#142]
Hi there,

I'm the founder of [Fanout](https://fanout.io), sort of an alternative to Pusher that's more geared towards API creators. Also our server is open source and can be run standalone.

We're interested in adding official support for Fanout in Laravel Echo. Please let me know if this would be of interest and if so we'll develop the feature and submit a PR.

Thanks!

**Comment by masterix21** [comment]
I think that one beautiful things is to add the support for a custom connector on the Laravel Echo constructor. It should open the support for unlimited services.

**Comment by driesvints** [comment]
Heya. Thanks but we have no plans for this now. I do however agree that a custom connecter setup might be cool but I have no idea how that could be implemented. Feel free to send in a PR for that if you can implement it in a clean way.
