### ISSUE TITLE
Can not find information about supported Browsers and potential fallback mode?

### ISSUE THREAD

**Issue by wowcut** [laravel/echo#146]
Hi, I can not find any information about what browsers are supported - also I would like to know if this library has a fallback mode that would help with old Browsers that still do not have support for websockets? 

Thanks for your attention!

**Comment by kohenkatz** [comment]
This library does not handle any communication with the server. It uses (right now) either Pusher.js or Socket.io. Each of those has its own requirements and you should check their respective websites for more details.
