### ISSUE TITLE
1.3.0 - 1.3.2 - Breaking changes

### ISSUE THREAD

**Issue by catalinux** [laravel/echo#147]
I think that this changes https://github.com/laravel/echo/commit/7b7dd5f1bd0b6bf60140ce6d2594b3fd0357eb7c?diff=split added breacking changes.

**In 1.3.0 we had following**

PHP: 
```php
public function broadcastAs()
    {
        return 'alerts\created';
    }
```

JS:

```js
channel.listen('.alerts.created', (event) => {})
````

Everything worked great, because `EventFormatter` would return `alerts\created`

**Now in 1.3.2** 

when I do `channel.listen('.alerts.created', (event) => {})` it will look for `alerts.created`  (that is what EventFormmatter` returns)

Is there a way we could prevent other users to spent hours in debugging.   Minor versions should not add  breaking changes

**Comment by mbarwick83** [comment]
Any update on this? Notifications are no longer working for me, running 1.3.2

**Comment by catalinux** [comment]
You have to adapt your event names from  php app

**Comment by mbarwick83** [comment]
Thanks. But do you care to elaborate? I'm using echo's `.notification` method.

**Comment by ellisio** [comment]
Please refer to this PR for _why_ the way you were implementing was actually the broken way. The PR was merged to align the code with the documentation.

https://github.com/laravel/echo/pull/140

**Comment by robclancy** [comment]
Lack of a changelog for this makes it risky to update anything.

**Comment by ellisio** [comment]
If you followed the Laravel documentation, then you are fine and the risk is minimal.
