### ISSUE TITLE
[Question] could Echo be used with SharedWorkers ?

### ISSUE THREAD

**Issue by ctf0** [laravel/echo#148]
am using https://github.com/pusher-community/pusher-with-shared-workers as a route to follow

and the main issue is with the [shared_worker](https://github.com/pusher-community/pusher-with-shared-workers/blob/master/shared_worker.js)

first i tried to add echo in that file like so
```js
importScripts('pusher.worker.min.js')

import Echo from "laravel-echo"
window.Echo = new Echo({
    broadcaster: process.env.MIX_BROADCAST_DRIVER,
    key: process.env.MIX_PUSHER_APP_KEY,
    cluster: process.env.MIX_PUSHER_APP_CLUSTER,
    encrypted: process.env.MIX_PUSHER_APP_ENCRYPT
});

let clients = []

Echo.channel('channel-name').listen('Testing', (data) => {
    clients.forEach((client) => {
        client.postMessage(data)
    })
})

...
```

but didnt work, also tried to register it in the main `app.js` and call it from the `window` but again no luck.

lastly tried using the **echo.js** directly `importScripts("pusher.worker.js, echo.js");` but nothing changed, so is there a way to get echo to work with SharedWorkers ?

**Comment by iamvinny** [comment]
Have you figured it out? I'm struggling to achieve the same...

**Comment by ctf0** [comment]
@iamvinny here is an example of what i have tried https://github.com/ctf0/laravel-pusher-sharedworkers

**Comment by Aaron3219** [comment]
Was it successful?
