### ISSUE TITLE
is possible react-native use laravel-echo?

### ISSUE THREAD

**Issue by learnmove** [laravel/echo#150]
any one achive?
I make chat app 
I did vue.js chat with laravel-echo ,work fine
I like laravel-echo agile 
so
is possible create chat app in react-native  with laravel-echo?

**Comment by kohenkatz** [comment]
See #144 and others

**Comment by okaufmann** [comment]
When the next version will be released you can pass the io-module as option parameter and it does check if window if its available. See details: https://github.com/laravel/echo/pull/160

**Comment by driesvints** [comment]
Please try with the latest versions again. Feel free to reply if it still doesn't works.
