### ISSUE TITLE
Uncaught TypeError: Cannot read property ‘socketId’ of undefined

### ISSUE THREAD

**Issue by matrunchyk** [laravel/echo#154]
When the socket.io server is down it happens that the whole application is down because of [intervention to the global namespace of axios](https://github.com/laravel/echo/blob/master/src/echo.ts#L68) (and other connection drivers).

[There](https://github.com/laravel/echo/blob/master/src/echo.ts#L144) is no check if the connector is defined or not. Do you think it might be a good idea to add some `if` case or a ternary one?

Thanks.

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.

**Comment by robertnicjoo** [comment]
@driesvints where did it solved? please share the link of issue that solved this issue.
