### ISSUE TITLE
private channel status callback

### ISSUE THREAD

**Issue by xralphack** [laravel/echo#158]
My Client can successfully joined private channel

```
window.echo.private('App.User.' + me.id)
  .notification((notification) => {
    console.log(notification.type);
});
```

I want to get the status as user joining or leaving the private, anyone can help?

thanks~

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs or problems. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
