### ISSUE TITLE
[Version 1.3.4] Can't receive events after update

### ISSUE THREAD

**Issue by kiriunin** [laravel/echo#167]
Version 1.3.4 is not receiving any events unlike the previous version (1.3.3).

**Comment by mpyw** [comment]
We should revert this PR

[Fix event formatter bug by sebastiandedeyne · Pull Request #165 · laravel/echo](https://github.com/laravel/echo/pull/165)

**Comment by mpyw** [comment]
@kiriunin Workaround

```php
/**
 * The event's broadcast name.
 *
 * @return string
 */
public function broadcastAs()
{
    return 'server.created';
}
```

```diff
- .listen('.server.created', function (e) {
+ .on('server.created', function (e) {
     ....
 });
```

**Comment by kiriunin** [comment]
@mpyw Thank you, it works for me!

@taylorotwell This PR breaks official documentation...

**Comment by mpyw** [comment]
Merged
