### ISSUE TITLE
Doesn't work with token based authentication

### ISSUE THREAD

**Issue by mattmcdonald-uk** [laravel/echo#17]
If you're connecting to /broadcasting/socket on another server you'll often be using token based authentication with the Authorization header.

Currently that can be passed to the auth method using its 'headers' option, but isn't supported elsewhere.

Happy to put in a PR for this, but wanted feedback first on the preferred approach.

Would it be better to allow an arbitrary set of additional headers be passed and applied when creating the request (https://github.com/laravel/echo/blob/master/src/connector/pusher-connector.ts#L47), or just allow an authorization token be passed and send that header if provided?

**Comment by taylorotwell** [comment]
Maybe just let an array of custom headers be passed?

**Comment by morloderex** [comment]
@taylorotwell That might be a good idea maybe though the options object.

**Comment by mattmcdonald-uk** [comment]
Closing as this no longer seems relevant - /broadcasting/socket no longer requested
