### ISSUE TITLE
how to change pusher's host ?

### ISSUE THREAD

**Issue by spmsupun** [laravel/echo#171]
when it's using pusher-js alone we can change the ws host,
```
let pusher = new Pusher('123456', {
  wsHost: '192.168.10.10',
  wsPort: '8080',
  wssPort: '8080',
  enabledTransports: ['ws', 'flash']
});
```
is there a way to change wsHost when we using Echo?

This doesn't work:
```
window.Echo = new Echo({
  broadcaster: 'pusher',
  host: '192.168.10.10',
 key:'123'
});
```
it's still go to ws://ws.pusher.com

**Comment by laravuel** [comment]
up

**Comment by innivodave** [comment]
You should use wsHost and httpHost for the JS config. 'host' is used for the php config

```
window.Echo = new Echo({
  broadcaster: 'pusher',
  httpHost: '192.168.10.10',
  wsHost: '192.168.10.10',
  key:'123'
});
```

**Comment by vesper8** [comment]
@spmsupun @innivodave 

My vue site is https://www.xxx.com
and my Laravel api is https://api.xxx.com

I use Laravel Echo with Pusher and it always wants to use https://www.xxx.com/broadcasting/auth to join my channels.

I need it to be https://api.xxx.com/broadcasting/auth

I have jwt.auth and cors working correctly already, but no matter what I do, setting the host, wsHost or httpHost, it doesn't respect my setting. It ignores it completely if I change the 'host' and if I set the wsHost/httpHost it then tries to connect to a /pusher/app url with lots of url parameters and doesn't try to connect to /broadcasting/auth anymore

I'm really stuck here.. some help would be so appreciated!

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.

**Comment by burimdervishollirrota** [comment]
@vesper8 I've been looking for 3 days for this solutions thanks a lot man
