### ISSUE TITLE
understanding how many Pusher connections are used 

### ISSUE THREAD

**Issue by vesper8** [laravel/echo#172]
Hi there, I've been using Laravel Echo for a few months and just now I am about to reach the end of the Pusher free tier, that is to say I am getting close to having more than 100 concurrent connections according to Pusher's dashboard.

However it occurred to me today that it seems like my users are using 2 connections each instead of just 1.. 

I read "how are connections counted" here https://support.pusher.com/hc/en-us/articles/202092346-How-are-connections-counted-

And it seems like my users should only be using 1 connection.. but since Echo is abstracting the instantiation of Pusher.. I'm not completely sure what's going on.

So my question is this.. looking at the code below.. how many connections am I using per user? 1? or is it 2?

```
Echo.private(`App.User.${user.id}`).notification(notification => {
    ...
});

Echo.private(`notifications.${user.id}`).listen(".App\\Events\\NewNotification", e => {
    ...
});

Echo.private(`notifications.${user.id}`).listen(".App\\Events\\MessageBroadcast", e => {
    ...
});

Echo.join("online").here(users => {
    this.$store.state.navigation.usersOnline = users;
    this.usersOnline = users;
})
.joining(user => {
    this.$store.state.navigation.usersOnline.push(user);
    this.usersOnline.push(user);
})
.leaving(user => {
    this.$store.state.navigation.usersOnline = this.$store.state.navigation.usersOnline.filter(u => u != user);
    this.usersOnline = this.usersOnline.filter(u => u != user);
});

Echo.join(`chatroom.${id}`).here(users => {
    this.usersInRoom = users;
})
.joining(user => {
    this.usersInRoom.push(user);
})
.leaving(user => {
    this.usersInRoom = this.usersInRoom.filter(u => u != user);
})
.listen(".App\\Events\\MessagePosted", e => {
    ...
});
```

**Comment by Mat-Moo** [comment]
Came on to ask exactly the same thing. For some reason I've got a sending app and a receiving app... the receiving part is using 2 connections per tab whilst the sender only 1. Can't fathom it, did you get any further?

**Comment by driesvints** [comment]
Can you first please try one of the following support channels? If you can actually identify this as a bug, feel free to report back.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
