### ISSUE TITLE
Uncaught TypeError: io is not a function

### ISSUE THREAD

**Issue by komirad** [laravel/echo#173]
I am using Laravel echo like so in my bootstrap.js

```
import Echo from 'laravel-echo';

window.Echo = new Echo({
    broadcaster: 'socket.io',
    host: 'http://localhost:3000',
});
```

I am using Laravel's inbuilt webpack to transpile my JS. And I am getting this on my console:
```
app.js:6604 Uncaught TypeError: io is not a function
    at SocketIoConnector.connect (app.js:6604)
    at SocketIoConnector.Connector (app.js:6172)
    at new SocketIoConnector (app.js:6594)
    at new Echo (app.js:6691)
    at Object../resources/assets/js/bootstrap.js (app.js:66564)
    at __webpack_require__ (app.js:679)
    at fn (app.js:89)
    at Object../resources/assets/js/app.js (app.js:66448)
    at __webpack_require__ (app.js:679)
    at fn (app.js:89)
```

I can't find in the documentation on how can I import io into Echo. Any ideas?

**Comment by kkomelin** [comment]
@komirad Please see https://github.com/laravel/docs/issues/3173 and https://komelin.com/articles/realtime-apps-laravel-echo-tips-and-tricks#laravel-echo-server-fails

**Comment by kkomelin** [comment]
@taylorotwell Could you please implement a check for the dependency on the Laravel Echo client level?

**Comment by AndrewMast** [comment]
(Just so the question is explicitly answered...)

`io` must be a function:
```
import Echo from 'laravel-echo';

window.io = require('socket.io-client');

window.Echo = new Echo({
    broadcaster: 'socket.io',
    host: 'http://localhost:3000',
});
```
*or* you must provide a `client`:
```
import Echo from 'laravel-echo';

window.Echo = new Echo({
    broadcaster: 'socket.io',
    client: require('socket.io-client'),
    host: 'http://localhost:3000',
});
```

**Comment by kkomelin** [comment]
@AndrewMast Thanks. From which version is it possible?

**Comment by AndrewMast** [comment]
@kkomelin I don't know which version, but it appears to have been added by @okaufmann on Jan 9 (https://github.com/laravel/echo/commit/cc09aa86524938ba652b4f9e97d950d00dadc95f)

**Comment by kkomelin** [comment]
@AndrewMast Thank you. It's worth knowing.

**Comment by connectkushal** [comment]
>@kkomelin Since version 1.3.3. The support was added by @okaufmann on Jan 9, 2018 (cc09aa8)

the package.json on the master branch still points to version 1.3.2. Is 1.3.3 tagged anywhere yet or am i missing something  ?

**Comment by AndrewMast** [comment]
@connectkushal Its the version on [NPM](https://www.npmjs.com/package/laravel-echo). It confuses me too.

**Comment by connectkushal** [comment]
@AndrewMast cool, thanks for the code snippet too
