### ISSUE TITLE
how to write socketid to header

### ISSUE THREAD

**Issue by archer-wong** [laravel/echo#176]
here is an example,  
```
setTimeout(function() { 
    Echo.connector.options.auth.headers['X-Socket-ID'] = Echo.socketId();
}, 2000);

setTimeout(function() { 
    var orderId = 1
    Echo.private('order.' + orderId)
        .listen('TestPrivateEvent', (e) => {
            console.log(e);
        });
}, 3000);
```

vendor/laravel/framework/src/Illuminate/Broadcasting/BroadcastController.php
```
public function authenticate(Request $request)
{   
    debug(json_encode($request->header()));
    return Broadcast::auth($request);
}
```
log information：
```
{
    "connection": [
        "close"
    ], 
    "content-length": [
        "28"
    ], 
    "content-type": [
        "application/x-www-form-urlencoded"
    ], 
    "host": [
        "xxxx.cn"
    ], 
    "x-requested-with": [
        "XMLHttpRequest"
    ], 
    "cookie": [
        ......
    ], 
    "x-socket-id": [
        "2lZruXuFAFDeK6tKAABB"
    ], 
    "x-csrf-token": [
        "eci68phBwGXOjHJVNXslx6l39S9WXshO2KGdMN2a"
    ]
}
```

**X-socket-id can be acquired by the backend.  but this is just an example of my test. What is the correct method?**

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs or problems. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
