### ISSUE TITLE
Support "pusher:subscription_error" event

### ISSUE THREAD

**Issue by tillkruss** [laravel/echo#177]
Support for `pusher:subscription_error` would be nice. It only applied to `private` and `presence` channels.

`pusher:subscription_succeeded` could be moved to basic pusher channel, because it's triggered for all channel types.

https://pusher.com/docs/client_api_guide/client_events#subscription_error

**Comment by driesvints** [comment]
How would this exactly work? Something like an `.error()` method? Can't you simply catch these errors in your code?

**Comment by charleswolfe** [comment]
I could see subscription errors coming back in firefoxes console. I wanted to be able to execute a function when the subscription failed. 

I prefer something like 'subscription_error', however 'error' would be fine if there was a type for 'subscription_error', so I handle that very specific case.

Also thanks for looking into this @driesvints , knowing that we didn't make the socket connection and being able to handle it allows us to write less code. For example: dealing with a user that logs in to an application simultaneously using multiple browsers.

**Comment by tillkruss** [comment]
@driesvints: I guess I'd like to handle errors in a callback and if there is no callback maybe rethrow the exception or just call `console.error()`.

```js
Echo.join(`chat.${roomId}`)
    .here(...)
    .joining(...)
    .leaving(...)
    .listen(...)
    .error(error => {
        //
    });
```

**Comment by driesvints** [comment]
Is there a way to do a type check on the error? Something like this:

```js
Echo.join(`chat.${roomId}`)
    .here(...)
    .joining(...)
    .leaving(...)
    .listen('NewMessage', ...)
    .error(err => {
        if (err.type === 'subscription') {
             // do whatever type related
        }
        
        // Sentry.captureException(err);
    });
```

Reason why I want to do it this way is to just provide a generic way of catching errors so people can do whatever they want.

**Comment by tillkruss** [comment]
That'd be great.

```js
Echo.join(`chat.${roomId}`)
    .here(...)
    .joining(...)
    .leaving(...)
    .listen('NewMessage', ...)
    .error((err, type) => {
        // type = subscription
        // err = Error object
    });
```

**Comment by driesvints** [comment]
Okay so I don't know when I'll have time to work on this but feel free to send in a PR if you get to it before me.

**Comment by driesvints** [comment]
Sent a PR for this here: https://github.com/laravel/echo/pull/284

@tillkruss would be great if you could give feedback on my notes on the private channel thing on the PR.

**Comment by tillkruss** [comment]
@driesvints: LGTM. Haven't tested it, I don't think we use that code anymore.
