### ISSUE TITLE
How to configure connection attempt counts?

### ISSUE THREAD

**Issue by MovingGifts** [laravel/echo#181]
Is there a way for reconnect attempts to be configured? Something like try to connect 2 times, then wait one minute before trying to reconnect 2 times again then wait one minute etc.. until a connection is established?

I feel like it keeps hitting the server too many times when the server is down and the console shows way to many reconnection attempts. Any ideas?

**Comment by driesvints** [comment]
There's currently no support for this. And I'm not really sure if this is wanted/needed. Perhaps try to discuss it with others first and then see if there's more interest in this.
