### ISSUE TITLE
React Native and laravel echo

### ISSUE THREAD

**Issue by Salmondx** [laravel/echo#182]
I've tried to setup a laravel-echo with socket.io client in React Native environment but without success.

```js
import Echo from 'laravel-echo';
import io from 'socket.io-client';

....

let echo = new Echo({
  broadcaster: 'socket.io',
  host: 'my.host.site',
  client: io,
  auth: {
    headers: {
      Authorization: this.props.token,
    }
  }
});

const userChannel = echo.private(`app.user.${this.props.user.id}`);

userChannel.listen('.balance.updated', function (e) {
  console.log('hello');
});
```

For some reason this doesn't work. Host URL is valid, token is valid.

Also if I provide a random string (e.g. `my.gasasdasdasdasda.com`) as a host parameter, socket.io doesn't throw any exceptions.

**Comment by Salmondx** [comment]
Fixed, the issue was that nginx on our dev server blocks all requests without a valid referer header.
Btw, `laravel-echo` doesn't throw any errors in RN environment and no logs about connection errors.

**Comment by chernandezq** [comment]
@Salmondx how you resolved this, I have the same problem

**Comment by rbgoncalves** [comment]
that's how I've setup it https://medium.com/@bldd97/react-native-laravel-echo-using-socket-io-29b9bc2df536
