### ISSUE TITLE
Catch server errors like Client can not be authenticated, got HTTP status 401

### ISSUE THREAD

**Issue by loic-lopez** [laravel/echo#183]
Hi,

I am using laravel-echo-server with laravel-echo, I would like to know if it is possible to catch server events like : 
```
Client can not be authenticated, got HTTP status 401
```

I need to reconnect the user in case of his token has expired.
Thanks for reply

**Comment by vesper8** [comment]
I am having the exact same issue.. some presence channels randomly and silently fail to authenticate and I need to make sure it will retry when that happens

**Comment by loic-lopez** [comment]
Please notify me if you know a solution @vesper8

**Comment by fannyfan414** [comment]
Same problem, any solutions?

**Comment by Ans0n-Ti0** [comment]
Have the same issue here, anyone has solved the problem?

**Comment by ndinhbang** [comment]
i had the same issue. i looked into the code and found that when fail to authenticate or authorized, laravel echo server emit **subscription_error** event
https://github.com/tlaverdure/laravel-echo-server/blob/b6838d8dc6fa053fa45dbdb5bb6d973bdbf15a23/src/channels/channel.ts#L107
`/**
     * Join private channel, emit data to presence channels.
     */
    joinPrivate(socket: any, data: any): void {
        this.private.authenticate(socket, data).then(res => {
            socket.join(data.channel);

            if (this.isPresence(data.channel)) {
                var member = res.channel_data;
                try {
                    member = JSON.parse(res.channel_data);
                } catch (e) { }

                this.presence.join(socket, data.channel, member);
            }

            this.onJoin(socket, data.channel);
        }, error => {
            if (this.options.devMode) {
                Log.error(error.reason);
            }

            this.io.sockets.to(socket.id)
                .emit('subscription_error', data.channel, error.status);
        });
    }`

then i listen on event to catch that error
`Echo.connector.socket.on( 'subscription_error', (channel, data) => {
                    console.log(channel, data);
                } );`

**Comment by driesvints** [comment]
Seems like this is a laravel-echo-server specific request which can best be documented on the docs for laravel-echo-server.
