### ISSUE TITLE
Problem with left channel (unsubscribed) after reconnection on private / presence channel

### ISSUE THREAD

**Issue by lrembacz** [laravel/echo#185]
Hi,
Ive noticed that when there is server killed and reconnection is done again and my Echo is listening on privateChannel (the same issue Ive notice for presenceChannel) there is connection automatically restored, but after that socket is losing connection right after with unsubscribed message:
joined channel: private-_users.1
left channel: private-_users.1 (unsubscribed)

My code is like that:

```
    mounted() {
        window.Echo.connector.socket.on('connect', () => {
            window.Echo.private(`users.${this.userId}`).listen('.Event', (e) => {
                console.log('Event')
            })
```

Is there a way to manually get the channel and make subscription?

And how actually can we know if socket is connected and is listening on events?

Note:
My problem is showing up when I have more than one user connected to the same channel. I have users with id 1 connected to this one room and its made to synchronize those clients in real time, so I need to be sure if clients are connected properly to prevent some data discrepancy.

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
