### ISSUE TITLE
fsevents on Linux or Windows

### ISSUE THREAD

**Issue by jmarcher** [laravel/echo#19]
I got this error trying to install laravel-echo

```
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
```

[Add fsevents to NodeJS #7858](https://github.com/nodejs/node/issues/7858)
It seems to be a problem with NodeJS however it may be removed from optional dependencies so that Linux users can workaround this error

**Comment by morloderex** [comment]
@jmarcher It's not really an error. It's an optional package for performance on `OSX` so you can just ignore these errors.

**Comment by jmarcher** [comment]
@morloderex the problem is that it stops the installation on Linux

**Comment by morloderex** [comment]
@jmarcher But i don't really see where it's been pulled in either because it's not in the devdepentenices in this project.

**Comment by jmarcher** [comment]
After playing around for a while, it seems to be a npm3 bug, I just downgraded to npm2 and it works fine, it could be considered as a tip in the documentation.

**Comment by morloderex** [comment]
Ping @taylorotwell

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
