### ISSUE TITLE
How do I use this package in my Ionic 3 app?

### ISSUE THREAD

**Issue by crushcafeteria** [laravel/echo#190]
Hello there,
I am trying to create a chat application with Laravel Echo. I really want to use Echo because it is a very sane way to manage the socket side of things. However, I have been cracking this issue for 3 consecutive days with no success and it is driving me crazy.

I have imported the package into my page like this
```ts
import Echo from "laravel-echo-ionic"
```
Now my question is, how do I use this package to listen for events in a channel from Laravel backend?
I have tried using it like this and it does not work:-
```ts
let echo = new Echo({
    broadcaster: 'pusher',
    key: 'your-pusher-key',
    cluster: 'eu',
    encrypted: true
});
```
The I also tried this:-
```ts
constructor(public echo: Echo) {
        this.echo.connector(new Echo({
            broadcaster: 'socket.io',
            host: settings.socket_url
        }));

        echo.channel('private-conversation-' + this.conversation.id).listen('new-message', (data) => {
            console.log(data);
        });
}
```
This does not work either. 

Can someone please post documentation on how to use this package in an Ionic 3 application? Or better yet, a link to a working app that i can use to donate parts to mine. 
Thanks in advance.
- Nelson A.

**Comment by sebastianro92** [comment]
me too... pls help! how implement in ionic 3...

**Comment by d3l3rium1986** [comment]
I got it working in ionic 2 a while back. I can create a ionic 3 project and test it out and share the repo. Will take a few days as im a bit backed up with work.
