### ISSUE TITLE
Whisper question

### ISSUE THREAD

**Issue by MatthewAugier** [laravel/echo#193]
....whisper('status', {userId: id, status: 'idle'});

When I send a whisper all other clients get it perfect and I can process as required.

However this is not a persistent state on laravel echo/stored in Redis... so when I refresh the page these messages from other clients are lost. Is there a way to persist this data via JS rather than an Ajax request to laravel to broadcast the state change? Seems a bit ham fisted?

**Comment by MatthewAugier** [comment]
Actually looks like https://github.com/tlaverdure/laravel-echo-server/pull/279 would work?

**Comment by driesvints** [comment]
Afaik these messages aren't meant to be persisted. It's totally up to you to persist state as you see fit (browser storage, Redux, etc).
