### ISSUE TITLE
Provide callback for the new Echo instance (or better yet return a Promise)

### ISSUE THREAD

**Issue by rohan-deshpande** [laravel/echo#195]
Getting the socket id for non vue / axios apps kind of sucks if you don't want to put the echo instance on the window object. You can only get it once you've connected to the socket and echo provides no native functionality (as far as I am aware) to do this reliably.

I had to do this

```
  echo.connector.pusher.connection.bind('connected', () => {
    console.log(echo.socketId());
  });
```

Which I learned about from this [stackoverflow post](https://stackoverflow.com/questions/46360427/laravel-echo-callback) and the [Pusher docs](https://pusher.com/docs/server_api_guide/server_excluding_recipients). 

Not ideal. It would be nice if you could just go 

```javascript
let socketId = null;
const echo = new Echo(options).then(echo => {
  socketId = echo.socketId();
});
```
Even a callback would be enough.

**Comment by driesvints** [comment]
I'll mark this as a feature request. Unfortunately my JS knowledge is too limited to implement this myself. I believe that if you'd want to refactor the library to be more into standards with modern JS approaches and more adaptable/usable that we'd be open for PRs. But it would have been well thought out and preferable discussed in length beforehand.

**Comment by tlaverdure** [comment]
It's not a common practice to create a promise from a constructor. I've added a change in https://github.com/laravel/echo/pull/210 to move the connection logic to it's own method. If that is merged, I can work on creating a connection event handler from the connectors. 

Then we can either add a callback in the `options` object:

```js
new Echo({
  ...
 onConnect: () => {...}
  ...
})
```

 Or remove the `connect()` method from the constructor and require the developer to connect at will.

```js
const echo = new Echo(...);

echo.connect().then(() => {
  // connected
});
```

@driesvints which would work better?

**Comment by rohan-deshpande** [comment]
I personally like the second far better than the first.

**Comment by driesvints** [comment]
@tlaverdure I'm afraid my JS knowledge is too limited to know what the best approach would be. It's best to ask other users of the library what they'd like.

**Comment by hailwood** [comment]
@tlaverdure I also prefer requiring the developer to connect manually.
The callback approach limits us to only having one possible handler, the promise approach means the following (although a silly example...) would work.

```
const echo = new Echo(...);

// Connects, then resolves the promise
echo.connect().then(() => console.log('Connected once...'));

// Already connected, simply returns the resolved promise
echo.connect().then(() => console.log('Connected twice...'));

// Already connected, simply returns the resolved promise
echo.connect().then(() => console.log('Connected three times...'));
```

**Comment by driesvints** [comment]
Hey all. I've been looking into this and while I agree this seems like a good thing to have in the library we're not going to work on this ourselves at the moment. We're however open to prs if anyone wants to take a stab at this themselves! Thanks.
