### ISSUE TITLE
Auth failures return status code 500 instead of 401

### ISSUE THREAD

**Issue by genyded** [laravel/echo#196]
If there are any auth errors (typically from the Echo authEndpoint), a status 500 is returned instead of status 401. This is problematic in that client side handling between those 2 status codes is completely different. A 401 is either typically handled by refreshing a token or redirecting to login. A 500 is typically a fatal cannot continue situation, which is not the case here. This is a MAJOR issue.

We are seeing this and here are a couple of other examples:
[500 error](https://laracasts.com/discuss/channels/laravel/passport-auth-error-500-with-laravel-echo-server)
[Another 500](https://laracasts.com/discuss/channels/javascript/laravel-echo-with-pusher-couldnt-get-auth-info-from-your-webapp-500)

**Comment by driesvints** [comment]
Seems to me this is more of an issue with your server than with Echo. Echo can't control what status code is returned.
