### ISSUE TITLE
Having the same user multiple times on a Presence Channel

### ISSUE THREAD

**Issue by Pymous** [laravel/echo#198]
Hello !

I have a bit of an edge case on my hand ; I'm using Laravel Echo for a WebRTC application.

Everything is working fine, every users can join a Presence Channel and do stuff on it. But in some rare case, I need to have the same user join the channel twice (for example, one session on a PC, and another one on a smartphone).

For now, Laravel Echo just "ignore" the second session, and I can't get any events on the second session.

Is there a way to "disable" this feature ? Or handle it properly in my case ?

Thanks for the work !

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs or problems. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
