### ISSUE TITLE
Echo won´t initiate Pusher

### ISSUE THREAD

**Issue by fwartner** [laravel/echo#20]
Getting ```uncaught exception: You must pass your app key when you instantiate Pusher.```when installing Echo according to the docs.
But i provided my key correctly.. =/

**Comment by mattmcdonald-uk** [comment]
What are you using to initiate Echo?

**Comment by fwartner** [comment]
What do you mean? Which driver i´using? Pusher.

**Comment by morloderex** [comment]
@fwartner: are you sure you have set you pusher key correctly? because the option has recently been changed from `pusherKey` to just beeing `key`.

**Comment by mattmcdonald-uk** [comment]
@fwartner I mean what is the Javascript code you are using when you start a new Echo instance, e.g.
`window.Echo = new Echo({
    broadcaster: 'pusher',
    key: 'your-pusher-key'
});`

**Comment by fwartner** [comment]
Yep. According to the Laravel Docs at master. Getting an error now.. Something with socketId.. =/

**Comment by fwartner** [comment]
```js
import Echo from "laravel-echo"

window.Echo = new Echo({
    broadcaster: 'pusher',
    key: 'MY-KEY',
    encrypted: true
});
```

**Comment by oyed** [comment]
Your original error was caused by the docs saying to use `key`, but Echo expecting you to use `pusherKey`, which Taylor fixed in https://github.com/laravel/echo/commit/bdc7d4792a4eef1ea1376b15683255427ea19aa7 (5 hours after this issue)

Regarding your new error - can you give us the whole error from the console?

**Comment by fwartner** [comment]
I am using Vue for my whole application.. But it´s fixed now. Thanks anyways :)
