### ISSUE TITLE
PUSHER channel events listen callback did not work

### ISSUE THREAD

**Issue by teamen** [laravel/echo#200]
I have use the below code to listen a channel event, it can subscribe success but callback no effects.

![image](https://user-images.githubusercontent.com/13899144/44902366-680b1580-ad3c-11e8-8c85-53e7c9e56518.png)

However, I use the raw lib
```
Echo.connector.pusher.channel('chatroom').bind('.message.sent', function(data){console.log(data);})
```

to listen the event , the callback triggered successfully.

The browser console feedback:
![image](https://user-images.githubusercontent.com/13899144/44902487-b8827300-ad3c-11e8-9666-1004aab2b5f1.png)

Although， I had saw the issue #55 and tried  but did not work,   are there anybody come across the similar problem ?

**Comment by teamen** [comment]
my dependencies is:
```
        "laravel-echo": "^1.4.0",
        "pusher-js": "^4.3.0",
```

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.

**Comment by tirta-keniten** [comment]
This happens to me too. The listen callback not fire by Echo.
