### ISSUE TITLE
Echo.leave() leaves both public & private.

### ISSUE THREAD

**Issue by Livijn** [laravel/echo#202]
I am using the *same* name for both my private and public channels. This makes it impossible to just leave the public channel

    // Subscribe to private
    Echo.private('user.1')
        .listen(...)

    // Subscribe to private
    Echo.channel('user.1')
        .listen(...)

    // Leaves both public & private
    Echo.leave('user.1'); 

I would suggest adding an optional *boolean* to the `leave()`-method which passes it down to the connector in socketio-connector.ts:

    // added leaveOnlyPublic
    leave(name: string, leaveOnlyPublic: bool): void {
        // OLD: let channels = [name, 'private-' + name, 'presence-' + name];
        let channels = leaveOnlyPublic ? [name] : [name, 'private-' + name, 'presence-' + name];

        channels.forEach(name => {
            if (this.channels[name]) {
                this.channels[name].unsubscribe();

                delete this.channels[name];
            }
        });
    }

**Comment by driesvints** [comment]
It's best to just use separate channels for this.

**Comment by Livijn** [comment]
Well, they **are** separate channels, hence the issue. `Echo.private()` creates a channel with the `private-` prefix, meaning the channel names do differ. This is not a crucial issue though.

**Comment by driesvints** [comment]
Ah I see what you mean. I'll try to have a look at this at a later time. Thanks for reporting!

**Comment by driesvints** [comment]
In an ideal situation I'd make the `leave` channel only leave the specified channel name and add a `leaveAll` method which would adopt the behavior of the current method. Since this would be a breaking change I believe a new `leaveOne` method could provide the functionality that you need. I'll send in a PR.
