### ISSUE TITLE
Can't get notifications/Events etc. on client side. Bug with queues

### ISSUE THREAD

**Issue by rSammy** [laravel/echo#203]
Hello,

Before I was able to get some notifications and events when they were fired from server and got them on client side using some system of chatting and making use of DatabaseNotifications and BroadcastNotifications for some cases.

Now, I can't get any of these since the queue doesn't work as expected.
I can only fire some mail notifications, the broadcast notification is not fired and events don't work at all.

I looked up in console, I saw that the events were not being fired. So I checked redis cli.

That's what I've 
```
1537374236.096152 [0 lua] "zrangebyscore" "queues:forecasts:delayed" "-inf" "1537374236"
1537374236.096290 [0 127.0.0.1:61571] "EVAL" "-- Get all of the jobs with an expired \"score\"...\nlocal val = redis.call('zrangebyscore', KEYS[1], '-inf', ARGV[1])\n\n-- If we have values in the array, we will remove them from the first queue\n-- and add them onto the destination queue in chunks of 100, which moves\n-- all of the appropriate jobs onto the destination queue very safely.\nif(next(val) ~= nil) then\n    redis.call('zremrangebyrank', KEYS[1], 0, #val - 1)\n\n    for i = 1, #val, 100 do\n        redis.call('rpush', KEYS[2], unpack(val, i, math.min(i+99, #val)))\n    end\nend\n\nreturn val" "2" "queues:forecasts:reserved" "queues:forecasts" "1537374236"
1537374236.096400 [0 lua] "zrangebyscore" "queues:forecasts:reserved" "-inf" "1537374236"
1537374236.096540 [0 127.0.0.1:61571] "EVAL" "-- Pop the first job off of the queue...\nlocal job = redis.call('lpop', KEYS[1])\nlocal reserved = false\n\nif(job ~= false) then\n    -- Increment the attempt count and place job on the reserved queue...\n    reserved = cjson.decode(job)\n    reserved['attempts'] = reserved['attempts'] + 1\n    reserved = cjson.encode(reserved)\n    redis.call('zadd', KEYS[2], ARGV[1], reserved)\nend\n\nreturn {job, reserved}" "2" "queues:forecasts" "queues:forecasts:reserved" "1537374326"
```

I tried everything, like Cache::flush(), removing cache files in storage.

Whenever I start the worker, these errors don't stop to show up. When I stop the worker, the error stops.

What the heck is going on ? 

Please tell me where do I have to go to empty cache or whatever and get my broadcast channels to works. 😢

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.

**Comment by jiteshdhamaniya** [comment]
I am having same problem, whats the solution ?

**Comment by rSammy** [comment]
Make sure redis server is working without issue if using socket io
Check laravel logs
Make sure you didn't start the worker beforehand if you are using queues
Check connectivity and password
