### ISSUE TITLE
Echo continue connecting and disconnecting  in react native.

### ISSUE THREAD

**Issue by vipin733** [laravel/echo#205]
I'm using  
"laravel-echo": "^1.4.0",
"socket.io-client": "^2.1.1"
laravel-echo-server

I'm trying to implement laravel echo in my react native app but its working in my vue web app,
every time its connect and  disconnect

here is my entry 

app.js file 

```
async _connection() {
window.io = require('socket.io-client')
     var token  = await Expo.SecureStore.getItemAsync('token')

      window.Echo = new Echo({
         broadcaster: 'socket.io',
          host:  SOCKET_SERVER,
         auth: {
         headers: {
               Authorization: `Bearer ${token}`
         }
       }
       }) 
}
```
![screen](https://user-images.githubusercontent.com/10106412/46212466-a869ad80-c353-11e8-841c-7a8cb83a8f4f.PNG)

**Comment by driesvints** [comment]
Can you first please try one of the following support channels? If you can actually identify this as a bug, feel free to report back.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
