### ISSUE TITLE
How to reconnect after message "server error", got HTTP status 500

### ISSUE THREAD

**Issue by fannyfan414** [laravel/echo#206]
Sometimes 1 of 10-20 attempts to connect to private/presence failed for no reason with error:
`⚠ [10:59:56] - -mn5EKQT9zQoxCjmAAAZ could not be authenticated to presence-offer.17
{
    "message": "Server Error"
}
Client can not be authenticated, got HTTP status 500`
How can i catch this error and try to reconnect user?

**Comment by driesvints** [comment]
Can you first please try one of the following support channels? If you can actually identify this as a bug, feel free to report back.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
