### ISSUE TITLE
I cannot work with Laravel echo

### ISSUE THREAD

**Issue by adelsedighi** [laravel/echo#209]
It is quiet some time that I have installed laravel echo server 3rd version and node dependencies, I have read all related docs, but I still could not use this feature? as client broadcaster! please someone help me to figure this out

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs or problems. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
