### ISSUE TITLE
SyntaxError: Unexpected token export (1.5.0)

### ISSUE THREAD

**Issue by udanpe** [laravel/echo#211]

**Comment by driesvints** [comment]
Please open a new issue with enough info instead of just posting an empty issue.

**Comment by udanpe** [comment]
@driesvints This error don't need description. And you know about this bug. But how say @tlaverdure if you don't use module as intended (with mix and pusher) your are not a people and must clone repository for self. React create app, react native, cordova,  nextjs, nuxtjs and other all must suffer. This is not serious.

**Comment by driesvints** [comment]
@udanpe I have no idea how this bug could be reproduced. What steps do you take?

**Comment by udanpe** [comment]
@driesvints https://github.com/laravel/echo/pull/210 I use next.js with other modules. I think 100-150 and all this modules convert es6 to commonjs. You can show me just one public module who dont do this?

**Comment by driesvints** [comment]
You're still not posting any steps. Please share your code where this is breaking things and post steps you take how you install the package.

**Comment by udanpe** [comment]
@driesvints it's not my fault) just convert es6 to commonjs. Last node lts 10.14 don't support es6 import export

**Comment by udanpe** [comment]
@driesvints 
module.exports = Echo // support
export default Echo // don't support

**Comment by udanpe** [comment]
@driesvints But if you want step by step, ok. Install next.js https://github.com/zeit/next.js/ or another frontend framework import Echo run in dev mode and you can see this error. Commonjs it's standard.

**Comment by driesvints** [comment]
@udanpe we can't accommodate for every framework out there. It's either the current version or another one. 

Anyway, my knowledge about JS is too limited to provide a proper answer for this. Maybe @tlaverdure who sent in the PR could answer this better.

**Comment by samuelterra22** [comment]
I am using Nuxt.js and received the same error after upgrading to version 1.5.0

![image](https://user-images.githubusercontent.com/11915449/49382315-46377b00-f6fd-11e8-8a9c-8eeed169aa7b.png)

**Comment by udanpe** [comment]
@driesvints maybe you have @tlaverdure contacts? It is very and very not professional. @taylorotwell what your thing about this?

**Comment by udanpe** [comment]
@driesvints maybe you have @tlaverdure contacts? It is very and very not professional. @taylorotwell what you think about this?

**Comment by udanpe** [comment]
If your really want use es6 you must create other file echo.common.js for other people

**Comment by tlaverdure** [comment]
Sure, I'll send a PR to also package a echo.common.js file. No need to @ me so many times...
