### ISSUE TITLE
Echo.channel().initial() callback

### ISSUE THREAD

**Issue by autaut03** [laravel/echo#215]
Hey there. I'm currently using my own broadcasting driver for Laravel which utilitizes SocketCluster as a websocket server. I'm thinking of switching to Laravel Websockets package on the backend and Echo on the front, but I'm missing one thing from my own implementation: initial events. Basically, in my laravel's broadcast routes I return an array of events (just normal instances of broadcast events, same that would go to broadcast()), which is then returned to the client right after it successfully subscribes to a given channel.

Example: 
```php
Broadcast::channel('chats.{room}', function ($user, $room) {
    return [ new ChatRoomInitialEvent($room) ];
});
```

I need this kind of solution as it is a simple and effective way to guarantee that the client will not get duplicated entities or wrong order of them.

Created this issue to ask whether this kind of thing is suitable for Laravel/Echo or not. If it is, I will be happy to contribute. Thanks regardless.

Oh, and forgot to mention: yes, I understand that this would also require changes to laravel/framework, but that's like 10 lines of code changed.

**Comment by driesvints** [comment]
I'm not really sure what it is that you're asking. Can you perhaps describe in detail how this would work? Preferable with a practical example. What changes exactly are needed and where?

**Comment by autaut03** [comment]
As I was writing this I realized that such change wouldn't be compatible with Pusher API, which was my original goal, while writing a simple alias isn't really a solution and would bring a lot of problems with maintenance.

Please, close this issue. Sorry for taking your time, have a good day :)

**Comment by driesvints** [comment]
No problem
