### ISSUE TITLE
Provide a way to check for unauthorized connection

### ISSUE THREAD

**Issue by ryanrapini** [laravel/echo#218]
Sorry if I'm missing something, but I can't find a way to check if authorization failed.

```
window.Echo.private('channel')
.listen('SampleEvent', (e) => {
    alert("Worked");
})

window.Echo.connector.socket.on('connect', function(){
    console.log("Connected", echo.socketId());
});
```

The above code will log to console when I connect to a private channel. But I want to alert the user if the private channel is unauthorized:
```
Client can not be authenticated, got HTTP status 500
[10:41:39] - Sending auth request to: http://example.test/broadcasting/auth

⚠ [10:41:40] - token_CJ4tokenAAAI could not be authenticated to private-channel
```

Any idea how I would do this with jQuery? I dug through the source and through the documentation but couldn't come up with a solution.

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
