### ISSUE TITLE
Echo with NodeJS HTTPS doesn't work

### ISSUE THREAD

**Issue by joaopmarques66** [laravel/echo#219]
Hi there, I've been developing this NodeJS application that takes advantage of Laravel Echo's functionalities to receive information from a server through socket connection.

**Server-side**
- Laravel Echo Server with Laravel 5.7.19

**Client-side**
 "laravel-echo": "^1.5.2"
  "socket.io": "^2.2.0"

```js
import Echo from '../../node_modules/laravel-echo/dist/echo.common.js'
import Socketio from 'socket.io-client';

let echo = new Echo({ 

      broadcaster: 'socket.io',
      host: 'https://smartfish.danymota.com:8080/',
      encrypted: true,
      secure: true,
      client: Socketio,
      auth: {
        headers: {
          'Authorization': 'Bearer ' + this.token.bearerToken,
        },
      },
    });
    echo.private('central.' + macAddress)
      .listen('RulesUpdated', (response) => {
        handleRules(JSON.parse(response.aquarios))
        console.log(new Date().toLocaleString() + " - Rules updated")
      })
```

**Problem**
Everything works fine in Http, when I switch to HTTPS it just stops working.
Also, if I run the application in a browser, **everything works fine**. Thats why I tried to play around with a bunch of factors such as the URL (/socket.io, wss, etc), the options passed on initialization, etc. All in vain. 

**Socket.io debug**
 socket.io-client:url parse https://smartfish.danymota.com:8080/socket.io +0ms
  socket.io-client new io instance for https://smartfish.danymota.com:8080/socket.io +0ms
  socket.io-client:manager readyState closed +0ms
  socket.io-client:manager opening https://smartfish.danymota.com:8080/socket.io +0ms
  socket.io-client:manager connect attempt will timeout after 20000 +4ms
  socket.io-client:manager readyState opening +1ms
  socket.io-client:manager connect_error +60ms
  socket.io-client:manager cleanup +0ms

Thank you all in advance.

**Comment by driesvints** [comment]
Can you first please try one of the following support channels? If you can actually identify this as a bug, feel free to report back.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)

**Comment by joaopmarques66** [comment]
Thanks for the aswer.
Posting this here, so that people can follow up on the issue.
[https://stackoverflow.com/questions/54091123/laravel-echo-with-nodejs-https-doesnt-work]

**Comment by joaopmarques66** [comment]
I've solved the problem by adding `rejectUnauthorized: false` to echo 

`this.echo = new Echo({
      broadcaster: 'socket.io',
      host: config.ECHO_SERVER,
      client: Socketio,
      rejectUnauthorized: false,
      auth: {
      headers: {
      'Authorization': 'Bearer ' + this.token.bearerToken,
    },
  },
})
`
