### ISSUE TITLE
[Request] Use Vue.use(Echo) to bind Laravel Echo with Vue

### ISSUE THREAD

**Issue by petervmeijgaard** [laravel/echo#22]
It would be nice if I could do something like this:

``` JavaScript
import Vue from 'vue';
import Echo from 'laravel-echo';

Vue.use(Echo);

export const echo = new Echo({
  broadcaster: 'pusher',
  key: 'SomeRandomKey',
});
```

Instead of having to bind Vue to the `window`
https://github.com/laravel/echo/blob/master/src/echo.ts#L32

**Comment by PetervMeijgaard** [comment]
I think the syntax would be something like this:
https://github.com/PetervMeijgaard/echo/blob/master/src/echo.ts#L44

**Comment by happyDemon** [comment]
@petervmeijgaard would [Vue-Echo](https://github.com/happyDemon/vue-echo) be what you're looking for?

**Comment by petervmeijgaard** [comment]
Awesome! This didn't exist when I created this issue! Thanks @happyDemon 😄
