### ISSUE TITLE
Jquery dependency problem

### ISSUE THREAD

**Issue by edwardfhsiao** [laravel/echo#220]
On the npm website, it shows 0 dependencies. However,
```import Echo from 'laravel-echo';``` gives this error
```Can't resolve 'jquery' in '/Users/username/node_modules/_laravel-echo@1.5.2@laravel-echo/dist'```.

We are not using jquery. Is it possible to remove this dependency?

**Comment by driesvints** [comment]
Can you post the exact steps to recreate this issue? Can you post the code which recreates the issue?

**Comment by edwardfhsiao** [comment]
im using webpack. once i import it, the error occurred. After I install the jquery, error gone

**Comment by driesvints** [comment]
Please provide some code.

**Comment by edwardfhsiao** [comment]
I will create a repo for you tomorrow

**Comment by edwardfhsiao** [comment]
Hi @driesvints , I found the problem. In webpack I did this
```js
    new webpack.ProvidePlugin({
      React: 'React',
      react: 'React',
      'window.react': 'React',
      'window.React': 'React',
      $: 'jquery',
      jQuery: 'jquery', // comment out this line, problem solved.
      'window.jQuery': 'jquery',
    }),
```

The repo is https://github.com/edwardfhsiao/laravel-echo-test
after git clone just run ```npm i ``` and ```npm run server```

I wonder why this happens. Thanks in advance.

**Comment by driesvints** [comment]
No idea. This is more of a question for a forum or something I'm afraid.

**Comment by edwardfhsiao** [comment]
@driesvints Thank you.
