### ISSUE TITLE
import Echo from "laravel-echo":   throw exception !!!

### ISSUE THREAD

**Issue by marol1210** [laravel/echo#221]
somebady can help me？  thanks  a lot.

OS: linux
nodejs version : v11.6.0

<img width="408" alt="_20190111145157" src="https://user-images.githubusercontent.com/7519301/51017856-80bfed80-15b0-11e9-95c2-27777cb5e992.png">

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
