### ISSUE TITLE
Echo.leaveChannel() undefined

### ISSUE THREAD

**Issue by RicardoRamirezR** [laravel/echo#223]
When I try to access `Echo.leaveChannel`, I get an error saying:
`Uncaught TypeError: Echo.leaveChannel is not a function`. 

Seeing the main class I can't find that function as the docs are referring to.

**Comment by driesvints** [comment]
Which echo version are you using? Which Laravel version are you using? Please provide more code which re-creates this problem.

**Comment by RicardoRamirezR** [comment]
Laravel: 5.7.25
Laravel-echo: 1.5.2

![captura de pantalla 2019-02-11 a la s 9 06 45 a m](https://user-images.githubusercontent.com/6526545/52568340-788be580-2ddc-11e9-87da-1c600b96ce2c.png)
![captura de pantalla 2019-02-11 a la s 9 07 01 a m](https://user-images.githubusercontent.com/6526545/52568342-79bd1280-2ddc-11e9-8d99-8c9f6e90de03.png)

Changing from leaveChannel to leave works well; but leaves all channels.

**Comment by driesvints** [comment]
Which driver are you using?

**Comment by driesvints** [comment]
Can you show some more code? Perhaps the part where Echo and the driver is set up?

**Comment by RicardoRamirezR** [comment]
```javascript
import Echo from "laravel-echo"

window.Pusher = require('pusher-js');

window.Echo = new Echo({
    broadcaster: 'pusher',
    key: 'MIB0dYszhpG6rXLN28B5MJhhtY4wWSynmAGqUMA2',
    encrypted: false,
    namespace: 'Noah.Events',

    wsHost: window.location.hostname,
    wsPort: 6001,
    disableStats: true,
    enabledTransports: ['ws', 'wss'],
});
```

**Comment by driesvints** [comment]
I'm pretty much in the dark here what's going on. It should definitely work. Have you tried removing your node_modules directory and `package-lock.json` (or `yarn.lock`) and installed the dependencies again with their latest versions?

**Comment by RicardoRamirezR** [comment]
Done! Same problem.

I did a `laravel new echo-test` then install the necessary packages.

In the Chrome Dev Tools, I typed:

![captura de pantalla 2019-02-14 a la s 9 23 28 a m](https://user-images.githubusercontent.com/6526545/52792932-8e96e180-303a-11e9-8a37-71c5d81c231f.png)

**Comment by driesvints** [comment]
I've found the issue and we released a new patch version with the fix: https://github.com/laravel/echo/commit/fd3b65b5be2950e550e1e18a8d29451bdd66ce7f
