### ISSUE TITLE
Laravel Private Channel Not Authorizing : Error 404

### ISSUE THREAD

**Issue by WhyIExist** [laravel/echo#224]
I asked this on stack too, but I never got any reply..
1

I am trying to build a real-time notification system. I used Laravel-Notifications and laravel-echo-server. when I listen for notification using start command in terminal laravel-echo-server start then error occured in private channel:

Client can not be authenticated, got HTTP status 404 ⚠ [6:57:15 PM] - qXY1YTBcnGUzqJvfAAAB could not be authenticated to private-App.User.2

Client can not be authenticated, got HTTP status 404

CODE

channels.php

```
Broadcast::channel('App.User.{id}', function ($user, $id) {
 return (int) $user->user_id === (int) $id;
});
```
Notification

```
class StickBoardLiked extends Notification
{
use Queueable;

protected $boardid;


/**
 * Create a new notification instance.
 *
 * @return void
 */
public function __construct($boardid)
{
    $this->boardid = $boardid;
}

/**
 * Get the notification's delivery channels.
 *
 * @param  mixed  $notifiable
 * @return array
 */
public function via($notifiable)
{
    return ['database', 'broadcast'];
}

/**
 * Get the mail representation of the notification.
 *
 * @param  mixed  $notifiable
 * @return \Illuminate\Notifications\Messages\MailMessage
 */
public function toMail($notifiable)
{
    return (new MailMessage)
                ->line('The introduction to the notification.')
                ->action('Notification Action', url('/'))
                ->line('Thank you for using our application!');
}

/**
 * Get the array representation of the notification.
 *
 * @param  mixed  $notifiable
 * @return array
 */
public function toArray($notifiable)
{
    return [
        //
        'liked_by' => Auth::user()->user_id,
        'username' => Auth::user()->user_name,
        'board_id' => $this->boardid,
        'content_type' => 'like',

    ];
}
}
```
front-end script to listen for notification

```
Echo.private("App.User." + this.user.user_id).notification(notification 
=> {
  this.unreadNotifications.push(notification);
});
```

In config/app.php , this is uncommented,

App\Providers\BroadcastServiceProvider::class,

Please help out!!

**Comment by sog01** [comment]
You should use auth::api as a middleware on BroadcastServiceProvider

`class BroadcastServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {        
        Broadcast::routes(['middleware' => ['auth:api']]);

        require base_path('routes/channels.php');
    }
}
`

Then, you have to send `api token` for authorization in your request header.

**Comment by driesvints** [comment]
Please try @sog01's suggestion from above or one another support channel first. If you can actually identify this as a bug, feel free to report back.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)

**Comment by WhyIExist** [comment]
Thankyou guys for help, I had just found the problem few hours ago.. It wasn't going to correct path 
It was going to:   http://localhost/
Should have: htto://localhost:8000/

**Comment by marafee1243** [comment]
> You should use `auth::api` as a middleware on `BroadcastServiceProvider`
> 
> ```
> class BroadcastServiceProvider extends ServiceProvider
> {
>     /**
>      * Bootstrap any application services.
>      *
>      * @return void
>      */
>     public function boot()
>     {        
>         Broadcast::routes(['middleware' => ['auth:api']]);
> 
>         require base_path('routes/channels.php');
>     }
> }
> ```
> 
> Then, you have to send `api token` for authorization in your request header.

This worked for me. As I am using Passport APIs for authentication.
