### ISSUE TITLE
Vue jest fails when integrated with vue-google-oauth2

### ISSUE THREAD

**Issue by rahulswimmer** [laravel/echo#227]
- Node Version: 10.0.0
- Vue: 3.5.1
### Description:
I am using [vue-google-oauth2](https://github.com/guruahn/vue-google-oauth2#readme) for integrating Google login in my vue project, which also has vuetify as a plugin and jest as the unit testing framework.
 
I followed all the steps mentioned in [vue-google-oauth2](https://github.com/guruahn/vue-google-oauth2#readme) and got my google login to work.

Now the import statement and Vue.use(Gauth), are all done in main.js

Now on click of a button, I run the Google login and fetch the id_token from google.

So I import the same in login.spec.js file to check if value of id_token was empty before the button was and clicked and was not null after clicking the button.

But 'npm run test' throws an error pointing finger at the import statement of GAuth

## Steps To Reproduce:
Following are the files:

      **main.js**

      import GAuth from 'vue-google-oauth2'
      const gauthOption = {
         clientId:
         'xyz',
         scope: 'profile email',
         prompt: 'select_account'
       }

       Vue.use(GAuth, gauthOption)

    **login.vue:**

     <div class="login">
        <v-container fluid fill-height>
           <v-layout row wrap>
              <v-flex xs12 justify-center class="login-button-wrapper">
                <v-btn
                  block
                   class="login-button"
                   color="primary"
                   @click="googleLogin"
                   name="login-button-name"
                    >Login</v-btn>
                </v-flex>
             </v-layout>
          </v-container>
       </div>

     export default {
        name: 'Login',
        data() {
          return {
             accessToken: ''
           }
         },
         methods: {
            googleLogin() {
               console.log(this.accessToken)
               this.$gAuth.signIn().then(GoogleUser => {
               this.accessToken = GoogleUser.Zi.id_token
            })
          }
       }

     **login.spec.js:**

     import { mount } from '@vue/test-utils'
     import Login from '@/components/Login'
     import Vue from 'vue'
     import Vuetify from 'vuetify'
     import VueRouter from 'vue-router'
     import { GAuth } from 'vue-google-oauth2'

     const gauthOption = {
         clientId: 'xyz',
         scope: 'profile email',
         prompt: 'select_account'
      }

    describe('Login', () => {
      Vue.use(Vuetify)
      Vue.use(VueRouter)
      Vue.use(GAuth, gauthOption)

    const wrapper = mount(Login)

        it('fetches empty access token', () => {
            expect(wrapper.vm.accessToken).toBe('')
            wrapper.find('.login-button').trigger('click')
            expect(wrapper.vm.accessToken).not.toBe('')
         })
     })`

Now here the assertion that checks if accessToken is empty or not, works, but after that ,to implement a click, vue-jest has to implement this.$gauth.signIn(...).

Here is where things break.

I get an error:

● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config
       option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    **export default installGoogleAuthPlugin
    ^^^^^^

    SyntaxError: Unexpected token export

      4 | import Vuetify from 'vuetify'
      5 | import VueRouter from 'vue-router'
    > 6 | import { GAuth } from 'vue-google-oauth2'
        | ^**

Please educate me as to how do I rectify this!

**Comment by driesvints** [comment]
Heya,

Unfortunately we don't provide support for vue-google-oauth2. Please try asking this on a support channel: 

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
