### ISSUE TITLE
Any tips on a redundant setup?

### ISSUE THREAD

**Issue by kramer65** [laravel/echo#228]
We've just integrated laravel-echo into our product and we now need to deploy to our production machines. We've got a high availability setup with two application servers behind one load balancer. 

Is there any documentation on setting up Laravel Echo in a redundant setup?

**Comment by francislavoie** [comment]
This isn't a question for Echo, but rather for whatever websocket server you're using and whatever load balancing solution you're using. Echo is just a client, it doesn't care what it's connecting to.

I'm currently working on adding support for scaling to laravel-websockets (see https://github.com/beyondcode/laravel-websockets/pull/140) using Redis as the data backend. Once this is in, you'll be able to load balance your websocket connections to multiple instances.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
