### ISSUE TITLE
Pusher disconnect

### ISSUE THREAD

**Issue by Mat-Moo** [laravel/echo#233]
- Echo Version: 1.5.3
- Laravel Version: 5.7.19
- PHP Version: 7.1.3
- NPM Version: 6.9.0
- Node Version: 10.16.0

### Description:
I'm building a Laravel application, using echo with Pusher as the client. On pushed I've got webhooks setup to track presence channels, however if I close a tab a disconnect is not being sent (if I view the debug console I can see the events). If I open the webpage then the event are immediate. I've even tried to run the disconnect manually, but nothing seems to happen. 

I did read https://blog.pusher.com/lower-delays-in-presence-channel-disconnection-timeouts/ which is what I am experiencing, so almost like the ping/pong event didn't get a reply so then says disconnected.

### Steps To Reproduce:
1) Open the debug console in pusher
2) Create echo instance window.Echo = new Echo({...});
3) Observer events coming in
4) Try and disconnect window.Echo.disconnect(), also tried window.Echo.connector.pusher.connection.disconnect()
5) Nothing in pusher

**Comment by driesvints** [comment]
Heya, thanks for reporting this. Could you perhaps build a minimal setup which reproduces this and upload it to a github repo? I'll try to reproduce it then.

**Comment by poseidonphp** [comment]
I was just troubleshooting an issue where my connections were not being killed when navigating to a different page using vue-router. 
Slightly different than your issue, as mine were getting killed if i closed the tab. My solution was to force it to leave the channel if my Vue component was destroyed (ie - navigated away).

IF you're using VueJS - you could try adding the beforeDestroy() hook into your component, then calling Echo.leave('channel-name').

```
export default {
components: {},
data() {return {}},
created() {},
beforeDestroy() { window.Echo.leave('my-channel');}
}
```

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue and we'll re-open this issue.

**Comment by Mat-Moo** [comment]
I have been doing further research, but not come to a proper conclusion yet, hence why I've not replied still. Once I've established fact I'll report back.
