### ISSUE TITLE
Check to see if you are listening on a particular channel

### ISSUE THREAD

**Issue by nicolasvahidzein** [laravel/echo#236]
is there a way to check if we are listening on a particular channel?

when i call 

`window.Echo.private('tasks')`

i am actually subscribing to that channel again.

I need to see what my status is in regards to a particular channel so i know i need to unsubscribe before i leave that page.

Thanks.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by nicolasvahidzein** [comment]
ok added discord but there is no one ever ready to help i find.
