### ISSUE TITLE
Broadcasting using Redis Driver has a channel naming issue since v5.8 Echo

### ISSUE THREAD

**Issue by skeeith** [laravel/echo#238]
- Echo Version: 1.5.4
- Laravel Version: 5.8.28
- PHP Version: 7.2.3
- NPM Version: 6.10.2
- Node Version: 12.7.0

### Description:
Since Laravel 5.8 there were changes on the config/database.php on Redis configuration that was not written on the website documentation regarding broadcasting events using Redis.

IF you don't fully specify the channel name on your Echo listeners including the database prefix you won't receive the broadcasted events.

Laracasts Discussion
https://laracasts.com/discuss/channels/general-discussion/broadcasting-using-redis-driver-has-a-channel-naming-issue

Referring to this file
https://github.com/laravel/laravel/blob/master/config/database.php
Redis -> options -> prefix

my .env APP_NAME=TestApp

Laravel Echo Server log shows
Channel: testapp_database_test-channel 
Event: App\Events\TestEvent

js file
Echo.channel('testapp_database_test-channel').listen('TestEvent', (event) => {
    console.log(event);
});

USING IT THIS WAY WILL FAIL
Echo.channel('test-channel').listen('TestEvent', (event) => {
    console.log(event);
});

Previous Laravel versions shows
Channel: test-channel 
Event: App\Events\TestEvent

Works normally fine on previous versions.
js file
Echo.channel('test-channel').listen('TestEvent', (event) => {
    console.log(event);
});

### Steps To Reproduce:
Install Laravel 5.8
Setup queuing or horizon
Set .env BROADCAST_DRIVER=redis
Create an event and broadcast on a channel (test-channel)
Setup Laravel Echo and listen on a channel (test-channel)
and test.

**Comment by driesvints** [comment]
Thanks. There's already a bug report for here: https://github.com/laravel/framework/issues/28701

Appreciating a pr if you could send one in. Thanks.
