### ISSUE TITLE
Echo.presence is undefined

### ISSUE THREAD

**Issue by petervmeijgaard** [laravel/echo#24]
When I try to access `Echo.presence`, I get an error saying:
`Uncaught TypeError: Echo.presence is not a function`

But when I do `Echo.private` or `Echo.channel`, it works without any problems.

However, when I get it working when I use `Echo.join`, the syntax from the Laracast video about Echo.

**Comment by morloderex** [comment]
@PetervMeijgaard Have you looked at the docs for echo?
The method you should use is called `join`. not `presence`.

**Comment by PetervMeijgaard** [comment]
Yes, I have.
From https://laravel.com/docs/master/broadcasting#presence-channels

```
Echo.presence('chat.' + roomId)
    .here((users) => {
        //
    })
    .joining((user) => {
        console.log(user.name);
    })
    .leaving((user) => {
        console.log(user.name);
    });
```

**Comment by morloderex** [comment]
@PetervMeijgaard Well that might be an issue with the documentation. 
Because in the source it looks like the method is called join not presence. 

ping @taylorotwell

**Comment by PetervMeijgaard** [comment]
Yeah, exactly :) It confused me and had to check the Laracast about Echo to be sure.

**Comment by tlaverdure** [comment]
I've been using join() and not presence(). @taylorotwell is this maybe a typo in the docs, or you thinking about changing the name to avoid confusing `join()` an `joining()`?

**Comment by petervmeijgaard** [comment]
Ah I saw that the documentation has been updated. It's `join()` and nog `presence()`.

Thanks @taylorotwell :+1:

**Comment by petervmeijgaard** [comment]
Fixed in: https://github.com/laravel/docs/commit/5ddcf2fbc361e179d3b215235cce50534402897a
