### ISSUE TITLE
CSRF token is missing in /auth broadcast request

### ISSUE THREAD

**Issue by janiskelemen** [laravel/echo#252]
- Echo Version: 1.6.0
- Laravel Version: 5.8
- PHP Version: 7.3
- NPM Version: 6.11.3
- Node Version: 10.15.0

### Description:
The XSRF-TOKEN is missing in the /auth ajax request so that the /auth broadcast returns 419. Downgrade to 1.5.4 solves the issue.

**Comment by Bogardo** [comment]
This seems to be related to the change https://github.com/laravel/echo/pull/251.
The `document.hasOwnProperty('querySelector')` in particular, which in Chrome (73.0.3683.103) returns `false`.

You can temporarily fix this by setting the header yourself:

```
let echo = new Echo({
  broadcaster: 'pusher',
  key: process.env.MIX_PUSHER_APP_KEY,
  cluster: process.env.MIX_PUSHER_APP_CLUSTER,
  encrypted: true,
  auth: {
    headers: {
      'X-CSRF-TOKEN': document.querySelector('meta[name="csrf-token"]').getAttribute('content')
    }
  },
});
```

**Comment by matthewnessworthy** [comment]
@driesvints / @taylorotwell please can you tag a release, the issue remains unresolved until then

**Comment by driesvints** [comment]
Next week on release day. Please use 1.5.4 for now.

**Comment by tjipkloosterman** [comment]
adding the csrfToken option in the Echo constructor fixes this issue for now,

Or set the window.Laravel.csrfToken

**Comment by marcnewton** [comment]
For me `window.Laravel.csrfToken` not work but you can set it directly using the following path:

`vm.$Echo.connector.pusher.config.auth.headers['X-CSRF-TOKEN'] = token`
