### ISSUE TITLE
X-CSRF-TOKEN header missing after update from 1.5.4 to 1.6.0

### ISSUE THREAD

**Issue by tjipkloosterman** [laravel/echo#254]
Updated to 1.6.0 and the X-CSRF-TOKEN header is missing from the request, reverted back to 1.5.4 and the X-CSRF-TOKEN header is back in the request while authorizing via the broadcasting/auth endpoint.

since a few days my live server was not working anymore, i received a status 419 after echo was trying to authorize https://domain.com/broadcasting/auth..

My dev server was working like it should, so i tried updating npm (because my live server is updating automatically when running Salt)  and noticed Laravel echo had a new version (which i already expected), so i refreshed my browser and the same problem occurred on dev, after reverting Echo to version 1.5.4 everything is working again on both servers.

https://github.com/laravel/echo/commit/f6ce77926cc3af4d865386646e3536ce311d5a2b

**Comment by driesvints** [comment]
Please see https://github.com/laravel/echo/issues/252 

This was fixed and will be released next Tuesday.
