### ISSUE TITLE
Off function to remove specific listener

### ISSUE THREAD

**Issue by MrJmpl3** [laravel/echo#257]
Socket.io has off function, maybe can expose this to echo.

```
//To unsubscribe all listeners of an event
socket.off('event-name');

//to unsubscribe a certain listener
socket.off('event-name', listener);
```

**Comment by driesvints** [comment]
Yeah sure. Not sure if Pusher also implements this? Maybe a different name than "off" though. Maybe "ignore"?

**Comment by driesvints** [comment]
Closing this as we've only received one request for this. Feel free to PR if you want.
