### ISSUE TITLE
How to catch unsubscribe event?

### ISSUE THREAD

**Issue by MoeCasts** [laravel/echo#261]
Enviorment:
- laravel v6.x
- laravel-echo v1.6.1
- laravel-echo-server 

Question:
How can i catch unsubscribe event from user?
I want to do some things when user leave channel in backend, but i can not find the event.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
