### ISSUE TITLE
Cannot listen when joining presence channel

### ISSUE THREAD

**Issue by kevinongko** [laravel/echo#262]
- Echo Version: 1.6.1
- Laravel Version: 7.3.0
- PHP Version: 7.3.15
- NPM Version: 6.13.4
- Node Version: 10.19.0

### Description:
Cannot listen when joining presence channel because of `presence-` prefix

### Steps To Reproduce:
1. Set the broadcast channel routes in routes/channels.php
```php
  Broadcast::channel('room.{roomId}', function ($user, $roomId) {
     // some code here
  });
```
2. Echo.join to 'room' 
```js
    Echo.join(`room.${this.roomId}`)
      .here(users => { this.users = users })
      .joining(user => this.users.push(user))
      .leaving(user => _.remove(this.users, user))
      .listen('NewMessage', e => {
          console.log(e)
      })
```

3.  in NewMessage Event
```php
    public function broadcastOn()
    {
        return new PresenceChannel('room.'.$this->roomId);
    }
```

4. Remove redis prefixes in .env
```
REDIS_PREFIX=
```
5. Run laravel-echo-server and check the page
```
[7:43:06 PM] - l83ZKBCDZdXvdxKaAAAH joined channel: presence-room.1
Channel: presence-room.1
Event: App\Events\NewMessage
```

The NewMessage Event prefix the code with `presence-` but Echo cannot listen to `presence-room.1` because it join to `room.1`

Is this a bug or I'm missing something?
Thanks in advance :D

**Comment by driesvints** [comment]
Have you tried upgrading to the latest redis? https://github.com/laravel/framework/issues/32069

**Comment by ItsZiroy** [comment]
According to the Laravel docs, a user must be authenticated to join a presence channel. In the above example you did not include any authentication call back like so:
```PHP
Broadcast::channel('room.{roomId}', function ($user, $roomId) {
    if ($user->canJoinRoom($roomId)) {
        return ['id' => $user->id, 'name' => $user->name];
    }
}); 
```
Returning the user object will first make the channel a presence channel. Not just creating a 
```PHP
new PresenceChannel();
```
Object. Since the join will then receive a User as callback, Echo automatically knows it's a presence channel. 
Reference: https://laravel.com/docs/7.x/broadcasting#authorizing-presence-channels

**Comment by kevinongko** [comment]
@ItsZiroy yes, I do return user object in that callback, I'm just leaving it out for the sake of example above

@driesvints upgrading my redis from 5.0.7 to 5.0.8 somehow fixed the problem, thanks

cheers

**Comment by ankit-shah-logistic** [comment]
I have the same issue, Presence channel is not working. Is any one help me to solve this out ?
