### ISSUE TITLE
Support pusher end-to-end encryption

### ISSUE THREAD

**Issue by it-can** [laravel/echo#263]
Would be nice to have support for end-to-end encryption

https://github.com/pusher/pusher-http-php#end-to-end-encryption-beta

**Comment by driesvints** [comment]
So this is just to get it working client side right? Because you can already add the options server-side in your config.

**Comment by it-can** [comment]
yeah this seems to be possible within laravel, 

https://github.com/laravel/framework/pull/31559

But I think we also need an option to subsribe  to  ```private-encrypted-``` channels... this is not possible in echo as far as I know now...

**Comment by driesvints** [comment]
I'll mark this as an enhancement for now. Feel free to pr.

**Comment by it-can** [comment]
ok will try to find some time to create a PR...

**Comment by it-can** [comment]
@driesvints ok added a PR, can you take a look if I did it correct?

**Comment by derekmd** [comment]
@driesvints: I believe this issue can be closed? "laravel/echo" 1.7.0 and "laravel/framework" 6.17.0 changes allow private encrypted channels.
