### ISSUE TITLE
1.7.0 release does not work in IE 11

### ISSUE THREAD

**Issue by bengallienne** [laravel/echo#266]
- Echo Version: 1.7.0
- Laravel Version: 6.18.6
- PHP Version: 7.3
- NPM Version: 6.14.4
- Node Version: 10.20.1

### Description:
When compiling a Laravel environment that includes the normal echo code in the app.js file, for example;

`
import Echo from 'laravel-echo';

window.Pusher = require('pusher-js');

window.Echo = new Echo({
	broadcaster: 'pusher',
	key: process.env.MIX_PUSHER_APP_KEY,
	cluster: process.env.MIX_PUSHER_APP_CLUSTER,
	encrypted: true
});
`

After compilation, viewing the page using IE11 results in a syntax error which points to this piece of code;

`class Connector {
    /**
     * Create a new class instance.
     */
    constructor(options) {
        /**
         * Default connector options.
         */
        this._defaultOptions = {
            auth: {
                headers: {},
            },
            authEndpoint: '/broadcasting/auth',
            broadcaster: 'pusher',
            csrfToken: null,
            host: null,
            key: null,
            namespace: 'App.Events',
        };
        this.setOptions(options);
        this.connect();
    }
    /**
     * Merge the custom options with the defaults.
     */
    setOptions(options) {
        this.options = Object.assign(this._defaultOptions, options);
        if (this.csrfToken()) {
            this.options.auth.headers['X-CSRF-TOKEN'] = this.csrfToken();
        }
        return options;
    }
    /**
     * Extract the CSRF token from the page.
     */
    csrfToken() {
        let selector;
        if (typeof window !== 'undefined' && window['Laravel'] && window['Laravel'].csrfToken) {
            return window['Laravel'].csrfToken;
        }
        else if (this.options.csrfToken) {
            return this.options.csrfToken;
        }
        else if (typeof document !== 'undefined' &&
            typeof document.querySelector === 'function' &&
            (selector = document.querySelector('meta[name="csrf-token"]'))) {
            return selector.getAttribute('content');
        }
        return null;
    }
}`

### Steps To Reproduce:
Build a basic laravel app with vue front end using the versions above.
Add in the code above to include Echo in something like app.js
Try to load the page in IE, it does not load
Repeat the same process using version 1.6.1 of Echo, syntax error goes away and page loads

**Comment by taylorotwell** [comment]
Hmm, are you able to help us fix it?

**Comment by bengallienne** [comment]
I'd be happy to test some iterations if you want? From looking at what changed in the commit it seems very odd, from what I can tell you seem to have only added some brackets in some arrow function declarations, so I am unsure why that would break it.

**Comment by taylorotwell** [comment]
Sure, if you can determine the cause please PR us.

**Comment by bengallienne** [comment]
So after a bit of digging around it seems that (for some reason), that piece of code is not getting transpiled down to native javascript in version 1.7.0 whereas it does in 1.6.1. In 1.7.0 the compiled file still has ES6 in it, which IE11 doesn't understand. Have you changed how you are compiling the code at all?

**Comment by driesvints** [comment]
These are all the changes made: https://github.com/laravel/echo/compare/v1.6.1...v1.7.0

**Comment by AndyCodeWD** [comment]
The dist/echo.js file generated from running npm run build is different from the file thats published to npm.
https://unpkg.com/laravel-echo@1.6.1/dist/echo.js
Running npm run build on 1.6.1 generates an es6 file similar to 1.7.0
https://unpkg.com/laravel-echo@1.7.0/dist/echo.js

**Comment by driesvints** [comment]
I guess what that tells us is that the way it's compiled is different from before. Seems like a certain dependency dropped support for older versions? Maybe Babel?

**Comment by HansSchouten** [comment]
I am having the same issue, is there any updates on how to make it compatible again with IE11?

**Comment by driesvints** [comment]
@HansSchouten we're looking for help with this.

**Comment by derekmd** [comment]
I submitted a pull request today that will make echo.js again compile down to ES5 and it also includes the `Object.assign()` polyfill for IE11.

FYI, if this happens with other NPM packages where only an ES6 distribution is given, Laravel Mix has the ability to ES5-transpile that at the app level instead. Add the below snippet to your `webpack.mix.js` config to transpile `node_modules/laravel-echo/**/*.js`.

```javascript
mix.webpackConfig({
    module: {
        rules: [
            {
                test: /\.jsx?$/,
                exclude: /node_modules\/(?!(laravel-echo))/,
                use: [
                    {
                        loader: 'babel-loader',
                        options: Config.babel()
                    }
                ]
            },
        ]
    }
});
```

**Comment by bengallienne** [comment]
Awesome, great work @derekmd !

**Comment by mchtyener** [comment]
Please help with internet explorer echo undefined warning.
