### ISSUE TITLE
Echo cannot subscribe to notifications

### ISSUE THREAD

**Issue by ItsZiroy** [laravel/echo#269]
- Echo Version: 1.7.0
- Laravel Version: 7.9.2 
- PHP Version: 7.4.5
- NPM Version: 6.13.4
- Node Version: 12.16.1

### Description:
When trying to subscribe to notifications on a given channel, no message is ever being received. In the backend however everything is working fine and also on the laravel-echo-server the event is being dispatched. It, however, never shows in the frontend.
![image](https://user-images.githubusercontent.com/44354000/81276822-d34dd480-9053-11ea-8a8a-953cbb85f5e5.png)

Also it seems that route model binding doesn't work for notification channel authentication either. But that is an issue for the framework.

### Steps To Reproduce:
Create a broadcast notification in the laravel backend. Dispatch on a channel of your choice and try to listen to it in the frontend.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
