### ISSUE TITLE
A method to stop listening for the notification event

### ISSUE THREAD

**Issue by sudkumar** [laravel/echo#271]
Echo provides the functionality to listen a laravel notification events which internally calls the listen method on channel instance i.e.

```js
notification(callback: Function): Channel {
  // internally calls the listen method for the notification event
  return this.listen(
    '.Illuminate\\Notifications\\Events\\BroadcastNotificationCreated',
    callback
  );
}
```

This way, we don't have to provide the notification event name.

But when unsubscribing from the channel, we have to pass the notification event name

```js
const channel = new Echo(...)
channel.notification(() => {})

// when finished
channel.stopListening('.Illuminate\\Notifications\\Events\\BroadcastNotificationCreated')
```

It would be better if we could provide a method on the channel instance that would do it.

```diff
+ stopListeningForNotification (): Channel {
+    return this.stopListening('.Illuminate\\Notifications\\Events\\BroadcastNotificationCreated')
+ }
```

Please let me know what do you think. I would love to contribute.

**Comment by driesvints** [comment]
Think this is something you can easily code into your own app with a function call.

**Comment by sudkumar** [comment]
Alright. Thank you.

**Comment by dnnp2011** [comment]
Yes it can be done manually when needed, but that's not the point is it? It's about consistency and avoiding user confusion.
