### ISSUE TITLE
Net client for Laravel Echo

### ISSUE THREAD

**Issue by waltergrimmvie** [laravel/echo#272]
HI, we have a Echo runnign fine, and looking for a .net client .

I have tested the H.Sockets package that works with socket, and can be viewed here.

https://dotnetfiddle.net/WzIdnG

We are using the following code to access the wss socket server like below: 

Question: can someone please help or point me to usage of Net client to connect to laravel websockets, like in the fiddle demo ( it will not connect to the server)

// import Echo from 'laravel-echo'
// window.Pusher = require('pusher-js');
// window.Echo = new Echo({
//     broadcaster: 'pusher',
//     key: process.env.MIX_PUSHER_APP_KEY,
//     cluster: process.env.MIX_PUSHER_APP_CLUSTER,
//     wsPort: 6001,
//     wsHost: window.location.hostname,
//     encrypted: true,
//     wssPort: 6001,
//     disableStats:true,
//     enabledTransports: ['ws', 'wss'],
// });

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
