### ISSUE TITLE
Echo.private() does not subscribe to the channel

### ISSUE THREAD

**Issue by Francismori7** [laravel/echo#28]
Here is my test case:

```
        Echo.private('App.User.' + this.user.id)
            .notification((notification) => {
                console.log(notification.type);
            });

        Echo.channel('test')
            .listen('Test', () => {
                console.log('Hi');
            });
```

In my dashboard, I can only see this:
![image](https://cloud.githubusercontent.com/assets/520647/17720375/6f8b98ea-63ef-11e6-9a23-e99a0e6f4275.png)

The `test` channel is successfully subscribed as you can see. The private-App.User.2 is not. I am authenticating the request too using the default `Broadcast::channel()` call, the auth call is made by Echo properly too.

**Comment by Francismori7** [comment]
My bad. Debugbar was appending some crap on the broadcasting/auth/ route response, which screwed with Pusher's authorization process...

**Comment by farshidahmadianpin** [comment]
@Francismori7 hi bro how you subscribe to privateChannel?
i have the same issue.
