### ISSUE TITLE
how to make laravel echo setup js on cdn

### ISSUE THREAD

**Issue by rifaatch** [laravel/echo#281]
i am using laravel echo server with redis a socket notfication , i used this tutorial :

[https://www.itsolutionstuff.com/post/laravel-broadcast-redis-socket-io-tutorial-example.html]

there a JS file created :laravel-echo-setup.js is there is a way to read this file from cdnjs instead locally ?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
