### ISSUE TITLE
I can't have differents channels for production and development, with pusher

### ISSUE THREAD

**Issue by spacedog4** [laravel/echo#283]
- Echo Version: 1.8.0
- Laravel Version: 7.21.0
- PHP Version: 7.3.21
- NPM Version: 6.14.2
- Node Version: 12.16.1

### Description:
I'm using laravel with pusher and after uploading my project to production I've notice that it doesn't matter if I change the keys inside .env file, it was still poiting to the development channel instead of production until I run `run npm prod`

I don't `npm run prod` in my server, I run it locally, and locally I have my development keys inside .env, so every time I `run npm prod` I have to change that keys before sending the compiled files to production

**What I have to do if I merge my develop branch to my master branch:**

- Change keys inside .env file
- Recompile with npm run prod or npm run dev
- Push files with git

**What I want to do insted:**

- Push files with git

### Steps To Reproduce:

- Install pusher and echo and fill with the proper keys
- Change the enviroment keys from `.env` file
- Don't run `npm run prod` or `npm run dev`

**Comment by driesvints** [comment]
There's probably some caching going on here. Try running `php artisan config:clear`. Anyway, I've been using echo with different pusher production and dev channels in the past successfully. Please try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks.

**Comment by spacedog4** [comment]
Just in case other users have the same problem, here is my solution

It wans't a cache problem, this was happening because I run `npm run prod` locally, it needs to be run in the production server with the productions keys setted on the enviroment file. So i had to add this script to my server after pulling the updates

```
// Install NPM dependencies, run Mix, then delete node_modules folder
npm install && npm run prod && rm -rf ./node_modules
```
credits to Martin Bean from the [discord server](https://discordapp.com/invite/KxwQuKb)

In my case I use Plesk in my server where I can configure to pull the updates automatically, I just had to add the aditional script in Plesk
