### ISSUE TITLE
Not receiving events from pusher

### ISSUE THREAD

**Issue by alive2tinker** [laravel/echo#285]
Hi guys,
I need to implement Laravel Echo in my project for broadcasting, and I have followed the documentation precisely, but Echo does not seem to be working, since events do come to pusher debug console, but i'm not able to see them in the browser. below are the most important pieces of code:

.env:
```
BROADCAST_DRIVER=pusher

PUSHER_APP_ID=0000000000000
PUSHER_APP_KEY=-----------------------------
PUSHER_APP_SECRET=-----------------------
PUSHER_APP_CLUSTER=ap2
```

broadcasting:

```

    'default' => env('BROADCAST_DRIVER', 'pusher'),

    /*
    |--------------------------------------------------------------------------
    | Broadcast Connections
    |--------------------------------------------------------------------------
    |
    | Here you may define all of the broadcast connections that will be used
    | to broadcast events to other systems or over websockets. Samples of
    | each available type of connection are provided inside this array.
    |
    */

    'connections' => [

        'pusher' => [
            'driver' => 'pusher',
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'app_id' => env('PUSHER_APP_ID'),
            'options' => [
                'cluster' => env('PUSHER_APP_CLUSTER'),
                'useTLS' => true,
            ],
        ],
```

channels.php (PS. note: always returned true in logs):
```

Broadcast::channel('App.User.{id}', function ($user, $id) {
    \Illuminate\Support\Facades\Log::info("Load from channel");
    \Illuminate\Support\Facades\Log::info((int) $user->id === (int) $id);
    return (int) $user->id === (int) $id;
});

```

FavoriteCreate.php:

```
FavoriteCreated implements ShouldBroadcast

/**
     * Get the channels the event should broadcast on.
     *
     * @return \Illuminate\Broadcasting\Channel|array
     */
    public function broadcastOn()
    {
        return new PrivateChannel('App.User.' . $this->favorite->favorable->id);
    }

    public function broadcastAs()
    {
        return 'favorite.created';
    }

```

app.blade.php: (I suspect that `defer` may have something to do with it):
```

        <main class="py-4">
            @yield('content')
        </main>
    </div>
    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
    @yield('js')
```

BroadcastingServiceProvider.php: 
```
public function boot()
    {
        Broadcast::routes();

        require base_path('routes/channels.php');
    }
```

bootstrap.js
```
import Echo from 'laravel-echo';

window.Pusher = require('pusher-js');

window.Echo = new Echo({
    broadcaster: 'pusher',
    key: '00000000000000',
    cluster: 'ap2',
    forceTLS: true
});

```
webpack.mix.js:
```
mix.js('resources/js/app.js', 'public/js')
    .sass('resources/sass/app.scss', 'public/css')
    .sourceMaps();
```

NotificationsComponent.vue:
```
created() {
        Echo.private('App.User.'+this.user)
        .listen('favorite-created', (e) => {
            console.log(e);
        })
    }
```
Pusher DebugConsole:
```
API MESSAGE
‌

Channel: private-App.User.3, Event: Illuminate\Notifications\Events\BroadcastNotificationCreated

06:00:45

API MESSAGE
‌

Channel: private-App.User.3, Event: favorite.created
```

Any help is highly appreciated since I have been working on this for the last four days without any success.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by xlcrr** [comment]
Hi, sorry to open this again without a solution but I and others seem to have a similar problem

https://github.com/beyondcode/laravel-websockets/issues/420

I am able to see the events in the websockets dashboard, but they are not being picked up on the frontend.

I had this working previously with a similar config and would like to have a discussion about finding a solution as others will likely experience a similar problem

**Comment by xlcrr** [comment]
I was able to get it working by downgrading pusher-js to 4.4.0

`npm install pusher-js@4.4.0`

**Comment by HollyIT** [comment]
Just went through this myself. You need to add namespace:'' to your Echo constructor options. Echo defaults to app.events for the namespace. Since you're using broadcastAs, the namespace isn't part of the event name. Of course this means if you are broadcasting anything without doing a broadcastAs, then you'll have to subscribe to the fully qualified name (App\Events\WhatEver).

**Comment by farshidahmadianpin** [comment]
> npm install pusher-js@4.4.0

hey there,
i have the same issue,
in public channel is working but in private channel not working
[this is my description](https://github.com/laravel/echo/issues/302)

mr @driesvints closed all this problems without any answer :/
