### ISSUE TITLE
[React] Echo.leave is confusing

### ISSUE THREAD

**Issue by rayventerprise** [laravel/echo#286]
- Echo Version: 1.8.1
- Laravel Version: 7
- PHP Version: 7
- Node Version: 12

### Description:

I am using Pusher.js and React hooks. The documentation claims all you need to do is use Echo.leave(channel) to leave a channel and unsubscribe from listeners. Unfortunately that is not the case when you are dealing with a stateful SPA that recreates the callback. I had to add stopListening() on top of Echo.leave to prevent double callbacks when navigating pages caused new callbacks to be generated. The callbacks were not unbinded automatically on the leave method which by the name I assumed otherwise. More info here:   https://github.com/pusher/pusher-js/issues/273#issuecomment-692803569
```
function useEcho<T>(channel: string, event: string, onMessage: (message: T) => void) {
  useEffect(() => {
    if (channel !== '') Echo.private(channel).listen(event, onMessage)

    return () => {
      if (channel === '') return;

      /*
      This is absolutely needed due to callbacks not being unbinded on leave.
      If we don't use "stopListening()" and just use "leave()" it will not unbind the callback resulting in double calls.
      https://github.com/pusher/pusher-js/issues/273#issuecomment-692803569
       */
      const echoChannel = Echo.private(channel)
      echoChannel.stopListening(event)

      Echo.leave(channel)
    }
  }, [channel, event, onMessage])
}
```
### Steps To Reproduce:
1. Use React
2. Run useEffect() to trigger your echo channel listen.
3. Supply a useCallback() with dependencies to your "onMessage" in the useEcho hook.
4. Trigger one of those dependencies to update.
5. Receive a message from the event provided with useEcho.
6. You will have your callback triggered twice.

**Comment by driesvints** [comment]
Feel free to PR your solution. Thanks.
