### ISSUE TITLE
Common 'connected' and 'disconnected' callbacks

### ISSUE THREAD

**Issue by AdamGaskins** [laravel/echo#287]
Our Vue application shows the current connection status (connected or disconnected) for incoming events. We are using Laravel Echo Server on our dev deployment, and Pusher Channels for our live deployment, and so I had to set up this code:

```js
if(process.env.MIX_BROADCAST_DRIVER === 'pusher') {
    this.echo.connector.socket.on('connect', connectedCallback)
    this.echo.connector.socket.on('disconnect', disconnectedCallback)
} else {
    this.echo.connector.pusher.connection.bind('connected', connectedCallback)
    this.echo.connector.pusher.connection.bind('disconnected', disconnectedCallback)
}
```

(`socket` changed to `pusher`, and `connect` changes to `connected`)

It would be nice if there was a common way to subscribe to these events:

```js
this.echo.on('connect', connectedCallback);
this.echo.on('disconnect', disconnectedCallback);
```

**Comment by driesvints** [comment]
Don't think we're gonna work on this ourselves but we're open to PRs. Thanks
