### ISSUE TITLE
Allow socket to be provided from outside

### ISSUE THREAD

**Issue by atrauzzi** [laravel/echo#29]
I've got all my front end code nicely managed by JSPM and I would like to avoid having to put the socket.io client on my pages window object.

Maybe one of the constructor overloads for `new Echo` could look like this:

```
const socket = io("http://localhost:8083");

const echo = new Echo({
    broadcaster: "socket.io",
    socket: socket,
});
```

**Comment by driesvints** [comment]
Think this is the same as https://github.com/laravel/echo/issues/195? Feel free to reply if you believe otherwise.

**Comment by atrauzzi** [comment]
Not the same.

I'm talking about providing the active socket instance from the outside.  That issue is talking about obtaining the ID of the socket instance I want to be able to provide.

**Comment by driesvints** [comment]
Actually, I just noticed this is already possible. You can define the client on a `client` key in the options object: https://github.com/laravel/echo/blob/c829764fe05028462b4dc88fb5d7dd82b3b1914c/src/connector/socketio-connector.ts#L45-L47

I'll try to update the docs with this.

**Comment by atrauzzi** [comment]
Well look at that!  I opened this ticket quite some while ago, so I guess that just managed to sneak in on common sense.  😉 

Thanks for finding this ticket so I could get the update!

**Comment by driesvints** [comment]
@atrauzzi no problem man! 🙂
