### ISSUE TITLE
CORS Missing Allow Origin Error showing after adding Echo Code on Laravel view page

### ISSUE THREAD

**Issue by sailendra2017** [laravel/echo#296]
- Echo Version: 1.9.0
- Laravel Version: 6.14
- PHP Version: 7.2
- NPM Version: 6.14.8
- Node Version: 14.15.4
- OS : Windows 10
- Server : XAMPP

### Description:

I am getting following error after adding following code snnipet on **welcome.blade.php** page.

Code Snippet added on resources\views\welcome.blade.php
--------------------------------------------------------------
<script src="{{ asset('/js/echo.js') }}"></script>
    <script>
        if(typeof io === "undefined"){
            alert('please check your laravel-echo-server status!');
        }else{
            Echo.channel('everyone')
                .listen('SendMsgEvent', function (e) {
                    if (e.msg) {
                        app.listenMsg(e.msg);
                    }
                });
        }
    </script>

Error Screenshot :
------------------
![image](https://user-images.githubusercontent.com/25950585/104089856-30abbc80-5298-11eb-930e-861086ea48bc.png)

Can any one solve this issue ?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
