### ISSUE TITLE
Trigger client event to send message to server through Websocket connection

### ISSUE THREAD

**Issue by kelvin195eclipse** [laravel/echo#300]
Hi, I am using this with Beyondcode's Laravel Websockets package, and currently I have built a fully working server-to-client broadcasting feature with Pusher broadcaster. 

However, currently the way I trigger a client event, is by sending Ajax request to a route that execute my controller function, and then use event(xxx) function to send message back to all clients.
The clients listen to certain channel and event using Echo.channel('channel').listen('.event', (e) => {}).

And I tested to trigger the event on each keyup while typing, and my server cpu usage and load gone crazy, and I guess this is due to each keyup event performs Ajax call, which perform a TCP handshake once. 

Therefore, my question is, Is there anyway to use the established Websocket connection to send message to server, instead of using Ajax.

Thank you!

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
