### ISSUE TITLE
Laravel Echo not receiving Pusher event in Laravel 8- vujs "^2.5.17"  version

### ISSUE THREAD

**Issue by nabnitcjha** [laravel/echo#301]
**"laravel-echo": "^1.10.0",**
**"laravel-mix": "^6.0.6",**
**"popper.js": "^1.12",**
**"pusher-js": "^7.0.3",**
**"vue": "^2.5.17",**
**"laravel": "8",**

### **I write Echo in app.js** 
    created () {
        window.Echo.channel('privateChat')
            .listen('ChatEvent', (e) => {
                console.log(e);
            });
    },

###  **Event broadCasting function**
    public function sendMessage(Request $request)
    {
        $user = Auth::user();
        $message = new Message();
        $message->user_id = $user->id;
        $message->message = $request->message;
        $message->friend_id = $request->friendID;
        $message->my_id = $user->id;
        $message->save();
        // broadcast(new MessageSent($user, $message))->toOthers();
        event(new ChatEvent($request->friendID));
        return ['status' => 'Message Sent!'];
    }

###  **BroadCast service provider**
class BroadcastServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        Broadcast::routes();
        require base_path('routes/channels.php');
    }
}

**Events -> chatEvent.php**
class ChatEvent implements ShouldBroadcast
{
    use Dispatchable, InteractsWithSockets, SerializesModels;

    public $friendID;

    public function __construct($friendID)
    {
        //
        return $this->friendID = $friendID;
    }

    /**
     * Get the channels the event should broadcast on.
     *
     * @return \Illuminate\Broadcasting\Channel|array
     */
    public function broadcastOn()
    {
        return new PrivateChannel('privateChat');
    }
}

**routes -> channels.php**
Broadcast::channel('privateChat', function () {
    return Auth::check();
  });

![image](https://user-images.githubusercontent.com/69066722/109425863-930c7800-7a12-11eb-821e-446425dadf69.png)

![image](https://user-images.githubusercontent.com/69066722/109425880-a15a9400-7a12-11eb-9efb-234235235da3.png)

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
