### ISSUE TITLE
laravel Broadcasting in private channels is not working.( cant subscribe to private channels automaticaly)

### ISSUE THREAD

**Issue by farshidahmadianpin** [laravel/echo#302]
- Echo Version: 1.10.0
- Laravel Version: 8.4.0
- PHP Version: 7.4
- NPM Version: 6.14.6
- Node Version: 4.1.0
- pusher/pusher-php-server: 4.1.5
- pusher-js: 7.0.3

### Description:
I use pusher and laravel-echo to create chat app in laravel. public Channels work properly. 

I use [pusher.com debug console](https://dashboard.pusher.com/apps) and I realized in PrivateChannel laravel-echo can't subscribe users to Available private channels automaticaly.
notice that commented codes is for public channel.

`App\Events\ChatBroad.php` is:

```
    public function broadcastOn()
    {
        //        return new channel('recieve-chat.' . $this->chat['reciever_id']);
        return new PrivateChannel('recieve-chat.' . $this->chat['reciever_id']);
    }
```

`routes/channels.php` is:
```
Broadcast::channel('recieve-chat.{reciever_id}', function ($user , $reciever_id) {
      return true;
   // return $user->id == $reciever_id;

});
```
and in `App\Providers\BroadcastServiceProvider` i use this middleware:

`Broadcast::routes(['middleware' => ['auth']]);
`

`bootstrap.js ` is:
```
import Echo from 'laravel-echo'

window.Pusher = require('pusher-js');

window.Echo = new Echo({
    broadcaster: 'pusher',
    key: '83b97539662b786ffabb',
    cluster: 'eu',
    forceTLS: true,
    authEndpoint: '/broadcasting/auth',
    csrfToken: $('meta[name="csrf-token"]').attr('content'),
});
```

blade view file:

```
        <script src="{{asset('js/app.js')}}"></script>
        <script>
            {{--window.addEventListener('DOMContentLoaded' , function () {--}}
            {{--    Echo.channel('recieve-chat.{{Auth::id()}}' )--}}
            {{--        .listen('ChatBroad', (e) => {--}}
            {{--            window.livewire.emit('recieve:' + e.chat.bid_id , e.chat);--}}
            {{--            $(chatScrollDown('.chat'+ e.chat.bid_id ));--}}
            {{--        });--}}
            {{--});--}}

```
            window.addEventListener('DOMContentLoaded' , function () {
                Echo.private('recieve-chat.{{Auth::id()}}' )
                    .listen('ChatBroad', (e) => {
                        window.livewire.emit('recieve:' + e.chat.bid_id , e.chat);
                        $(chatScrollDown('.chat'+ e.chat.bid_id ));
                    });
            });
        </script>

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by farshidahmadianpin** [comment]
hey there @driesvints 
i try this problem in laracasts and stackoverflow and nobody cant answered me.

when in "App\Events\ChatBroad.php" i use "Channel" and  in view script code i use "Echo.channel" it's work properly.
but if i use "PrivateChannel" in "App\Events\ChatBroad.php" and  in view script code i use "Echo.private" it's not working.

please help me 
[https://laracasts.com/discuss/channels/laravel/laravel-broadcasting-broadcasting-in-private-chanel-not-working](https://laracasts.com/discuss/channels/laravel/laravel-broadcasting-broadcasting-in-private-chanel-not-working)
[https://stackoverflow.com/questions/66447911/laravel-broadcasting-broadcasting-in-private-chanel-not-working-i-use-laravel-ec](https://stackoverflow.com/questions/66447911/laravel-broadcasting-broadcasting-in-private-chanel-not-working-i-use-laravel-ec)

**Comment by driesvints** [comment]
The linked support requests are only a day old. Please give it a few more days.

**Comment by farshidahmadianpin** [comment]
please man, i'm under Pressure.
this is not a normal issue. i try everything but isn't working.
please help me

**Comment by farshidahmadianpin** [comment]
and in `App\Providers\BroadcastServiceProvider` i use this middleware:

`Broadcast::routes(['middleware' => ['auth']]);
`

**Comment by farshidahmadianpin** [comment]
common man please open issue , Maybe Someone else can help me

**Comment by taylorotwell** [comment]
Is the user actually logged into the application?

**Comment by farshidahmadianpin** [comment]
@taylorotwell
yes users logged in to app.
i use pusher debug console. and I noticed that in public channel users subscribed to channel but in the private channel this is not happen.
![image](https://user-images.githubusercontent.com/43478634/110105307-78912080-7dbd-11eb-9e69-b0c7d9b5d356.png)

**Comment by farshidahmadianpin** [comment]
@taylorotwell @driesvints
hey there,
i try to subscribe manualy to private channel and I looked at the Echo Library.
in src\connector\pusher-connector.ts :
![image](https://user-images.githubusercontent.com/43478634/110237266-4d8b0600-7f50-11eb-84fd-a6aa1397efad.png)
 
and in src\channel\pusher-channel.ts :
![image](https://user-images.githubusercontent.com/43478634/110237301-92af3800-7f50-11eb-9b28-41cdf9301157.png)
also in src\channel\pusher-private-channel.ts  we have :

![image](https://user-images.githubusercontent.com/43478634/110237363-ed489400-7f50-11eb-83bf-34d831291c79.png)

Is it possible that in PusherPrivateChannel class fails to subscribe to private channel??
please help me

**Comment by driesvints** [comment]
What would really help here is if you could provide a repository for me to pull in that reproduces this issue. Please commit your custom changes separately from the base skeleton.

**Comment by farshidahmadianpin** [comment]
@driesvints 

I do not have enough knowledge to edit the library.
I explained all my codes in [here](https://github.com/laravel/echo/issues/302#issue-821240665). And I have not written anything other than these codes.
 i installed fresh laravel and done everything step by step from [laravel broadcasting docs](https://laravel.com/docs/8.x/broadcasting) and not working again.

**Comment by driesvints** [comment]
Hey @farshidahmadianpin. You don't need to edit the library, just create a new repo with an app that reproduces the issue. Please commit your custom changes separately from the base skeleton.

**Comment by farshidahmadianpin** [comment]
@driesvints
hey bro,
i create simple application. in [repo ](https://github.com/farshidahmadianpin/laravel-echo-test).
i have one route for this app:` shop.test/cart`
if you open this url in to diffrent tabs. it work properly in public channels.
now setting of private channel added in private branch.
login to app and try it. u can see laravel echo unable to subscribe to privtechannel

**Comment by driesvints** [comment]
Can you please recreate that repo with your custom changes committed separately like I asked?

**Comment by driesvints** [comment]
I realize there's a language barrier here. So let me know if there's anything you don't understand.

**Comment by farshidahmadianpin** [comment]
@driesvints
i create repo in two deffrent branches.
main branch  is for public channel and work prperly .
private branch  is for private channel and not working.

**Comment by farshidahmadianpin** [comment]
i have no custom change.
i create two commit. first "commit" is for publc channel and "private channel commit" for private channel
[repo](https://github.com/farshidahmadianpin/laravel-echo-test)

**Comment by farshidahmadianpin** [comment]
@driesvints i'm sorry.
[this is new repo as you want](https://github.com/farshidahmadianpin/laravel-echo/commits/main)
i commit all changes from skeleton, step by step.🌸🙏

**Comment by driesvints** [comment]
Okay I got it working. A couple of things:

- This env variable needs to be set to `pusher` (see the docs): https://github.com/farshidahmadianpin/laravel-echo/blob/main/.env.example#L17
- It's best that you move this piece of code inside your JS files (in the app.js file for example): https://github.com/farshidahmadianpin/laravel-echo/blob/main/resources/views/cart.blade.php#L28-L34
- I needed to remove the `['middleware' => ['auth']]` here. Not sure why you added that. https://github.com/farshidahmadianpin/laravel-echo/blob/main/app/Providers/BroadcastServiceProvider.php#L17
- It's best that you define these with mix keys and define the env keys in your .env file (see the docs): https://github.com/farshidahmadianpin/laravel-echo/blob/main/resources/js/bootstrap.js#L15-L16

Hope that helps.

**Comment by farshidahmadianpin** [comment]
thank you very much.
i remove this `['middleware' => ['auth']]` and its working.
thank you 🙏🙏🙏🙏🌺🌺🌸❤️

**Comment by n795113** [comment]
> 

I have the same issue. Public channel works and the private doesn't.

**Comment by pildit** [comment]
Hey can you please re-share that repo ? I have the same issue

**Comment by hyphen81** [comment]
same issue...would really help if that repo was available.

**Comment by dlogic-lbs** [comment]
Yes, I have the same issue. It is ridiculous, that @farshid-ahmadian had to go all the distance with you for you then to simply not keeping the repo and those solutions opened / available. I struggle to understand, how is not keeping it to help others (?) - why don't you simply remove this entire page from the web forever? Thanks, the solutions would help a lot.

**Comment by anas322** [comment]
I have the same issue and this repo that you deleted would be helpfull :(

**Comment by golden-gab** [comment]
Need help i have the same issue

**Comment by jeanC-git** [comment]
#2023

Laravel 10.1 - composer.json:
- "pusher/pusher-php-server": "^7.2"
- "beyondcode/laravel-websockets": "^1.14",

Vue project:
- "laravel-echo": "^1.15.3",
- "pusher-js": "^8.3.0",

I have the same problem.
Any updates on these issue?

**Comment by dcdebug** [comment]
> hey there @driesvints i try this problem in laracasts and stackoverflow and nobody cant answered me.
> 
> when in "App\Events\ChatBroad.php" i use "Channel" and in view script code i use "Echo.channel" it's work properly. but if i use "PrivateChannel" in "App\Events\ChatBroad.php" and in view script code i use "Echo.private" it's not working.
> 
> please help me https://laracasts.com/discuss/channels/laravel/laravel-broadcasting-broadcasting-in-private-chanel-not-working https://stackoverflow.com/questions/66447911/laravel-broadcasting-broadcasting-in-private-chanel-not-working-i-use-laravel-ec

The solvtion in this link(include laracast) works for me. 
Thanks .
