### ISSUE TITLE
laravel echo cant subscribe to private channel.

### ISSUE THREAD

**Issue by farshidahmadianpin** [laravel/echo#303]
- Echo Version: 1.10.0
- Laravel Version: 8.4.0
- PHP Version: 7.4
- NPM Version: 6.14.6
- Node Version: 4.1.0
- pusher/pusher-php-server: 4.1.5
- pusher-js: 7.0.3

### Description:

i see many peoples have this issue. and nobody cant solve it.

please dont closing this issue until to recieving  answer

how i can subscribe to private channel manualy?

### Steps To Reproduce:
[my description is there](https://github.com/laravel/echo/issues/302)

**Comment by driesvints** [comment]
Please don't open duplicate issues. I'll re-open your other one and have a look when I find the time.

**Comment by farshidahmadianpin** [comment]
@driesvints thank you 💜
