### ISSUE TITLE
Not Subscribing to Presence Channel, not even in Pusher dashboard

### ISSUE THREAD

**Issue by gweinxx** [laravel/echo#304]
- Echo Version: 1.10.0 (Current version of Laravel echo)
- Laravel Version: 7.30.1
- PHP Version: 7.4.7
- NPM Version: 6.14.5
- Node Version: 12.18.1

### Description:

I have spend hours to solve this issue of mine, googling here and there, **SO, Laracast, etc**, but still couldn't solve this problem
The only feature of Laravel Echo that works for me is only **public channel** and **private channel**, but somehow I cannot make presence channel to work

### Steps To Reproduce:
1. Create new / fresh laravel app

2. Install:
    - `laravel/sanctum`
    - `pusher/pusher-php-server` (v 4.0)
    - `vue`
    - `vuex`
    - `vuei18n`
    - `vue-meta`
    - `vue-router`
    - `vue-template-compiler`
    - `laravel-echo`
    - `pusher-js`

3. Setting things up, login - logout, controller logic, migration, etc

4. In `resource/js/bootstrap.js`
![Fact 1](https://user-images.githubusercontent.com/39983680/110459873-13606680-8100-11eb-822d-5177444414e3.png)

5. In `routes/api.php`
![Fact 2](https://user-images.githubusercontent.com/39983680/110460056-4e629a00-8100-11eb-8cf2-b44a2f8b4f19.png)

6. In `routes/channels.php`
![Fact 3](https://user-images.githubusercontent.com/39983680/110460734-2a538880-8101-11eb-8edd-61fc9053127d.png)

7. In `home.vue`
![Fact 3](https://user-images.githubusercontent.com/39983680/110460419-c03ae380-8100-11eb-9c52-8a8b07bafd03.png)

**Comment by driesvints** [comment]
I'm very sorry but this isn't a support channel. As you have a pretty specific setup for your app I'm going to have to ask you to continue to try one of the following support channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem.

Thanks.
