### ISSUE TITLE
Echo.private should offer a callback to be called when it finishes subscribing

### ISSUE THREAD

**Issue by viaativaweb** [laravel/echo#305]
Hello, I want to open a channel, whisper a quick message and leave. Like that:

```
Echo.private('chat')
.whisper('typing', {name: this.user.name});
```

When doing that using Pusher I got the error:

> Cannot broadcast client event (connection not subscribed to channel private-chat)

According to the threads I read, the "official" solution is a timeout:

```
var channel = Echo.private('chat');

setTimeout(() => {
  channel .whisper('typing', {name: this.user.name});
}, 300);
```

To me that seems sloopy, what if it takes more than 300s to subscribe (my case)? Should I just give it a an arbitrarily large timeout until I cover all possible delays? 

I think an callback would be ideal:

```
var channel = Echo.private('chat');

channel.on('subscribed', () => {
  channel .whisper('typing', {name: this.user.name});
});
```

**Comment by driesvints** [comment]
Feel free to attempt a PR 👍
