### ISSUE TITLE
Not return callback error

### ISSUE THREAD

**Issue by dat0825** [laravel/echo#307]
When i join presence room with not Authorization but error callback not return
Anyone hleps me. Many thanks!
Here is my code:
```
let token = ''
window.Echo = new Echo({
    broadcaster: 'socket.io',
    host: 'wss://127.0.0.1:3444',
    auth:
        {
            headers:
                {
                    // 'Authorization': 'Bearer ' + token
                }
        }
});
window.Echo.connector.socket.on('connect', function () {
    console.log("Connecttt success")
})

window.Echo.connector.socket.on('disconnect', function () {
    console.log("Disconnectedd !!!!!!")
})

window.Echo.join("66b65878-5e0f-427e-9d4a-0d91f76ffe14")
    .here((users) => {
        console.log("Joined room")
    })
    .joining((user) => {
        console.log("joinning", user);
    })
    .leaving((user) => {
        console.log("leaving", user);
    })
    .listen('MessageCreated', (e) => {
        console.log("Message", e)
    })
    .error(function (error) {
        console.error(error);
    })
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
