### ISSUE TITLE
Echo not sending ping-pong while receiving messages from server

### ISSUE THREAD

**Issue by dark0fire** [laravel/echo#308]
- Echo Version: 1.10.0
- Laravel Version: 8.35.1
- PHP Version: 8.0.3
- NPM Version:7.5.2
- Node Version: 15.8.0
- beyondcode/laravel-websockets: 2.0.0-beta-34

### Description:
When receiving messages from the server at a higher rate(about 1 every 3 seconds), echo is not sending the pingpong, therefore my connection is disconnected at the server

### Steps To Reproduce:

- php artisan websockets:serve
- connecting via echo to private channel
- sending events from laravel
- receiving events in echo
- 2 minutes after last pingpong, while receiving messages from the server, I stop receiving messages(verified the server cleans up subscriptions every 120 seconds)

I dont think the server shouldn't clean up, I think echo(or pusherjs) should pingpong, but there is no built-in option to do so myself. Maybe this might be a feature request, but since I do not see any documentation on the issue, I assume it is a bug.

If you need more info please let me know, there is a lot of files involved in the complete picture, but I think it should boil down to what I've described.

[I've also created a question on stackoverflow with some images](https://stackoverflow.com/questions/67130157/laravel-echo-pusher-not-sending-ping-when-receiving-data/67130288#67130288)

**Comment by driesvints** [comment]
> php artisan websockets:serve

This command doesn't exists in Echo. Please try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

**Comment by dark0fire** [comment]
I would like you to reconsider looking into the issue. I only added that line to ensure you understand what im working with, but the fact that there is no ping-pong between receive messages is something that comes from echo right?
