### ISSUE TITLE
Socket.io Remove Params

### ISSUE THREAD

**Issue by shayanxshaan** [laravel/echo#309]
Hello,
I had a problem with socket.io when using Laravel Echo.
I want to connect WebSocket via socket.io with Echo in laravel, but I get an origin Error.

But if I connect to a socket without Echo, it's fine and works great! But I want to use laravel echo for broadcasting!

The only difference between direct connect and laravel echo is the URL!

When I connect to the WebSocket directly, my URL didn't change! But when I try to connect with laravel echo, I see some parameters like ( EIO & transport & sid ). I think this is my problem! But I don't know how to remove these params from the URL when using laravel echo!

Does anyone know what my problem is?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
