### ISSUE TITLE
Pusher systematically disconnect after 30s

### ISSUE THREAD

**Issue by wassim** [laravel/echo#310]
I have setup my Laravel app with Pusher & Echo. Everything works as it should. I can broadcast an event and listen to it in my vue component. However there is a Pusher disconnection systematically after  30 seconds. Tab still opened on same page. What am I doing wrong?

- pusher/pusher-php-server: 5.0.3
- Echo Version: ^1.10.0
- Laravel Version: 8.40.0
- PHP Version: 7.4

`broadcasting.php`
```php
      'pusher' => [
            'driver' => 'pusher',
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'app_id' => env('PUSHER_APP_ID'),
            'options' => [
                'cluster' => env('PUSHER_APP_CLUSTER'),
                'useTLS' => true
            ],
      ],
```

`bootstrap.js`
```javascript
import Echo from 'laravel-echo';

window.Pusher = require('pusher-js');

window.Echo = new Echo({
    broadcaster: 'pusher',
    key: process.env.MIX_PUSHER_APP_KEY,
    cluster: process.env.MIX_PUSHER_APP_CLUSTER,
    forceTLS: true
});
```

`MyEvent.php`
```php
    ...

    public function broadcastOn()
    {
        return new Channel('channel');
    }
```

`MyComponent.vue`
```javascript
        mounted() {
            Echo.channel('channel')
                .listen('MyEvent', (e) => {
                    console.log(e)
                })
        }
```

Pusher logs

```
Vacated | Channel: channel
Disconnection | Channels: channel, Lifetime: 30.256465965s
API message | Channel: channel, Event: App\Events\MyEvent
Occupied | Channel: channel
Subscribed | Channel: channel
Connection | Origin: http://localhost:3000
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
