### ISSUE TITLE
distribute compiled assets within the repo

### ISSUE THREAD

**Issue by cschra** [laravel/echo#311]
Hi,

I was wondering if you plan or think about distributing a compiled version of echo inside this repository. This would enable people without node (npm) to include this project as git submodule.
This would be great for the project/company I am working for as the only other option is to add the minified file to the repository.

Thank you very much in advance! 
Kind regards,
Christian

**Comment by driesvints** [comment]
We have no plans for this, sorry.

**Comment by cschra** [comment]
Thanks for your quick answer!
