### ISSUE TITLE
Stop listening to channel.here(), .joining() and leaving()

### ISSUE THREAD

**Issue by AdrianMrn** [laravel/echo#312]
Originally commented this in #51, but this deserves its own issue imo.

I want to stop listening to the `pusher:member_added` and `pusher:member_removed` events that are registered by `channel.joining()` and `channel.leaving()`. I tried `channel.stopListening('pusher:member_added', callback);` and some other things, but this doesn't seem to work. I also don't want to run `channel.leave()` and `channel.join()` every time my page rerenders.

It seems like this is being caused by the `here`, `joining` and `leaving` methods not using the actual callback you pass into it (like the `listenForWhisper` method does), but instead creating one for itself, making it impossible to remove it afterwards from the other side of the library:
https://github.com/laravel/echo/blob/b583f2641b51e7b4ab39c5bb03626be8add47722/src/channel/pusher-presence-channel.ts#L22-L28

Can anyone think of a non-breaking fix for this?

I can only think of these (breaking) changes:

This changes the return type from `this` to a function you can call to remove the event listener:
```
here(callback: Function): PusherPresenceChannel {
    function removableCallback(data) {
        callback(Object.keys(data.members).map((k) => data.members[k]));
    }

    this.on('pusher:subscription_succeeded', removableCallback);

    return () => this.stopListening('pusher:subscription_succeeded', removableCallback);
}
```

This moves the burden of formatting the callback's payload to the user, but it would allow us to run `channel.stopListening('pusher:subscription_succeeded', callback)` (not taking into consideration the fact that `listening` and `stopListening` seem to format the listener keys 👀 ):
```
here(callback: Function): PusherPresenceChannel {
    this.on('pusher:subscription_succeeded', callback);

    return this;
}
```

_Originally posted by @AdrianMrn in https://github.com/laravel/echo/issues/51#issuecomment-850483993_

**Comment by AdrianMrn** [comment]
A workaround is to use `channel.on('pusher:member_added', onJoining);` instead of `channel.joining`. You can then remove the listener by running `channel?.subscription.unbind('pusher:member_added', onJoining);`.

**Comment by driesvints** [comment]
I don't think we ever intended to have people pass the `pusher:` events to the Echo methods. That's why Echo exists, to wrap around those. 

> I also don't want to run channel.leave() and channel.join() every time my page rerenders.

Why not? What's the difference with `stopListening`?

> (not taking into consideration the fact that listening and stopListening seem to format the listener keys 👀 )

This is expected. We format the listener keys so they're formatted correctly according to a class namespace (see the Echo docs).

> It seems like this is being caused by the here, joining and leaving methods not using the actual callback you pass into it (like the listenForWhisper method does), but instead creating one for itself, making it impossible to remove it afterwards from the other side of the library:

What I think is missing here is two things:

1. Dedicated methods to stop listening for specific pusher events: `pusher:member_added` & `pusher:member_removed`
2. The ability to pass `pusher:` events to `stopListening`

Would you say that if these dedicated methods and/or the nr 2 ability existed that your problems are solved?

> at that point I'm not sure what the benefit of using laravel-echo over pusher-js is.

I feel like you're trying to use the library in a way it wasn't intended. This library is a direct integration with Laravel and provides easy integration to allow events to be listened to based on class namespaces/object names, etc. And provides authorization capabilities though broadcasting channels.

If we can add the functionality you're seeking then I think it'll be of benefit to you as well.

**Comment by AdrianMrn** [comment]
Thanks for the clear answer @driesvints. My original post may have been slightly emotional because of my frustration in debugging websockets at the end of a long week, sorry!

>Why not? What's the difference with stopListening?

Similar to the OP's comment here, leaving the channel would unsubscribe from events that were registered elsewhere. In our specific case, we have multiple listeners on `pusher:member_added` and `pusher:member_removed`.

>1. Dedicated methods to stop listening for specific pusher events: pusher:member_added & pusher:member_removed

Would this unregister all callbacks from those events? In my case, this would also unsubscribe me from events I didn't intend to. If it could work something like DOM event listeners, that would be great (where you pass in the specific callback you want to unregister from the listener):

```
const callback = () => { … };
node.addEventListener('click', callback);
node.removeEventListener('click', callback);
```

Right now, I don't think this would work, because the callback the user passes is not being used directly in the event listener (I may be unaware of a suitable workaround here).

>2. The ability to pass pusher: events to stopListening

I think this has the same downside as above solution.

**Comment by driesvints** [comment]
@AdrianMrn maybe these three new methods?

```
    /**
     * Register a callback to be called anytime the member list changes.
     */
    stopHere(callback: Function): PusherPresenceChannel {
        this?.subscription.unbindEvent('pusher:subscription_succeeded', (data) => {
            callback(Object.keys(data.members).map((k) => data.members[k]));
        });

        return this;
    }

    /**
     * Listen for someone joining the channel.
     */
    stopJoining(callback: Function): PusherPresenceChannel {
        this?.subscription.unbindEvent('pusher:member_added', (member) => {
            callback(member.info);
        });

        return this;
    }

    /**
     * Listen for someone leaving the channel.
     */
    stopLeaving(callback: Function): PusherPresenceChannel {
        this?.subscription.unbindEvent('pusher:member_removed', (member) => {
            callback(member.info);
        });

        return this;
    }
```

**Comment by driesvints** [comment]
Ignore the docblocks, forgot to edit them.

**Comment by driesvints** [comment]
@AdrianMrn does that look good to you?

**Comment by AdrianMrn** [comment]
@driesvints

Does this solution work in practice? Wouldn't this still run into the same issue I described here?:

>Right now, I don't think this would work, because the callback the user passes is not being used directly in the event listener

Because you're creating and passing a new function into `unbindEvent`, it won't find an event listener for the callback that was originally registered. This is how `removeEventListener` works and I would think it works the same in `pusher-js`' implementation, but like I said there might be a detail/workaround I'm forgetting about here.

A bit of a convoluted solution would be to save an array of event listeners alongside the original callbacks that were passed in by the user, and unregister those. I could have a go at this soon if you want?

**Comment by driesvints** [comment]
> Does this solution work in practice? Wouldn't this still run into the same issue I described here?:

I have no idea. I'm not really good with JS 😅 I'd assume it works because it's the same callback. Or do you think it always needs to be a reference? Can you maybe try it out?

> A bit of a convoluted solution would be to save an array of event listeners alongside the original callbacks that were passed in by the user, and unregister those. I could have a go at this soon if you want?

Will get back to you on that.

**Comment by driesvints** [comment]
@AdrianMrn so yes feel free to attempt a pr which you feel is best 👍

**Comment by driesvints** [comment]
Going to close this one as it's best to follow up in the PR. Feel free to send it in when you can.
