### ISSUE TITLE
Pusher worker support

### ISSUE THREAD

**Issue by s-patompong** [laravel/echo#313]
I'm trying to use Echo in my service worker js file. Pusher has its own worker script but I can't find any worker script from Echo. Is there a workaround on this?

This is the service worker code:
```js
import Echo from 'laravel-echo';
import Pusher from 'pusher-js/worker';

let window = self;

window.Pusher = Pusher;
window.LaravelEcho = new Echo({
  broadcaster: 'pusher',
  key: process.env.MIX_PUSHER_APP_KEY,
  wsHost: location.hostname,
  wsPort: 6001,
  wssPort: 6001,
  disableStats: true,
});
```

And this is the error from the console:
```
Uncaught TypeError: Pusher is not a constructor
    at PusherConnector.connect (sw.js:981)
    at new Connector (sw.js:156)
    at PusherConnector.<anonymous> (sw.js:125)
    at new PusherConnector (sw.js:962)
    at Echo.connect (sw.js:1390)
    at new Echo (sw.js:1366)
    at sw.js:5824
    at sw.js:5839
    at sw.js:5841
```

To me, it seem like Pusher works differently in its worker script (having Pusher not being a constructor for example). Any knowledge about how to integrate Echo with this is highly appreciated :)

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by UpdateWebTeam** [comment]
I have the same proplem
