### ISSUE TITLE
Missing type definitions for PresenceChannel

### ISSUE THREAD

**Issue by JonathanGuo** [laravel/echo#317]
- Echo Version: 1.11.0
- Laravel Version: 8.49.2
- PHP Version: 8.0.6
- NPM Version: 6.14.8
- Node Version: 14.15.1

### Description:

First of all, thanks for the great work of the `laravel-echo` package!

I've noticed the type definition of `PresenceChannel` is incorrect. (it might be out of date).

According to the interface `PresenceChannel` it has only 3 functions:

```TypeScript
/**
 * This interface represents a presence channel.
 */
export interface PresenceChannel {
    /**
     * Register a callback to be called anytime the member list changes.
     */
    here(callback: Function): PresenceChannel;

    /**
     * Listen for someone joining the channel.
     */
    joining(callback: Function): PresenceChannel;

    /**
     * Listen for someone leaving the channel.
     */
    leaving(callback: Function): PresenceChannel;
}
```

However, the `PusherPresenceChannel` extends `PusherChannel`, which has more functions. e.g. `listen`

Functionally it's working fine with compiled JavaScript package, but with the `@typescript-eslint` rule [`no-unsafe-call`](https://github.com/typescript-eslint/typescript-eslint/blob/v4.27.0/packages/eslint-plugin/docs/rules/no-unsafe-call.md) rule turned on, we will get the warning/error (depends on config) messages:

```
Unsafe call of an `any` typed value.eslint@typescript-eslint/no-unsafe-call
```

And the following error from ts:

```
Property 'listen' does not exist on type 'PresenceChannel'.ts(2339)
```

Unfortunately, we cannot even cast the type because the types/interfaces do not overlap:

```TypeScript
(Echo.join(channelName) as Channel).listen() // Would throw the following error

// Conversion of type 'PresenceChannel' to type 'Channel' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
// Type 'PresenceChannel' is missing the following properties from type 'Channel': options, listen, listenForWhisper, notification, and 4 more.ts(2352)
```

#### 🚑 Hotfix
To who has similar issues and seek a workaround, use double-cast can be a quick way:

```TypeScript
(Echo.join(channelName) as unknown as Channel).listen() 
```

### Steps To Reproduce:

1. Turn on the rule `@typescript-eslint/no-unsafe-call`
2. Chain the presence channel: `Echo.join(channelName).listen(() => {});`

---

I am more than happy to submit a PR to fix the interface definitions. Please let me know if the issue I raised is on the right track.

**Comment by driesvints** [comment]
I don't really see an issue here, sorry. A presence doesn't needs all these methods. They're defined on the base `Channel` class.

**Comment by JonathanGuo** [comment]
> I don't really see an issue here, sorry. A presence doesn't needs all these methods. They're defined on the base `Channel` class.

Hi @driesvints . Surely the errors exist in TypeScript. The compiled JavaScript code has the methods, but the `PresenceChannel` Interface misses the definition of the methods.

The following examples are created in this repo:

First, it doesn't have a type hint when using TS:

![image](https://user-images.githubusercontent.com/3345508/125360958-bf70d180-e3c0-11eb-8bf0-52452a62e3a5.png)

It has a `Property does not exist on Type` error when you use `listen`
![image](https://user-images.githubusercontent.com/3345508/125360991-cbf52a00-e3c0-11eb-9729-2231b9933d72.png)

Secondly, it cannot be cast to `Channel` due to the interface doesn't extend anything, they don't overlap the type definitions:
![image](https://user-images.githubusercontent.com/3345508/125361255-2c846700-e3c1-11eb-9f5c-f1bc7e6abd58.png)

This issue is basically caused by missing type definitions.

Please review.

**Comment by driesvints** [comment]
It's best you attempt a PR if you think anything is broken here 👍

**Comment by JonathanGuo** [comment]
> It's best you attempt a PR if you think anything is broken here 👍

Will do
