### ISSUE TITLE
.here() function does not update when a new user joins or leaves

### ISSUE THREAD

**Issue by SirCumz** [laravel/echo#32]
.here() function does not get called when a new user joins or leaves.

I just tested it with 2 accounts in 2 different browsers. it only gets called when i refresh the browser.

im using socket.io (redis)

**Comment by joexanderson** [comment]
.here() is only fired once, on the initial load. I'm using Pjax, for example, and on the initial page, .here() works. But on subsequent pages, it's not fired again so only those who trigger the .leave() and .joined() events show up.

Maybe it could be more useful if it could be called directly?

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
