### ISSUE TITLE
v1.11.1 was released without building

### ISSUE THREAD

**Issue by JonathanGuo** [laravel/echo#321]
- Echo Version: 1.11.1
- Laravel Version: 8.51.0
- PHP Version: 8.0.6
- NPM Version: 6.14.0
- Node Version: 14.15.1

### Description:

The last release v1.11.1 seems released without running `npm run build` to have the latest `PresenceChannel.ts` to be included in `dist`.

### Steps To Reproduce:

```bash
npm i laravel-echo@1.11.1

cat node_modules/laravel-echo/dist/channel/presence-channel.d.ts
```

expected the following output:

```typescript
/**
 * This interface represents a presence channel.
 */
export interface PresenceChannel {
    /**
     * Register a callback to be called anytime the member list changes.
     */
    here(callback: Function): PresenceChannel;
    /**
     * Listen for someone joining the channel.
     */
    joining(callback: Function): PresenceChannel;
    /**
     * Listen for someone leaving the channel.
     */
    leaving(callback: Function): PresenceChannel;
}
```

If I clone the repo and run `npm run build`, I should have the correct interface exported.

**Comment by driesvints** [comment]
Will take care of this soon, thanks.

**Comment by driesvints** [comment]
We've done a new release with the build. Thanks for reporting.
