### ISSUE TITLE
Laravel broadcast private channel can be subscribe by Echo::channel()

### ISSUE THREAD

**Issue by nogamenofun98** [laravel/echo#329]
- Echo Version: 1.11.2
- Laravel Version: 8.61.0
- PHP Version: 8.0.8
- NPM Version: 6.14.13
- Node Version: 14.17.0

### Description:
![image](https://user-images.githubusercontent.com/9070825/139202014-2262478a-b3d7-4e0c-8c80-a6ce8f78dfc9.png)

When the frontend using laravel echo to subscribe to the channel, if I use Echo.private(), then it will call "/broadcasting/auth" api to get the token, and if I didnt pass the auth header in Echo there, it will show authentication failed. However, if I call Echo.channel() to subscribe to the same private channel, it just directly show "pusher_internal:subscription_succeeded" in the message, meaning it is successfully subscribe to the private channel without need to authentication using the auth headers, but it supposingly should show authentication error.

![image](https://user-images.githubusercontent.com/9070825/139202302-1c5f47b4-4921-4ba7-aff0-885a71f576c3.png)

### Steps To Reproduce:

1) Create a private channel route in routes/channel.php
2) Use Echo.channel() to subscribe to the channel, and it will show subscribe success.

**Comment by driesvints** [comment]
@nogamenofun98 you did not use the command I provided to initialize the project. The first commit does not reflects a new fresh Laravel install. Please recreate the project with the command I provided so all custom changes are clear. Feel free to respond again when you've done that and I'll re-open the issue.
