### ISSUE TITLE
There are no possibility to use relative path for wsHost

### ISSUE THREAD

**Issue by Spartaques** [laravel/echo#330]
Hello guys. My config for Echo is this one:
 window.Echo = new Echo({
        broadcaster: 'pusher',
        key: 'websocketkey',
        wsHost: window.location.hostname,
        wsPort: 6001,
        port: window.location.port,
        forceTLS: false,
        debug: false,
        disableStats: true,
})

But i want to use relative path for wsHost. this is because i want to use reverse proxy and internal docker network and exclude request using global network. So, when i make request to localhost, my nginx proxy it to websocket server, no need to establish connection throught global network. For now, it not work. When i use

wsHost: '/'
it not work at all.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by StaticFX** [comment]
For anyone still looking, you can use the wsPath attribute in your config
