### ISSUE TITLE
echo.ts should also export Channel and PresenceChannel

### ISSUE THREAD

**Issue by steve3d** [laravel/echo#332]
I know you guys are almost vue lovers, but I'm sure there are many laravel users are using angular, and I'm one of these.

I've been using angular with laravel for years. and recent version of angular start to enable typescript strict mode by default, So in angular app, I need to keep track of these channels, but the echo.ts didn't export the `Channel` and `PresenceChannel`, so there is no way to use this types directly. the only two way of use these two class is by setting it's type to `any` or disable strict mode at all.

but none of these two way is the best way. Losing types and disable strict mode will cause other code quality problems.

So I'm hoping if you can also export `Channel` and `PresenceChannel` class. this will make angular and other strict mode typescript uses much much more happy.

Thanks. And if you need, I can create a PR for these, because this is really a simple change. just add this line: 
```
export { Channel, PresenceChannel };
```
as the last line of `echo.ts` is enough.

**Comment by driesvints** [comment]
Heya, this seems to be a feature request. Feel free to attempt a PR if you want 👍

**Comment by bytestream** [comment]
@steve3d what was stopping you from just 
```js
import { PresenceChannel } from 'laravel-echo/src/channel'
```
