### ISSUE TITLE
Published 1.11.5 version still no PresenceChannel and Channel class in exported typings.d.ts

### ISSUE THREAD

**Issue by steve3d** [laravel/echo#335]
### Description:
I did make a pr to add `PresenceChannel` and `Channel` class to `echo.ts`'s export, but the npm published version still don't have this.

And I just tested pulling the latest code and compile by my self, these two class did exported.

Maybe some thing wrong with the compile process?

Someone please test the 1.11.5 package on npm, `laravel-echo/dist/echo.d.ts` still did not export `PresenceChannel` and `Channel`, but if you build again, these two class are exported. strange.

### Steps To Reproduce:
- `npm i  laravel/echo` to install 1.11.5, then no `PresenceChannel` and `Channel` exported in `echo.d.ts`.
 - `git clone ....` and `npm compile`, `PresenceChannel` and `Channel` did exported in `echo.d.ts`

**Comment by driesvints** [comment]
Welcoming PR's.

**Comment by steve3d** [comment]
@driesvints this can not be fixed with a pr.

if this package is published by hand, then someone must build the dist with old version of source code and published to npm.

I've tested with master and tag `1.15.1`, the build process is always right, but the npm published package is old version.

so this problem can not be fixed with pr.

**Comment by driesvints** [comment]
@steve3d did that work for you?

**Comment by steve3d** [comment]
yes 1.11.7 works， thank you！

**Comment by steve3d** [comment]
yes 1.11.7 works， thank you！
