### ISSUE TITLE
joining and leaving method isn't available in private channel

### ISSUE THREAD

**Issue by cod3rshotout** [laravel/echo#338]
I need to use `joining` and `leaving` for a private channel, so I did:

```
var channel = window.Echo.private(`room.${roomId}`)
    .joining((user) => {
        window.toastr.success(`User ${user.name} has joined the chat`);
    })
    .leaving((user) => {
        window.toastr.success(`User ${user.name} has left the chat`);
    })
```

I get this error:

>joining is not a function

This error doesn't appear when I use join, but if I use join the `listen` event doesn't work:

```
.listen('MessageSent', (e) => {
    alert('hello world');
    console.log(e);
})
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
