### ISSUE TITLE
Any plans for multi listen same event name?

### ISSUE THREAD

**Issue by kon3ko** [laravel/echo#339]
Laravel can now use Model for broadcast https://laravel.com/docs/9.x/broadcasting#model-broadcasting
ex.
```php
//\App\Models\News.php
public function broadcastOn($event)
    {
        return match ($event) {
            'updated' => [$this->user],
            default => [],
        };
    }

//news.vue
this.$echo.private('App.Models.User.' + this._.get(this.$store, 'state.auth.user.id'))
    .listen('.NewsUpdated', (e) => {
        console.log(1, e);
    });
```
Sometimes I want to use '.NewsUpdated' in multiple places.
If many places I use and cancel when I'm no longer on that page, and other places will be canceled as well.

Now I need to write condition in listen by checking from route name to solve this problem

**Comment by driesvints** [comment]
Right now we don't have any plans for this, sorry.
