### ISSUE TITLE
Useless exports, and broken IIFE

### ISSUE THREAD

**Issue by bytestream** [laravel/echo#343]
- Echo Version: 1.12.0
- Laravel Version: 9.18.0
- PHP Version: 8.1.7
- NPM Version: 8.11.0
- Node Version: 16.15.1

### Description:

In v1.11.5 the IIFE distribution file was broken by https://github.com/laravel/echo/pull/333. In my opinion, the new exports are completely useless given classes are already exported in their own right:
* https://github.com/laravel/echo/blob/master/src/channel/channel.ts
* https://github.com/laravel/echo/blob/master/src/channel/presence-channel.ts
  
They can be used without modification to the library, by simply:
```js
import { PresenceChannel } from 'laravel-echo/src/channel'
```

The changes break the IIFE distribution by exporting multiple objects. The change results in new usage:
```js
var myEcho = new Echo.default({});
```

This was highlighted in https://github.com/laravel/echo/issues/336 already, but closed as unsupported. If that's the case, then I would suggest that the IIFE distribution is removed. However, that seems unnecessary given the changes in https://github.com/laravel/echo/pull/333 are unnecessary and if they were to be reverted then the IIFE distribution would work again...

### Steps To Reproduce:

Use the `dist/echo.iife.js` file: 
```html
<script src="echo.iife.js"></script>
<script>var myEcho = new Echo({});</script>
```

```
Uncaught TypeError: Echo is not a constructor
```

**Comment by driesvints** [comment]
Right now, we're not looking into supporting IIFE anymore.

**Comment by bytestream** [comment]
@driesvints but you are happy to keep the useless exports? why don't we export all the classes in echo.ts while we're at it?

**Comment by jessarcher** [comment]
Hi @bytestream,

Appreciate this issue - #333 was a breaking change for IIFE builds and it seems a bit arbitrary to export `Channel` and `PresenceChannel`, but not any of the other classes.

On the other hand, importing the classes from `laravel-echo/src/*` seems a bit clunky. I'd prefer the packaged version to exclude the `src` directory, [as used to be the case](https://github.com/laravel/echo/pull/92), to save space and bandwidth. This seems to be a fairly common practice with libraries like Vue.

You've mentioned removing the IIFE build, but as far as I can tell, IIFE still works - it's just the usage that has unfortunately changed.

My brilliant colleague @timacdonald might have a solution that gives us everything. Stay tuned...

**Comment by timacdonald** [comment]
See: https://github.com/laravel/echo/pull/344

**Comment by bytestream** [comment]
Thanks for looking into this @jessarcher ☺️

> importing the classes from laravel-echo/src/* seems a bit clunky. I'd prefer the packaged version to exclude the src directory, https://github.com/laravel/echo/pull/92, to save space and bandwidth

I disagree with this. I, for example, use the src classes to extend the library https://github.com/supportpal/pollcast-js/blob/master/src/broadcasting/channels/channel.ts. Bandwidth would only really be saved in pulls from npm. Users shouldn't be shipping node_modules, but using something like webpack

> You've mentioned removing the IIFE build, but as far as I can tell, IIFE still works - it's just the usage that has unfortunately changed.

Correct

> See: https://github.com/laravel/echo/pull/344

Thanks @timacdonald !

**Comment by timacdonald** [comment]
No troubles at all ❤️
