### ISSUE TITLE
Bearer Token Authentication Configuration

### ISSUE THREAD

**Issue by parallels999** [laravel/echo#352]
Is there a config for use `bearer token authentication` easily?

Current:
```ts
var TOKEN='*******';
{
  broadcaster: 'pusher',
  // csrfToken: '******'
  auth: {
      headers: {
          Authorization: "Bearer " + TOKEN
      },
  },
  userAuthentication: {
      headers: {
          Authorization: "Bearer " + TOKEN
      },
  },
  ////
}
```
Shorter example:
```ts
{
  broadcaster: 'pusher',
  // csrfToken: '******'
  bearerToken: '*******',
  ////
}
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by parallels999** [comment]
@driesvints 
> try one of the following channels

Already did that, it is not a bug, or a problem

**Comment by driesvints** [comment]
@parallels999 this isn't the place to ask those questions, please see our issue templates.

**Comment by parallels999** [comment]
@driesvints if i make a PR for this, could you review it? please

**Comment by parallels999** [comment]
> this isn't the place to ask those questions, please see our issue templates.

For the records:
https://github.com/laravel/echo/blob/98bc978dae394fe7dfc33f4a97c74f52ab5a4646/.github/ISSUE_TEMPLATE/2_Feature_request.md?plain=1#L3
