### ISSUE TITLE
Break Google API it's a BUG, right?

### ISSUE THREAD

**Issue by allanmcarvalho** [laravel/echo#355]
- Echo Version: 1.14.0
- Laravel Version: 9.27.0
- PHP Version: 8.1.1
- NPM Version: 8.11.0
- Node Version: 16.16.0

### Description:
I will try very directly!!! Isn't a QUESTION on #354! It's a BUG!
I became thinking that @driesvints have some problems with me! I try and try communicate some problems of community and he appears that don't even bother to read and REALLY understand the problem...

I am saying here... Laravel ECHO IS BROKING a GOOGLE API, because it put trash on every request header, even when not necessary!!!! Is this not a bug? Really????

with postures like yours, @driesvints, I'm losing faith in the open source community!  It's a superiority syndrome!

**Comment by driesvints** [comment]
We aren't free support. That's not what open source means. Try a support channel first and no-one can help you out, post a new issue with a repo that reproduces the problem.

**Comment by parallels999** [comment]
> I became thinking that driesvints have some problems with me

Not, it is the same with everyone that is not from the laravel group, look https://github.com/laravel/echo/issues/352#issuecomment-1228503911

You could make a PR with the fix for that, but the answer probably the answer will be the same as this

>I am closing this pull request because it lacks sufficient explanation, tests, or both. It is difficult for us to merge pull requests without these things because the change may introduce breaking changes to the framework.
>
>Feel free to re-submit your change with a thorough explanation of the feature and tests - integration tests are preferred over unit tests. Please include it's benefit to end users; the reasons it does not break any existing features; how it makes building web applications easier, etc.
>
>Thanks!

They don't read anything, but you could give a try
