### ISSUE TITLE
TS2564: Property 'namespace' has no initializer and is not definitely assigned in the constructor.

### ISSUE THREAD

**Issue by MiloTischler** [laravel/echo#357]
- Echo Version: 1.14.0
- NPM Version: 6.14.17
- Node Version:v14.20.0

### Description:

- typescript: 4.0.8
- eslint: 6.8.0

I am getting this error:

```
node_modules/laravel-echo/src/util/event-formatter.ts(8,5):
TS2564: Property 'namespace' has no initializer and is not definitely assigned in the constructor.
```

and i think it could be solved by setting namespace to an inital value, like `false`

**Comment by driesvints** [comment]
Can you send in a PR? Thanks
