### ISSUE TITLE
Laravel echo and pusher auth error on ubuntu 22.04

### ISSUE THREAD

**Issue by halimsupranata** [laravel/echo#358]
- Echo Version: 1.14.0
- Laravel Version: ^9.0.0
- PHP Version: 8.1.11
- NPM Version: 6.14.4
- Node Version: 10.19.0
- Ubuntu 22.04.1

### Description:

when I call
`window.Echo.connector.pusher.config.auth.headers["Authorization"] = "Bearer XXXXX"
`then it will error
`TypeError: Cannot read properties of undefined (reading 'headers')
`
This is the result with ubuntu 22.04 when I check, there is no auth in the config
![result](https://user-images.githubusercontent.com/15225581/195744883-8775dd51-dd65-4b11-b003-8ad55ebe2cc9.png)

This is the result with ubuntu 20.04 when I check, there is auth, and it works
![result success](https://user-images.githubusercontent.com/15225581/195744886-d977cc8f-456f-4795-b30a-a67adfc399aa.png)

**BUT IT WORKS ON ubuntu 20.04.5
 with exact same NODE, NPM, exact same PHP, exact same echo version, exact same code(I clone it)**
![22 04](https://user-images.githubusercontent.com/15225581/195744834-9616f569-feaf-4054-a42b-2d231cc88556.png)
![20 04](https://user-images.githubusercontent.com/15225581/195744840-d9c52d86-445e-419e-8121-8f4d73409188.png)

### Steps To Reproduce:

Use ubuntu 22.04, call `window.Echo.connector.pusher.config.auth.headers["Authorization"] = "Bearer XXXXX"
`then it will error

It sounds doesn't make sense, because it does nothing with OS, but it really happens

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
