### ISSUE TITLE
Laravel Echo is not subscribing to private channel

### ISSUE THREAD

**Issue by NK0D1NG** [laravel/echo#360]
- Echo Version: 1.14.1
- Laravel Version: v9.33.0
- PHP Version: 8.1.12
- NPM Version: 8.19.2
- Node Version: v16.18.0

### Description:
Laravel Echo is not subscribing to a private channel. After instantiating and authenticating Laravel Echo the EventListener ('listen'-Method) never gets called. In the websocket connection is no subscription message and Soketi does not receive any subscription message. Using a public channel works as expected.

### Steps To Reproduce:

1. Setup Laravel Broadcasting with Soketi according to the docs
2. Generate Event, Listener and a Private Channel
3. Instantiate Laravel Echo
4. Listen to an event on that channel
5. Watch Browser Network Tab

Frontend Code for 3.:
```
import Echo from 'laravel-echo';

const echo = ref()
const channelName = 'c89e8e0f-d86e-4b5b-887c-3ba24fcc4637'

function setupEcho() {
    const token = useCookie('XSRF-TOKEN').value
    const config = useRuntimeConfig()
    if (!echo.value) {
        echo.value = new Echo({
        authorizer: (channel, options) => {
        return {
            authorize: (socketId, callback) => {
                const response = $fetch(config.baseURL + '/broadcasting/auth', {
                    async onRequest({ request, options }) {
                    options.method = 'post'
                    options.body = {
                        socket_id: socketId,
                        channel_name: channel.name
                    }
                    options.headers = {'X-XSRF-TOKEN': token,
                    'Accept': 'application/json',
                    },
                    options.credentials = 'include'
                    },
                    async onResponseError({ request, response, options }) {
                        console.log(response + response.status)
                    },
                })
                console.log(response)
            }
        };
        },
        broadcaster: 'pusher',
        key: 'app-key',
        cluster: 'mt1',
        wsHost: 'localhost',
        wsPort: 6001,
        forceTLS: false,
        disableStats: true,
        auth: {
            headers: {'X-XSRF-TOKEN': token,
                       'Accept': 'application/json',
            },
        },
        enabledTransports: ['ws', 'wss'],
    });
    }
}
```

Frontend Code for 4.:
```
function joinRoomChat() {
    console.log('Joining room: ' + channelName)
    echo.value.private(channelName)
    .listen('.client.stream.started', (e) => {
        console.log('I never get called!')
        console.log(e)
    });
}
```

Examples for 5.:
browser requests:
[![grafik.png](https://i.postimg.cc/Zq0W40jg/grafik.png)](https://postimg.cc/QBG8q82k)

POST-data sent within the request to broadcasting/auth:
```
{"socket_id":"2329902672.3158557083","channel_name":"private-room.c89e8e0f-d86e-4b5b-887c-3ba24fcc4637"}
```

The response from the auth-Request:
```
{"auth":"app-key:ad67d31af255737d954c8e1bf67b7db9e3e44494bd25b7f307d9f270ea7f2b3d"}
```
This is the request/response-payload of the first (and only) websocket connection Laravel Echo creates:
[![grafik.png](https://i.postimg.cc/x8VGXL4q/grafik.png)](https://postimg.cc/7GXJcJDy)

The actual callback function inside the `listen`-handler never gets called from Laravel Echo. There is just nothing in the browser console. It seems like Laravel Echo does not even send a subscribe message when using private channels.

If using the same event with a public channel Laravel Echo actually subscribes and I get the event data:
![grafik](https://user-images.githubusercontent.com/88783636/202142235-89e2d36b-c2d8-427d-9128-6e0d12b79f41.png)

I just made a public 'test' channel on the backend and changed the event to broadcast on that channel. This is how I changed the Frontend Code:
```
function joinRoomChat() {
    echo.value.channel('test')
    .listen('.client.stream.started', (e) => {
        console.log('I never get called!')
        console.log(e)
    });
}
```

I am not sure if there is a bug in Laravel Echo or maybe it is related to Soketi? Nevertheless I had the same problems using the laravel-websocket package, too so I think this bug is Laravel Echo related.

### The frontend built with NuxtJS:
https://github.com/NK0D1NG/laravel-broadcasting-fe
### The backend build with Laravel:
https://github.com/NK0D1NG/laravel-broadcasting-be

## Related topics
https://laracasts.com/discuss/channels/laravel/laravel-echo-not-listening-to-events-using-it-with-laravel-homestead-could-it-be-a-compatibility-issue-with-vue-3

I also posted a lot of information about the problem in this post on Laracast (including more Laravel-specific backend code):
https://laracasts.com/discuss/channels/laravel/event-listener-never-gets-called-even-if-the-event-gets-fired?page=1&replyId=849115

**Comment by jessarcher** [comment]
Hi @NK0D1NG, I am unable to replicate this issue.

Your example code seemed quite complicated so I just set up a minimal example to confirm that I can subscribe to private channels.

I spun up a Soketi server with Docker, per their docs:

```sh
docker run -p 6001:6001 -p 9601:9601 quay.io/soketi/soketi:1.4-16-debian
```

I set up a fresh Laravel install with Laravel Breeze's Vue stack to scaffold out auth views.

I installed the Pusher and Echo packages:

```sh
composer require pusher/pusher-php-server
npm install --save-dev laravel-echo pusher-js
```

I configured my `.env` as follows:

```env
BROADCAST_DRIVER=pusher
PUSHER_APP_ID=app-id
PUSHER_APP_KEY=app-key
PUSHER_APP_SECRET=app-secret
PUSHER_HOST=127.0.0.1
PUSHER_PORT=6001
PUSHER_SCHEME=http
PUSHER_APP_CLUSTER=mt1
```

I uncommented the default Echo configuration in `resources/js/bootstrap.js`:

```js
import Echo from 'laravel-echo';

import Pusher from 'pusher-js';

window.Pusher = Pusher;

window.Echo = new Echo({
    broadcaster: 'pusher',
    key: import.meta.env.VITE_PUSHER_APP_KEY,
    wsHost: import.meta.env.VITE_PUSHER_HOST ? import.meta.env.VITE_PUSHER_HOST : `ws-${import.meta.env.VITE_PUSHER_APP_CLUSTER}.pusher.com`,
    wsPort: import.meta.env.VITE_PUSHER_PORT ?? 80,
    wssPort: import.meta.env.VITE_PUSHER_PORT ?? 443,
    forceTLS: (import.meta.env.VITE_PUSHER_SCHEME ?? 'https') === 'https',
    enabledTransports: ['ws', 'wss'],
});
```

I then logged into the Laravel app and observed Echo connecting to Soketi:

![image](https://user-images.githubusercontent.com/4977161/202589311-f7acfb30-7ba8-43e2-8ee0-2233bc85ec04.png)

I then uncommented `App\Providers\BroadcastServiceProvider::class` in `config.app` and set up a channel in `routes/channels.php`:

```php
Broadcast::channel('foo-channel', fn () => true);
```

I then created an event with `artisan make:event FooEvent` and updated it to implement `ShouldBroadcast`. I updated the constructor  to accept a `$message` and updated the `broadcastOn` method to use the `foo` channel:

```php
class FooEvent implements ShouldBroadcast
{
    use Dispatchable, InteractsWithSockets, SerializesModels;

    public function __construct(public string $message)
    {
        //
    }

    public function broadcastOn()
    {
        return new PrivateChannel('foo-channel');
    }
}
```

In `Dashboard.vue` I subscribed to the event on the private channel:
 
```js
Echo.private('foo-channel')
    .listen('FooEvent', (e) => {
        console.log(e);
    });
```

And observed that Echo made the auth request:

![image](https://user-images.githubusercontent.com/4977161/202589766-c1eba671-c1a7-4aad-9bd2-a92ccfcac827.png)

I then used Laravel tinker to dispatch the event:

![image](https://user-images.githubusercontent.com/4977161/202589951-bf329fbb-352c-4f8d-a2c3-c3d8365e0a87.png)

And saw it come through in the console:

![image](https://user-images.githubusercontent.com/4977161/202589983-fc5b3950-dfbb-46ba-b366-f9e5b8f84a9f.png)

Are you able to confirm whether the issue exists for you with a minimal setup like this?

**Comment by NK0D1NG** [comment]
Hey @jessarcher 
thanks for investigating into this. The only difference to my setup could be the custom auth guard I am using:

from config/auth.php:
```
    'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],
        'vcs' => [
            'driver' => 'session',
            'provider' => 'clients',
        ],
    ],

    'providers' => [
        'users' => [
            'driver' => 'eloquent',
            'model' => App\Models\User::class,
        ],

        'clients' => [
            'driver' => 'eloquent',
            'model' => App\Models\Client::class,
        ],
    ],
```
from routes/channels.php:
```
Broadcast::channel('room.{ruuid}', function ($client, $ruuid) {
    Log::info('Broadcasting.Channel: ' . $ruuid);
    return $client->room_uuid == $ruuid;
}, ['guards' => ['vcs']]);
```

My 
app/Providers/BroadcastServiceProvider.php:
```
<?php

namespace App\Providers;

use Illuminate\Support\Facades\Broadcast;
use Illuminate\Support\ServiceProvider;

class BroadcastServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        Broadcast::routes(['middleware' => 'web', 'guards' => 'vcs']);

        require base_path('routes/channels.php');
    }
}

```

This is also the reason why my Echo setup seems complicated. I am also using Laravel Sanctum with an external Vue SPA which authenticates using Laravel's default session driver as you can see. Everything is set up like described in the official docs and not the first time I am doing it like this. Because Laravel Sanctum requires the X-XSRF-TOKEN to be set and Laravel Echo did not send this token automatically I added it by myself using the custom authorizer. As well as the application/json header. The Vue SPA is a different repository/project. Authenticating using the custom guard works just fine (for normal API routes and for the channels as well as you can see in the images in my original post). Because I have no monorepo I wasn't able to setup a minimal example for this whole setup yet.

So maybe Echo has a problem with the custom guard?

Can you confirm a subscription message inside the websocket connection? What do your request/responses in the websocket connection look like? Is there a subscription/subscription succeeded message? Can you confirm it works in your minimal example using a custom guard and Laravel Sanctum? I am using just another Eloquent model like:

```
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Laravel\Sanctum\HasApiTokens;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Spatie\Permission\Traits\HasRoles;
use App\Traits\Uuids;

class Client extends Authenticatable
{
    use HasFactory, HasApiTokens, HasRoles, Uuids;

    protected $guard_name = "vcs";

    public function room()
    {
        return $this->belongsTo(Room::class, 'room_uuid', 'uuid');
    }
}

```

**Comment by NK0D1NG** [comment]
By the way: I am not using axios - I am using the fetch API (The frontend is developed with NuxtJS which uses ohmyfetch as a fetch API dependency).

**Comment by NK0D1NG** [comment]
@driesvints @jessarcher 
I provided two demo repositories (links in the original post). They should work out of the box after installing the dependencies. Please follow the README of the Laravel Backend Repo to do the setup and create a first user with a custom guard. Even with this simplified setup Laravel Echo does not subscribe to the private channel.

For the frontend just use the newly created user (model is called 'client') to login. Then click on the Join Room Chat button which should call the `listen`-method - but the callback never gets called and there is no subscription..

**Comment by NK0D1NG** [comment]
I was finally able to reproduce the issue and solve it. It is important to call the callback on the custom authorizer:
```
function setupEcho() {
    const token = useCookie('XSRF-TOKEN').value
    const config = useRuntimeConfig()
    channelName.value = 'room.' + roomsStore.currentRoom.roomUuid
    console.log('Channel Name: ' + channelName)
    if (!echo.value) {
        echo.value = new Echo({
        authorizer: (channel, options) => {
        return {
            authorize: (socketId, callback) => {
                const request = $fetch(config.baseURL + '/broadcasting/auth', {
                    async onRequest({ request, options }) {
                    options.method = 'post'
                    options.body = {
                        socket_id: socketId,
                        channel_name: channel.name
                    }
                    options.headers = {'X-XSRF-TOKEN': token,
                    'Accept': 'application/json',
                    },
                    options.credentials = 'include'
                    },
                })
                request.then((response) => {
                    console.log(response)
                    callback(null, response)
                })
            }
        };
        },
        broadcaster: 'pusher',
        key: 'app-key',
        cluster: 'mt1',
        wsHost: 'localhost',
        wsPort: 6001,
        forceTLS: false,
        disableStats: true,
        encrypted: true,
        auth: {
            headers: {'X-XSRF-TOKEN': token,
                       'Accept': 'application/json',
            },
        },
        enabledTransports: ['ws', 'wss'],
    });
    }
}
```

**This part is the important one:**
```
                request.then((response) => {
                    console.log(response)
                    callback(null, response)
                })
```

I am not sure what callback is used internally by Laravel Echo but it is obligatory for the subscription of private/presence channels to work. All examples in the docs use axios so I had to change some code to work with the fetch API (which is used by the ohmyfetch library). After calling the callback (with a null value as first parameter which seems a bit strange but is also mentioned in the Laravel Docs) the subscription works and I get the event data:

![grafik](https://user-images.githubusercontent.com/88783636/203098123-700bfff5-7ce3-4fb2-8018-9978441a744b.png)

This issue was not easy to debug, because the same setup works perfectly fine with public channels (including the subscription!) and there are absolutely no errors in the console when trying the same with private channels.

The issue can be closed.

**Comment by Stetzon** [comment]
Laravel 11: For those using a simple Sanctum/Echo/Reverb setup, you can try the following:

```php
// config/cors.php

'paths' => ['api/*', 'sanctum/csrf-cookie', 
    '/broadcasting/auth' // add me
],
```

```php
// routes/channels.php

use Illuminate\Support\Facades\Broadcast;

Broadcast::routes(['middleware' => ['api', 'auth:sanctum']]);
```

```js
// main.js (of your SPA)

import Echo from 'laravel-echo';
import Pusher from 'pusher-js';
import axios from 'axios';
window.Pusher = Pusher;

window.Echo = new Echo({
    broadcaster: 'reverb',
    key: import.meta.env.VITE_REVERB_APP_KEY,
    wsHost: import.meta.env.VITE_REVERB_HOST,
    wsPort: import.meta.env.VITE_REVERB_PORT ?? 80,
    wssPort: import.meta.env.VITE_REVERB_PORT ?? 443,
    forceTLS: (import.meta.env.VITE_REVERB_SCHEME ?? 'https') === 'https',
    enabledTransports: ['ws', 'wss'],
    authorizer: (channel, options) => ({
        authorize: (socketId, callback) => {
            axios.post(`${import.meta.env.VITE_API_URL}/broadcasting/auth`, {
                socket_id: socketId,
                channel_name: channel.name,
            }, {
                withCredentials: true, // this is
                withXSRFToken: true, // important part
            })
                .then(response => {
                    callback(null, response.data);
                })
                .catch(error => {
                    callback(error);
                });
        },
    }),
});
```
The [default csrf configuration](https://github.com/laravel/echo/blob/9eb317b05888471aa6888ccda1235c3a2eee3cd3/src/connector/connector.ts#L63) for Echo does not work out of the box with sanctum, as it tries to find the csrf token on the window object or in the DOM.  We want to configure axios to be able to grab it from the cookie like it does on every other API request.

Since the `/broadcasting/auth` route is now automatically published, the `Broadcast::routes()` helper was removed from the docs.  Curiously, the custom authorizer docs were removed as well.  See change [here](https://github.com/laravel/docs/commit/48faaaff53e6cb72a10fb8ce94e4fabfa4657ee6#diff-5d10402d75abaf780e0b08af74845410dd121c97e8a0a8776f546c7a119a7b82L582).

[This SO post](https://stackoverflow.com/a/78667429/3711834) helped me get here.

**Comment by mandatoryGithubUser** [comment]
> Laravel 11: For those using a simple Sanctum/Echo/Reverb setup, you can try the following:
> 
> ```
> // config/cors.php
> 
> 'paths' => ['api/*', 'sanctum/csrf-cookie', 
>     '/broadcasting/auth' // add me
> ],
> ```
> 
> ```
> // routes/channels.php
> 
> use Illuminate\Support\Facades\Broadcast;
> 
> Broadcast::routes(['middleware' => ['api', 'auth:sanctum']]);
> ```
> 
> ```js
> // main.js (of your SPA)
> 
> import Echo from 'laravel-echo';
> import Pusher from 'pusher-js';
> import axios from 'axios';
> window.Pusher = Pusher;
> 
> window.Echo = new Echo({
>     broadcaster: 'reverb',
>     key: import.meta.env.VITE_REVERB_APP_KEY,
>     wsHost: import.meta.env.VITE_REVERB_HOST,
>     wsPort: import.meta.env.VITE_REVERB_PORT ?? 80,
>     wssPort: import.meta.env.VITE_REVERB_PORT ?? 443,
>     forceTLS: (import.meta.env.VITE_REVERB_SCHEME ?? 'https') === 'https',
>     enabledTransports: ['ws', 'wss'],
>     authorizer: (channel, options) => ({
>         authorize: (socketId, callback) => {
>             axios.post(`${import.meta.env.VITE_API_URL}/broadcasting/auth`, {
>                 socket_id: socketId,
>                 channel_name: channel.name,
>             }, {
>                 withCredentials: true, // this is
>                 withXSRFToken: true, // important part
>             })
>                 .then(response => {
>                     callback(null, response.data);
>                 })
>                 .catch(error => {
>                     callback(error);
>                 });
>         },
>     }),
> });
> ```
> 
> The [default csrf configuration](https://github.com/laravel/echo/blob/9eb317b05888471aa6888ccda1235c3a2eee3cd3/src/connector/connector.ts#L63) for Echo does not work out of the box with sanctum, as it tries to find the csrf token on the window object or in the DOM. We want to configure axios to be able to grab it from the cookie like it does on every other API request.
> 
> Since the `/broadcasting/auth` route is now automatically published, the `Broadcast::routes()` helper was removed from the docs. Curiously, the custom authorizer docs were removed as well. See change [here](https://github.com/laravel/docs/commit/48faaaff53e6cb72a10fb8ce94e4fabfa4657ee6#diff-5d10402d75abaf780e0b08af74845410dd121c97e8a0a8776f546c7a119a7b82L582).
> 
> [This SO post](https://stackoverflow.com/a/78667429/3711834) helped me get here.

This comment is a life saver. Nowhere in the Laravel Echo  did I see the CSRF token part, I was losing my mind with this error

**Comment by Erutan409** [comment]
> Laravel 11: For those using a simple Sanctum/Echo/Reverb setup, you can try the following:
> 
> ```
> // config/cors.php
> 
> 'paths' => ['api/*', 'sanctum/csrf-cookie', 
>     '/broadcasting/auth' // add me
> ],
> ```
> 
> ```
> // routes/channels.php
> 
> use Illuminate\Support\Facades\Broadcast;
> 
> Broadcast::routes(['middleware' => ['api', 'auth:sanctum']]);
> ```
> 
> ```js
> // main.js (of your SPA)
> 
> import Echo from 'laravel-echo';
> import Pusher from 'pusher-js';
> import axios from 'axios';
> window.Pusher = Pusher;
> 
> window.Echo = new Echo({
>     broadcaster: 'reverb',
>     key: import.meta.env.VITE_REVERB_APP_KEY,
>     wsHost: import.meta.env.VITE_REVERB_HOST,
>     wsPort: import.meta.env.VITE_REVERB_PORT ?? 80,
>     wssPort: import.meta.env.VITE_REVERB_PORT ?? 443,
>     forceTLS: (import.meta.env.VITE_REVERB_SCHEME ?? 'https') === 'https',
>     enabledTransports: ['ws', 'wss'],
>     authorizer: (channel, options) => ({
>         authorize: (socketId, callback) => {
>             axios.post(`${import.meta.env.VITE_API_URL}/broadcasting/auth`, {
>                 socket_id: socketId,
>                 channel_name: channel.name,
>             }, {
>                 withCredentials: true, // this is
>                 withXSRFToken: true, // important part
>             })
>                 .then(response => {
>                     callback(null, response.data);
>                 })
>                 .catch(error => {
>                     callback(error);
>                 });
>         },
>     }),
> });
> ```
> 
> The [default csrf configuration](https://github.com/laravel/echo/blob/9eb317b05888471aa6888ccda1235c3a2eee3cd3/src/connector/connector.ts#L63) for Echo does not work out of the box with sanctum, as it tries to find the csrf token on the window object or in the DOM. We want to configure axios to be able to grab it from the cookie like it does on every other API request.
> 
> Since the `/broadcasting/auth` route is now automatically published, the `Broadcast::routes()` helper was removed from the docs. Curiously, the custom authorizer docs were removed as well. See change [here](https://github.com/laravel/docs/commit/48faaaff53e6cb72a10fb8ce94e4fabfa4657ee6#diff-5d10402d75abaf780e0b08af74845410dd121c97e8a0a8776f546c7a119a7b82L582).
> 
> [This SO post](https://stackoverflow.com/a/78667429/3711834) helped me get here.

I have to agree with @mandatoryGithubUser that this was immensely helpful. A couple of things to add, though:

This is my current implementation of the echo instance, using the recommend configuration strategy based on [pusher's official documentation](https://github.com/pusher/pusher-js/blob/4306f011b866e76650830d1206b2093cc1f249c0/README.md#channelauthorization-object), as the older method has been [deprecated](https://github.com/pusher/pusher-js/blob/37b057c45c403af27c79303123344c42f6da6a25/src/core/options.ts#L17-L20):

```javascript
const echo = new Echo({
  broadcaster: 'reverb',
  key: import.meta.env.VITE_REVERB_APP_KEY,
  wsHost: import.meta.env.VITE_REVERB_HOST,
  wsPort: import.meta.env.VITE_REVERB_PORT ?? 80,
  wssPort: import.meta.env.VITE_REVERB_PORT ?? 443,
  forceTLS: (import.meta.env.VITE_REVERB_SCHEME ?? 'https') === 'https',
  enabledTransports: ['ws', 'wss'],
  Pusher,
  withoutInterceptors: true,
  /************************** New way of configuring (see aforementioned Pusher doc link) **************************/
  channelAuthorization: {
    endpoint: '/broadcasting/auth',
    headersProvider: () => {

      // using a VueJS ref for this value for when the user is authenticated, since I store my echo instance in a pinia store
      if (cookie.value) {
        return {'Authorization': `Bearer ${cookie.value}`};
      }

    }
  } as ChannelAuthorizationOptions
});
```

And similar to previously mentioned, I'm configuring my `channels.php` routes file as follows:

```php
Broadcast::routes(['middleware' => ['api', 'auth:sanctum']]);
```

As of v8.16.0 (https://github.com/laravel/framework/commit/acb4b77adc6e257e132e3b036abe1ec88885cfb7), passing in the CSRF token **SHOULD NOT** be necessary; and isn't required in my setup.

**Comment by by-artemis** [comment]
Hello @driesvints  @Stetzon @jessarcher @Erutan409 @NK0D1NG 
I know this is already closed but I am struggling with similar problem with a few difference's from OP's original issue. Mine is I have a separate repo for backend -- Laravel 11 (api) and separate for frontend -- Next TS / React (client). Here's the full details of my issue: https://stackoverflow.com/questions/79363315/laravel-echo-broadcasting-auth-error-on-laravel-11-next-typescript

I think I have read and tried most of the solutions on the internet to no avail. I'm helpless.
