### ISSUE TITLE
#encryptedPrivate does not work with NullConnector

### ISSUE THREAD

**Issue by luniki** [laravel/echo#367]
- Echo Version: 1.14.2
- Laravel Version: na
- PHP Version: na
- NPM Version: na
- Node Version: na

### Description:

Calling `echo.encryptedPrivate(…)` while using a NullConnector results in an error:

```
Uncaught TypeError: this.connector.encryptedPrivateChannel is not a function
```

This is caused by line https://github.com/laravel/echo/blob/master/src/echo.ts#L107 as a NullConnector does not have an  `encryptedPrivateChannel` function.

**Comment by driesvints** [comment]
Thanks, you sent in a PR so let's see how it goes.
