### ISSUE TITLE
PresenceChannel interface missing 'Whisper' method

### ISSUE THREAD

**Issue by DellanX** [laravel/echo#371]
- Echo Version: 1.15.0
- Laravel Version: 9.19.0
- PHP Version: 8.17
- NPM Version: 8.12.2
- Node Version: 16.15.1

### Description:

The 'Whisper' method is not included in the type for PresenceChannel. Upon looking into the interface for PresenceChannel in laravel-echo, I can see that indeed, there isn't an interface method there.
### Steps To Reproduce:

In TypeScript, create an Echo instance 'Echo'
typeup:
Echo.join('room').whisper('test, () => {}).

You'll see an error as 'whisper' is not included in type 'PresenceChannel'

**Comment by DellanX** [comment]
Should note: Adding the following line to laravel-echo/src/channel/presence-channel.ts did resolve the issue in my case
I am not familiar with the internals of this codebase enough to create a PR for this yet.

```js
whisper(eventName: string, data: any): PresenceChannel;
```

**Comment by driesvints** [comment]
I'm currently not sure why this method is not added to this interface. Feel free to attempt a PR to add it. It simply requires to edit this file: https://github.com/laravel/echo/blob/master/src/channel/presence-channel.ts
