### ISSUE TITLE
[Bug] PresenceChannel interface missing 'Whisper' method

### ISSUE THREAD

**Issue by DellanX** [laravel/echo#374]
- Echo Version: 1.15.0
- Laravel Version: 10.1.5
- PHP Version: 8.17
- NPM Version: 8.12.2
- Node Version: 16.15.1

### Description:
Reopening #371, as this issue both unresolved and I do not know the internals of this package to solve. (Fix was attempted in #372)

The 'Whisper' method is not included in the type for PresenceChannel. Upon looking into the interface for PresenceChannel in laravel-echo, I can see that indeed, there isn't an interface method there.

### Steps To Reproduce:

In TypeScript, create an Echo instance 'Echo'
typeup:
Echo.join('room').whisper('test, () => {}).

You'll see an IDE error as 'whisper' is not included in type 'PresenceChannel'

**Comment by driesvints** [comment]
Like I said in the previous issue: we're open to PRs for this, thanks.
