### ISSUE TITLE
Always got pusher ouput while using socket.io

### ISSUE THREAD

**Issue by JanWeskamp** [laravel/echo#376]
- Echo Version: 1.6.3
- Laravel Version: 10.5.1
- PHP Version:  8.2.4 
- NPM Version: 8.17.0
- Node Version: 18.7.0

### Description:
I always got the pusher key notification but everything showing socket.io

### Steps To Reproduce:
echo.js
`import Echo from "laravel-echo"

window.io = require('socket.io-client');

if (typeof io !== 'undefined' && typeof APP_URL !== 'undefined') {
    let host = '';
    console.log(APP_ECHO_PORT);

    if (APP_ECHO_PORT != null && APP_ECHO_PORT != 0) {
        host = APP_URL + ':' + APP_ECHO_PORT;
    } else {
        host = APP_URL;
    }
    console.log(host);

    window.Echo = new Echo({
        broadcaster: 'socket.io',
        host: host,
        transports: ['websocket', 'polling', 'flashsocket']
    });
    console.log(window.Echo);
}`

Output:
`Echo {options: {…}, connector: SocketIoConnector}
connector
: 
SocketIoConnector {_defaultOptions: {…}, options: {…}, socket: Socket, channels: {…}}
options
: 
{broadcaster: 'socket.io', host: 'https://dbd-icon-website.test:43538', transports: Array(3)}
[[Prototype]]
: 
Object`

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
