### ISSUE TITLE
Not subscribing to Echo when you open SPA as PWA from Homescreen

### ISSUE THREAD

**Issue by renege** [laravel/echo#379]
### Echo Version

1.15.0

### Laravel Version

10.9.0

### PHP Version

8.2

### NPM Version

8.55

### Description

When I develop a Single Page Application with Laravel and Vue.js 3 and place this on the homescreen of both iOS and Android, it works differently when you run it from the browser regarding notifications.

If you run the SPA in the normal browser of the device and the authenticated User receives a Notification, it shows the notification. This works. When opened from Homesreen it doesn't.

I checked Pusher and connection is established, but it doesn't subscribe.. So it doesn't receive notifications of course. This only occurs when you open it from a homescreen on both iOS and Android.

### Steps To Reproduce

Make a SPA with Notifications.

Set between the `head`-tags:
`<meta name="apple-mobile-web-app-capable" content="yes"> `

Send a Push Notification to the User (`$user->notifiy()`)

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by renege** [comment]
@driesvints it is definitely a bug.

**Comment by renege** [comment]
@driesvints Why? Echo was intended for handling subscribing to Broadcasting events and that is not working when you open in the homescreen? Then it's a bug, right? Because it works when you are in the normal browser.
