### ISSUE TITLE
All the names of the events must be prefixed with a dot 

### ISSUE THREAD

**Issue by nablidev** [laravel/echo#380]
### Echo Version

1.15.1

### Laravel Version

10.13.0

### PHP Version

8.2.0

### NPM Version

8.19.2

### Database Driver & Version

SQLite version 3.39.4

### Socket.io Version

socket.io: ^4.6.2 

### Pusher.js Version

pusher-js: ^8.0.2

### Pusher-php-server Version

pusher-php-server: 7.2.3

### Description

I am not sure if this is a **bug** or a **documentation** issue, or if I am missing something

but, in my case, I must prefix all the names of my events with a dot `.` in order for **Laravel Echo** to work. 

Like for example if I have an event named `BooksFetchedEvent` that broadcasts on a public `Channel('books')` then listening to this event with **Laravel Echo** works for me only when I **prefix** the event's name with a dot `.` like the following:

```js

window.Echo.channel('books')
    .listen('.BooksFetchedEvent', (event) => {
        console.log('event received');
    });

```

This also has the same effect on **Livewire**'s (v 2.12.3) listeners that use the **Laravel Echo**: their events must also be prefixed with a dot `.` otherwise they will not work. Like the following:

```php

    protected $listeners = ['echo:books,.BooksFetchedEvent' => 'booksUpdated'];

```

However, neither the Laravel's [documentation](https://laravel.com/docs/master/broadcasting#listening-for-event-broadcasts) section about **Laravel Echo** shows a dot `.` prefixed before the event's name.

```js

Echo.private(`orders.${orderId}`)
    .listen('OrderShipmentStatusUpdated', (e) => {
        console.log(e.order);
    });

```

Nor the Livewire's  [documentation](https://laravel-livewire.com/docs/2.x/laravel-echo#listeners) section about **Laravel Echo** event listeners shows a dot `.` prefixed before the event's name.

```php

class OrderTracker extends Component
{
    public $showNewOrderNotification = false;
 
    // Special Syntax: ['echo:{channel},{event}' => '{method}']
    protected $listeners = ['echo:orders,OrderShipped' => 'notifyNewOrder'];
 
    public function notifyNewOrder()
    {
        $this->showNewOrderNotification = true;
    }
}

```

### Steps To Reproduce

Laravel Echo

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
