### ISSUE TITLE
Connection fails in Chrome, works just fine in FF

### ISSUE THREAD

**Issue by lee-van-oetz** [laravel/echo#385]
### Echo Version

1.15.3

### Laravel Version

-

### PHP Version

-

### NPM Version

8.19.2

### Description

In the context of vite vue2 app, using laravel echo to connect to laravel-websockets server. Connection is established successfully from postman, also works in the app context from Firefox, example request:
```
GET /app/<app-key>?protocol=7&client=js&version=8.3.0&flash=false HTTP/1.1
Host: <domain>:6062
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/118.0
Accept: */*
Accept-Language: cs,sk;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate, br
Sec-WebSocket-Version: 13
Origin: https://<origin-domain>
Sec-WebSocket-Extensions: permessage-deflate
Sec-WebSocket-Key: psO9n1xZyp02kVhkagogbw==
Connection: keep-alive, Upgrade
Cookie: _ga=GA1.1.497557704.1683188777; _ga_2CVELC1K35=GS1.1.1683188777.1.0.1683188788.0.0.0
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: websocket
Sec-Fetch-Site: same-site
Pragma: no-cache
Cache-Control: no-cache
Upgrade: websocket
```
 and response headers from Firefox:
 ```
 HTTP/1.1 101 Switching Protocols
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Accept: SyJjS6kn3SF9ZH1Mu3lZane0BLU=
X-Powered-By: Ratchet/0.4.4
```
However, in Chrome I only get 
![image](https://github.com/laravel/echo/assets/7560923/22f5e552-254e-4d86-b952-c1effbb6b813)

This worked fine even in Chrome before I switched to from http/ws to https/wss. Not sure whether the problem is in echo itself, but I currently think it's possible.

### Steps To Reproduce

Use laravel-echo to connect to a TLS-secured WS server from Chrome.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
