### ISSUE TITLE
Different Channels with same listener issue

### ISSUE THREAD

**Issue by JeramyNS** [laravel/echo#39]
Something I stumbled upon by accident when experimenting with laravel echo.

If two completely different channels are setup, but they both have the same listener, then both callbacks will fire no matter which channel you post it on. However if you post in on a channel that is not called on the page then there is no issue.

For example, say I fire the event "MessageSent" on the channel "testChannel" with the following code:
```
Echo.channel('testChannel').listen('MessageSent', function (data) {
    console.log('test channel fired');
    console.log(data);
});
Echo.channel('otherChannel').listen('MessageSent', function (data) {
    console.log('other channel fired');
    console.log(data);
});
```
The output in the console will be:
```
test channel fired
Object {data: Array[3]}
other channel fired
Object {data: Array[3]}
```

Please note that I am using public channels with socket.io via Redis. I haven't tried to replicate it on anything else.

Sorry, normally would post a bit more info but it's home time ;) 
I can come back tomorrow with more details if needed.

**Comment by tlaverdure** [comment]
Good find. Should be fixed soon.
