### ISSUE TITLE
Fatal error when using channel.listen

### ISSUE THREAD

**Issue by bicicura** [laravel/echo#392]
### Echo Version

1.16.0

### Laravel Version

9.2

### PHP Version

8.0.2

### NPM Version

9.3.1

### Description

When trying to listen for a channel:
```js 
myChannel.listen('alertasContador', payload => {})
```

I got this fatal error: 
![image](https://github.com/laravel/echo/assets/56725472/f4206498-e801-48cb-92c9-f79b2fc7061c)

Event configuration:
```php
<?php

namespace App\Events;

use Illuminate\Broadcasting\Channel;
use Illuminate\Broadcasting\InteractsWithSockets;
use Illuminate\Contracts\Broadcasting\ShouldBroadcast;
use Illuminate\Contracts\Broadcasting\ShouldBroadcastNow;
use Illuminate\Foundation\Events\Dispatchable;
use Illuminate\Queue\SerializesModels;

class AlertaCount implements ShouldBroadcast
{
    use Dispatchable, InteractsWithSockets, SerializesModels;

    /**
     * Create a new event instance.
     *
     * @return void
     */
    public function __construct(public $cantidad)
    {
    }

    /**
     * Get the channels the event should broadcast on.
     *
     * @return \Illuminate\Broadcasting\Channel|array
     */
    public function broadcastOn()
    {
        return new Channel('alertas-cantidad');
    }

    /**
     * The event's broadcast name.
     */
    public function broadcastAs(): string
    {
        return 'alertasContador';
    }

}
```

Event route configuration:
```php
<?php

use Illuminate\Support\Facades\Broadcast;

Broadcast::channel('alertas-cantidad', function() {
    return true;
});

```

> [!NOTE]
> I am trying to connect to a public channel.

### Steps To Reproduce

1. Create a public channel in Laravel.
2. Connect to channel using Laravel Echo.
3. Try to listen to event.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by driesvints** [comment]
Does it work for you on v1.15.3?

**Comment by bicicura** [comment]
@driesvints Thanks for the quick response! I had the same issue with v1.15.3

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
