### ISSUE TITLE
Leave channel and disconnect right after

### ISSUE THREAD

**Issue by vatsake** [laravel/echo#393]
### Echo Version

1.16

### Laravel Version

11

### PHP Version

8.2

### NPM Version

9.7.1

### Description

I'm trying to create a websocket service class in Angular.

I would like to disconnect from server if "no one" is currently listening to any events.
If I send a "unlisten" request and then disconnect, browser will throw an error.

### Steps To Reproduce

```
const echo = new Echo({
      authEndpoint: '...,
      broadcaster: 'reverb',
      key: '...',
      wsHost: 'localhost',
      wsPort: '8080',
      wssPort: '8080',
      forceTLS: true,
      enabledTransports: ['ws', 'wss'],
})

echo.listen('...', '...', () => {});

setTimeout(() => {
      echo.leave(...) <- this message will not be sent.
      echo.disconnect()
}, 2000)
```

Browser throws error:
`WebSocket is already in CLOSING or CLOSED state.`

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
