### ISSUE TITLE
listen method does not work

### ISSUE THREAD

**Issue by lucasvmds** [laravel/echo#394]
### Echo Version

1.16.0

### Laravel Version

10.48.3

### PHP Version

8.3.4

### NPM Version

0.5.0

### Description

When trying to connect on a public channel, the events are not being received by the front end.
Searching the internet, I found a post on Laracasts where someone reported that the correct option would be to use the `on` method instead of the `listen` method mentioned in the documentation.
When doing this, my IDE (vscode) reported an error, but the code worked normally.

### Steps To Reproduce

Create a new Laravel application
Configure Laravel Echo for a public channel using the `listen` method
Trigger the event
Nothing happens
I change the method to `on`
The code works

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
