### ISSUE TITLE
cannot eager load 

### ISSUE THREAD

**Issue by shigg1120** [laravel/echo#41]
We cannot do something like this

```
broadcast(new ChatMessageSent($chat_message->load('user.profile'), Auth::user()))->toOthers();
```

When I console.log(event) in listen method.The relationship is not loaded.This would be a problem when we show data in Vue components since we cannot wirte the code below in .vue file

```
 $chat_message->user->profile->avatar
```

**Comment by morloderex** [comment]
I think you'll have to eager load it before passing it to the broadcast method.

**Comment by shigg1120** [comment]
I did.Did you actually try to see if it works?

**Comment by morloderex** [comment]
From your example abrove you are not doing that.. 
What i mean is this: 
`
$chat_message->load('user.profile')
broadcast(new ChatMessageSent($chat_message, Auth::user()))->toOthers();
`

**Comment by shigg1120** [comment]
i already did it thx

**Comment by huglester** [comment]
@shigg1120 probably would be good to close the issue? thanks

**Comment by shigg1120** [comment]
Anyone having the same problem??

**Comment by shigg1120** [comment]
toJson() fixed the issue
