### ISSUE TITLE
any plan to support triggering client events?

### ISSUE THREAD

**Issue by shwhl** [laravel/echo#47]
any plan to support triggering client events?

**Comment by morloderex** [comment]
Create a pr for it and see :)

**Comment by tlaverdure** [comment]
I may have something in the works in the next week or so.

**Comment by shigg1120** [comment]
nice one

**Comment by luiz-pv9** [comment]
This would be really helpful. There are actions that don't need to go through Laravel, such as "user is typing..." in a chat, for example. This is just a simple broadcast to a channel.

**Comment by woganmay** [comment]
Any news on this? I've got Echo working for receiving messages to the client, but sending stuff back from the client would be very helpful.

**Comment by lukepolo** [comment]
if your using pusher you can just use their native event triggers : 

https://pusher.com/docs/client_api_guide/client_events#trigger-events

**Comment by woganmay** [comment]
@lukepolo Thanks for the link! I'm using socket.io for now, but to be honest, looking at Pusher's pricing I can probably afford it for the app I plan on building.

**Comment by lukepolo** [comment]
@woganmay Gotcha, i dont think it would be terribly difficult to implement, but I do not have the time currently. But will need it for my app soon. So hopefully work will pay me to implement this soon!

**Comment by shigg1120** [comment]
The workaround for this is just make another instance of a channel and use "trigger" method right?If you are using Pusher right?

Does Echo have a method like it?

**Comment by tillkruss** [comment]
```js
var channel = Echo.join('foobar');

channel.here((users) => {
    channel.pusher.channels.channels[channel.name].trigger('client-foobar', { foo: 'bar' });
});
```

**Comment by shwhl** [comment]
Closing the issue, the `whisper` method and `listenForWhisper` method is available now.

**Comment by brunoinds** [comment]
Whisper does not solve the problem. It will be good to implement in the Laravel Echo library some way to trigger Events on the server. I know is not possible because Laravel does not listen for WS, but the JS under the hood could send a Post request....
