### ISSUE TITLE
Request: add `unlisten` method

### ISSUE THREAD

**Issue by deiucanta** [laravel/echo#51]
I need to stop listening for some events when the route changes (client-side). Currently I use `leave(channel)`, however, this might `unsubscribe` other events that were registered somewhere else in the app.

**Comment by vexii** [comment]
it looks like the is an [`stopListening`](https://github.com/laravel/echo/blob/master/src/channel/pusher-channel.ts#L100) call in `pusher-channel.ts`

**Comment by indigoram89** [comment]
this is necessary!

**Comment by shorlbeck** [comment]
+1 Definitely need this method.

**Comment by itsmill3rtime** [comment]
@shorlbeck @indigoram89 @vexii @deiucanta 

i did some searching around the web an was unable to find a posted solution but with some tinkering i found a temporary solution until they implement something in echo

in my vue component i wanted to only stop listening to events and not unsub from the channel when i went to a different page (component). so i put this within destroyed function but you could use it wherever you see fit

```
destroyed: function () {
            let self = this;
            Echo.private('projects.' + self.$route.params.project)
                .stopListening('DeploymentStepCommandAddedEvent')
                .stopListening('DeploymentStepCommandMovedEvent')
                .stopListening('DeploymentStepCommandRemovedEvent')
                .stopListening('DeploymentStepCommandUpdatedEvent');
        },
```


and these match up to the events i listened for

```
Echo.private('projects.' + self.$route.params.project)
                .listen('DeploymentStepCommandAddedEvent)
           ...... 

```

**Comment by Ifnot** [comment]
The [`stopListening`](https://github.com/laravel/echo/blob/master/src/channel/pusher-channel.ts#L100) method will only work with pusher driver.

With SocketIO there is no way to remove a previously added listener through Echo. The only way is to use the SocketIO API directly.

Adding a listener :
    Echo.connector.socket.on('blah', listener)

Removing the listener :
    Echo.connector.socket.removeListener('blah', listener)

But with this method you may verify the channel provenance as it will listen all subscriptions.

If we want a straightforward native solution we may need to add a way for [reverting the `on` method](https://github.com/laravel/echo/blob/master/src/channel/socketio-channel.ts#L108).

**Comment by pSchaub** [comment]
We really need this. 👍

**Comment by Ifnot** [comment]
With provenance i mean the channel name where the message comes from. In the message payload you have this information. If this is not important for you or if you have only one channel you can use this solution as is :)

**Comment by Xartrick** [comment]
While waiting for your proper solution, here is what I'm currently doing.

```js
export default {
	data() {
		return {
			listening: false
		};
	},
	
	created() {
		this.$echo.private('user.1').listen('.UserEvent', (data) => {
			if (!this.listening)
				return;
			
			// do stuff...
		});

		this.listening = true;
	},

	destroyed() {
		this.listening = true;
	}
};
```

Hope this helps some people out there (this may be viable for low amount of events only).

**Comment by an4ger** [comment]
Any news? It's a really big problem(

**Comment by cnk789** [comment]
Any updates?

**Comment by driesvints** [comment]
We're open to PRs.

**Comment by skollro** [comment]
Found a workaround to unbind a specific listener from an underlying Pusher channel subscription that I'd like to share with you. 👍🏻

```
const listener = (e) => { ... }
const channel = Echo.private('channel-name').listen('MyEvent', listener)

channel.subscription.unbind(channel.eventFormatter.format('MyEvent'), listener)
```

**Comment by Govar-Dev** [comment]
window.Echo.leave('listener')

**Comment by salehasadi** [comment]
> `window.Echo.leave('channel-name') `

I thin this will result in leaving that channel on page forever, till next page load, so maybe is not good idea.

**Comment by AdrianMrn** [comment]
Is there a way to stop listening to the `pusher:member_added` and `pusher:member_removed` events that are registered by `channel.joining()` and `channel.leaving()`? I tried `channel.stopListening('pusher:member_added');` and some other things, but this doesn't seem to work.
