### ISSUE TITLE
Pusher.ScriptReceivers[1] is not a function

### ISSUE THREAD

**Issue by happyDemon** [laravel/echo#54]
I'm not quite sure why I'm getting this error in the client.

Auth is going through fine to pusher, however the response doesn't get handled.

```
import Echo from "laravel-echo";

window.Echo = new Echo({
    broadcaster: 'pusher',
    key: 'MY KEY',
    cluster: 'eu'
});

window.teamChanel = window.Echo.private('team.'+window.teamId);
```

**Comment by aaronhuisinga** [comment]
I'm seeing this as well. Pusher notifications are still functioning properly, but it shows in my console on page load.

**Comment by sirfanqadir** [comment]
Issue solved when move the script in Footer

**Comment by Suresh-Yenni** [comment]
Can anyone tell me why is this not possible ? 
As in my application there are many things at multiple file which am rendering twice but those work fine.
What could be possible problem with pusher.

**Comment by Balram-chaudhary** [comment]
I have found this error  because i forget to comment testing pusher server connection in my footer section.

**Comment by Balram-chaudhary** [comment]
It is  a realtime notification system but it needs to be autheticate or logged by admin panel.You can make it a realtime notification system by changing some coding.
