### ISSUE TITLE
TypeError: request.headers.set is not a function

### ISSUE THREAD

**Issue by warang580** [laravel/echo#61]
``` javascript
Vue.http.interceptors.push(function (request, next) {
    if (_this.socketId()) {
        request.headers.set('X-Socket-ID', _this.socketId());
    }
    next();
});
```

`Uncaught (in promise) TypeError: request.headers.set is not a function(…)`

I replaced it by

``` javascript
request.headers['X-Socket-ID'] = _this.socketId();
```

in `node_modules/laravel-echo/dist/echo.js:523` and it worked.

Can you fix it ? I don't know how typescript works.
I can make a pull request to change `src/echo.ts:53` but I don't know if it's enough.

**Comment by happyDemon** [comment]
@warang580  updating your vue-router package to the latest release fixes this.

**Comment by otiagovicente** [comment]
Loading Echo before it all solves too

**Comment by desfree** [comment]
Thanks, it works to me

**Comment by bhavinjr** [comment]
if you are using axios then no need to add `X-Socket-ID` it will add automatically
