### ISSUE TITLE
Event still broadcasts to Current User

### ISSUE THREAD

**Issue by pfeiferchristopher** [laravel/echo#7]
So even though I've added `$this->dontBroadcastToCurrentUser();` in the constructor of all my broadcasted events that I don't want to duplicate. It is still going out to the current user showing duplicates. It seems as though `socket_id` is being properly set to the session, as well as being sent out with the events.

Not sure if it's because of this or not, but during the Laravel Echo demo on Laracasts it was mentioned and showed that Echo does a `/broadcasting/auth` API call which is not occuring with my current setup. Is that only for private channels?

Oh and real quick within BroadcastServiceProvider I keep getting method "channel" not found. This is the error:
```
ErrorException in BroadcastManager.php line 281:
call_user_func_array() expects parameter 1 to be a valid callback, class 'Illuminate\Broadcasting\Broadcasters\PusherBroadcaster' does not have a method 'channel'
```

Of course I appreciate any help, I know this all pre-release.

**Comment by tlaverdure** [comment]
@pfeiferchristopher not much is documented yet, but hopefully this helps:

- Laravel looks for the header `X-Socket-Id` when using `$this->dontBroadcastToCurrentUser();` to identify which user to not to send events to. 

- `/broadcasting/auth` is only used when authenticating a user for private or presence channels.

- The method `channel()` no longer exists, use `auth()` instead with Laravel 5.3

**Comment by pfeiferchristopher** [comment]
@tlaverdure thanks for your reply!

I did see that `X-Socket-Id` must be in the header, but what I'm confused on is in the Laravel Echo demo on Laracasts it never showed him adding that manually? I'm also confused as to where I'd have to add that header in. Is it within Echo itself?

**Comment by Francismori7** [comment]
@pfeiferchristopher https://github.com/taylorotwell/echo-demo/blob/master/resources/assets/js/bootstrap/echo.js#L10-L17

**Comment by pfeiferchristopher** [comment]
https://github.com/laravel/framework/issues/13929

**Comment by ssi-anik** [comment]
> @pfeiferchristopher not much is documented yet, but hopefully this helps:
> 
> * Laravel looks for the header `X-Socket-Id` when using `$this->dontBroadcastToCurrentUser();` to identify which user to not to send events to.
> * `/broadcasting/auth` is only used when authenticating a user for private or presence channels.
> * The method `channel()` no longer exists, use `auth()` instead with Laravel 5.3

Laravel changed `X-Socket-Id` to `X-Socket-ID` in `Illuminate/Broadcasting/BroadcastManager.php:90`
