### ISSUE TITLE
Uncaught SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by huchenhai** [laravel/echo#71]
I just follow the steps by documentation, but on my js file it shows this error that i can not import Echo from laravel-echo cuz import is invalid token. How to fix this ?

**Comment by huchenhai** [comment]
![image](https://cloud.githubusercontent.com/assets/14668354/21321867/a6010584-c5e4-11e6-95b9-a09ce22a4a39.png)
![image](https://cloud.githubusercontent.com/assets/14668354/21321890/b2c2fe08-c5e4-11e6-9eaa-3079b5d49bd8.png)

**Comment by scheMeZa** [comment]
I'm experiencing the same issue and did some research. I believe it's because node isn't up to date.

**Comment by Luppakorva** [comment]
@huchenhai and @scheMeZa 

Did you guys ever solve this? I'm having the same problem with Laravel 5.4. node is up to date though

**Comment by huchenhai** [comment]
@Luppakorva I solved this by compiling the ES6 and gulp, just follow this instruction step by step https://www.sitepoint.com/meet-elixir-the-laravel-way-of-compiling-assets/
I also referenced it on my QQ blog http://user.qzone.qq.com/458159038/blog/1482184601, if you have any questions

**Comment by Luppakorva** [comment]
@huchenhai Many thanks!
