### ISSUE TITLE
How i can configure it with socket io? 

### ISSUE THREAD

**Issue by mediaceh** [laravel/echo#74]
In the docs not have info except configure broadcaster and host. I want set transport and max try for connect. Default it will be connecting to my server until it no shot down!  How i can configure it with socket io?

**Comment by KekoApp** [comment]
Hi Mediaceh,

Currently Echo standalone only supports pusher. To use Socket.io you will need to use https://github.com/tlaverdure/laravel-echo-server along with Laravel Echo itself.

Setup is easy and documented, just be sure to double check the configuration json for correct authentication hosts / settings.

**Comment by driesvints** [comment]
Should be documented now.
