### ISSUE TITLE
Ability to pass on option "path" to socket io connection

### ISSUE THREAD

**Issue by mahenpatil** [laravel/echo#80]
Please allow passing on path in options to socket io connector.

It is not possible to use different route than "/" because anything after "/" is treated as namespace.

e.g.
var echo = new Echo({
    broadcaster: 'socket.io',
    host: 'http://localhost',
    path: '/myapp/socket.io/'
});

This path should be used while creating io socket as:

this.socket = io(this.options.host, {path: this.options.path});

Thanks very much in advance.

**Comment by barryvdh** [comment]
Like this? https://github.com/laravel/echo/issues/80

**Comment by mahenpatil** [comment]
Yes please, thanks a lot.
