### ISSUE TITLE
catch disconnect event

### ISSUE THREAD

**Issue by shigg1120** [laravel/echo#90]
Is there any way to listen for a disconnect event or an event like "cannot establish connection"?

**Comment by seedgabo** [comment]
any updates of this?

**Comment by smcgovern** [comment]
Is this a no? I've been trying to figure this out.

**Comment by clod986** [comment]
someone found a way https://stackoverflow.com/questions/47453025/laravel-echo-error-handling-with-pusher/47648234

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
