### ISSUE TITLE
Eager-loaded data not sent to the client

### ISSUE THREAD

**Issue by Demers94** [laravel/echo#95]
**Note: I'm not sure if this is an issue with Echo or with Laravel's broadcasting system, so I will open an issue on both**

When a model that eager-loads other models is passed to an event that implements `ShouldBroadcast` and that is received by Laravel Echo, the eager-loaded models are not received by the client.

Here's is an example with a `Post` model that belongs to a `User`.

Controller method where the post is created:

```
$post = Post::create([
    'user_id' => 1,
    'topic_id' => request('topic_id'),
    'body' => request('body'),
]);

$post = Post::with('user')->find($post->id);

 event(new PostCreated($post));
``` 

Here is the event class:

```
class PostCreated implements ShouldBroadcast
{
    use Dispatchable, InteractsWithSockets, SerializesModels;

    public $post;

    /**
     * Create a new event instance.
     *
     * @return void
     */
    public function __construct($post)
    {
        $this->post = $post;
        echo $post->user->name; // This works, name is echo'd
    }

    /**
     * Get the channels the event should broadcast on.
     *
     * @return Channel|array
     */
    public function broadcastOn()
    {
        return new Channel('topics');
    }
}
``` 

And finally the JS code : 

``` 
Echo.channel('topics')
    .listen('PostCreated', (e) => {
        console.log(e.post); // Can see the post object, but not the user property
        console.log(e.post.user); // Undefined
    });
``` 

Why is `post.user`  undefined in the JS code, while `$post->user` is not in the event class?

Do I need to do something special to ensure that the eager-loaded models are passed along when the event is broadcasted? 

I'm using Pusher, if that matters.

Thank you for the help!

**Comment by allentcm** [comment]
I'm having the same problem with Pusher also. Below is my temporally solution for this issue. Hope this issue can be solved soon.

1. In the event class convert the public exposed variable to JSON 
i.e. `$this->post = $post->toJson();`
2. At the JS side convert the JSON string back to object 
i.e. `var post = JSON.parse(e.post);`

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
