### ISSUE TITLE
Spy users

### ISSUE THREAD

**Issue by jbrooksuk** [laravel/echo#96]
It's currently _impossible_ to see all members of a presence channel without appearing in it yourself.

According to the [Pusher docs](https://support.pusher.com/hc/en-us/articles/235605227-See-the-members-of-a-presence-channel-without-appearing-in-it), this can be achieved through the use of _spy_ users.

The way they do it is to create a separate Pusher instance that authenticates as a `spy` user, which is ignored from any polling of users. https://github.com/pusher/presence-spy-example/blob/master/script.js#L22-L31

For this to work with Laravel, we'd need to extend authentication to accept spy users (perhaps as a variation of the actual user?).

Thoughts?

**Comment by taylorotwell** [comment]
Does the authorization part really care about spy users? I would like to see this implemented eventually.

**Comment by driesvints** [comment]
I've thoroughly searched for this in the Pusher documentation but the docs don't indicate the usage of this anywhere. The link you have above for the docs is gone btw. I only found this: https://support.pusher.com/hc/en-us/articles/360019268734-How-do-I-see-the-members-of-a-presence-channel-without-appearing-in-it-

But that doesn't works anymore. The code from the repo doesn't seems valid anymore. I there think this isn't possible anymore with Pusher.

**Comment by driesvints** [comment]
I received the following answer from Pusher:

> Hi Dries, 
> 
> Thanks for getting in touch. I believe the tutorial uses standard functionality to achieve the spying ability. The isSpy flag is an additional, custom auth param that doesn't have any direct bearing on the authentication behaviour. Instead this is just passed through the auth flow and used in the client to determine if the user is a spy or not, and if not report the user in the logged user list. https://github.com/pusher/presence-spy-example/blob/master/script.js#L39
> 
> Channels doesn't do any user filtering based on the metadata, this happens in the line linked above by the client function. 
> 
> In any case, it may be that this example is now out of date as we expose an API endpoint that allows you to query presence users in a channel - see https://pusher.com/docs/channels/server_api/http-api#presence-users.
> 
> Let me know if this helps at all. 
> 
> Thanks
> Ben

So this just seems like an example rather than a real feature.
