### ISSUE TITLE
If this fails so does your app, it should be able to fail and continue

### ISSUE THREAD

**Issue by robclancy** [laravel/echo#97]
Using ember I made a service for echo and had made Stubs for when pusher isn't configured or is failing because the app should run with or without pusher.

This worked to stop pusher down causing our whole app to be down until the jQuery `beforeSend` header was set. Now I have to hack echo, extend it to stop all these things it registers before even knowing if it can get a valid connection.

You should be able to disable any of these registrations https://github.com/laravel/echo/blob/master/src/echo.ts#L32. Or even better explicitly specify what you are using and only register that.

**Comment by driesvints** [comment]
Hmm, maybe adding a config option to disable registrations isn't a bad idea. Please also have a look at https://github.com/laravel/echo/issues/152

I think maybe a config option with a key `interceptors` and an array of `['axios', 'vue', 'jquery']` could. be the default which you can overwrite. Would that be helpful?

**Comment by robclancy** [comment]
I've had multiple problems because there is auto stuff and hardcoded things. It should be done like anything else is done in Laravel with PHP. You configure drivers and use what you specify. Laravel doesn't do any "if predis exists configure it", it will configure it if you tell it to. You can easily have multiple dependencies in the frontend that has nothing to do with echo but because echo is just checking if any random library exists in global scope... that sentence alone shows how wrong it is right now.
