### ISSUE TITLE
Cannot set property 'socketId' of undefined

### ISSUE THREAD

**Issue by poxin13** [laravel/echo#99]
Moving this over from laravel-echo-server as it appears more an issue with Echo than with the socket.io server. I'm attempting a simple demo of working with redis/socket.io with a presence channel using the latest version of Laravel 5.4, Echo, and Vue.

I have a simple channel defined as:
```
Broadcast::channel('chat', function ($user) {
    return [
        'id' => $user->id,
        'name' => $user->name
    ];
});
```

Then in my vue file:
```
mounted() {
    Echo.join(`chat`)
        .here((users) => {
            console.log(users);
        })
        .joining((user) => {
            console.log(user.name);
        })
        .leaving((user) => {
            console.log(user.name);
        });
}
```

I see the key being created in redis, however in the laravel-echo-server terminal I am getting the error:
```
[1:08:07 AM] - ZRyZ2AiHjX8nZMLVAAAC authenticated for: presence-chat
[1:08:07 AM] - ZRyZ2AiHjX8nZMLVAAAC joined channel: presence-chat
(node:12234) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 5): TypeError: Cannot set property 'socketId' of undefined
```

I'm a little stumped what to look for. socketId always seems to be 'undefined'. Even attempting to log the socketid is always undefined from `var socketId = Echo.socketId();`

**Comment by filipegar** [comment]
@poxin13 i had the same problem here; reverting laravel-echo-server to 1.2.4 solved it.

i don't think its something broken on laravel-echo side.

**Comment by scheMeZa** [comment]
Same problem.

**Comment by scheMeZa** [comment]
Thank you for the suggestion to pull back to 1.2.4; it worked.

**Comment by poxin13** [comment]
That seems to work, closing this

**Comment by skatetdieu** [comment]
For anyone else running into this, I figured out the issue and comment the solution on this here:
https://github.com/tlaverdure/laravel-echo-server/issues/202#issuecomment-323249811
